### PR TITLE
Insert new synchronized jitGetExceptionTableFromPC path as fallback

### LINKED ISSUE #19249: OpenJDK java/lang/Thread/virtual/stress/TimedGet Invalid JIT return address
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Release_testList_0/16/ - [p8-java1-ibm07](https://openj9-jenkins.osuosl.org/computer/p8-java1-ibm07)
jdk_lang_j9_0
java/lang/Thread/virtual/stress/TimedGet.java

https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Test_openjdk21_j9_sanity.openjdk_ppc64_aix_Release_testList_0/16/openjdk_test_output.tar.gz
```
18:33:51  STDOUT:
18:33:51  STDERR:
18:33:51  
18:33:51  
18:33:51  *** Invalid JIT return address 00000100114ABE44 in 0000010023C8BA70
18:33:51  
18:33:51  22:19:06.319 0x10023c92e00    j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDK21_ppc64_aix_Release/openj9/runtime/vm/swalk.c:1629: ((0 ))
```

### LINKED ISSUE #22371: Stack-walker jitInfo race condition
## Issue

Following up from https://github.com/eclipse-openj9/openj9/issues/19249#issuecomment-3109557980 :

A race condition in the stack-walker, specifically getting a method's jitInfo/artifact/metadata. 
The AVLTree holding the jitInfo hash-tables is synchronized with VMAccess, and the hash-tables themselves are synchronized with a monitor. 
When a stack-walker accesses the hash-tables to retrieve a certain jitInfo (when walking, at every JIT frame, if cache miss) it does not hold the monitor, hence if the hash-table is being modified (e.g. JIT inserting a new compiled method's jitInfo) the stack-walker can retrieve incorrect info.

### Current state
* CodeCache changes acquire VMExclusiveAccess (modifies AVLTree)
* JITInfo changes acquire monitor (modifies hash-table)
* GC gets VMAccess (not exclusive)
* Stack-walkers don’t use synchrony when getting jitInfo
* No need to synchronize AVLTree access when adding/accessing/removing jitInfo, only hash-table.

### Solutions
1. Use VMExclusiveAccess/VMAccess for jitInfo changes/access (hash-table)
   - Using existing reader/writer synchrony infrastructure
   - No need for monitor if hash-table access use VMAccess for synchrony
   - Using VMAccess on hash-table synchrony intrudes/may-hold other VMExclusiveAccess actions unnecessarily
   - Least intrusive solution(?)
2. Add monitor to stack-walker
   - “Obvious” solution, not performant (Sequentializes different stack-walkers, getting jitInfo)
   - Might be better than expected if cache-hit most of the time and rarely need the monitor when stack walking(?)
   - Walking parked virtual-threads continuation does not use the cache.
3. Use reader/writer synchrony (instead of normal monitor) in artifact modification/access
   - “Obvious” solution improved
   - Change monitor to reader/writer mutex
   - Overhead of reader/writer synchrony(?)

Ended up prototyping solution number 3.

### Drivers 

Testing 4 different drivers:
* A: Base/Nightly build
* B: Replace hash-table monitor with reader/writer mutex
  * Insert/remove artifact gets writer mutex
  * Retrieve artifact gets reader mutex
  * Does not solve race-condition, stack-walker does not get the mutex
  * Evaluate reader/writer mutex overhead
* C: Stack-walker gets reader mutex when needed
  * Only get mutex when getting jitInfo/artifact, if cache miss and going to hash-table
  * Possible many-short mutex acquire/release
* D: Stack-walker always hold reader mutex
  * Acquire reader mutex during all of stack-walk
  * Few-long mutex acquire/release
  * Holds reader access more than needed
* E: Solution 2 (use the same monitor for the stackwalker)
  * Will synchronize stack-walkers getting jitInfo
  * Only when accessing hash-table (cache-miss)

### Results (UPDATED)

| SPECjbb2015  | max-jOPS | Diff    |
|---|----------|---------|
| A | 67801    | 100.00% |
| B | 68292    | 100.73% |
| C | 67699    | 99.85%  |
| D | 36185    | 53.37%  |
| E | 67894    | 100.14% |

Currently looking at profiles, only immediate apparent observation in D 25% of time spent in `omrthread_spinlock_acquire`

## Conclusion

Seem like C (solution 3) and E (solution 2) are valid solutions.

~~Best solution is "C", getting the mutex only when needed even if more frequent acquires/releases.
Overhead from using reader/writer mutex instead of the monitor alone is 4.5%, and using the mutex to solve the race condition is another 1%.~~

~~Might be worth prototyping and measuring solution number 2, as difference between C and D might indicate high cache-hits, making solution 2 less problematic. But with virtual threads, you don't have the cache used, and having GC stack-walking many vThreads and synchronize around the monitor to stack-walk might be problematic, depend on parallel GC threads/stack-walkers.~~

~~I'll analyze profiles of the different drivers to see if something might help reducing the 4.5% effected by the reader/writer mutex change.~~

### PR DESCRIPTION
**Pull request by rmnattas**
jitGetExceptionTableFromPC is not synchronized, this can cause a race- condition loading exceptionTable/jitInfo if the JIT is updating it.

The race-condition is rare and synchronizing jitGetExceptionTableFromPC can be costly, hence this implements a synchronized fallback path.

New structure:
- Stack-walker loads exceptionTable/jitInfo (non-synchronized)
- If NULL it assumes it's an interpreter transition
- Checks PC in i2jReturnTable
- If not in i2jReturnTable:
  - [NEW] Use synchronized loading of exceptionTable/jitInfo
  - Report invalidJITReturnAddress error

Implementation uses a new field in J9JavaVM struct to pass the JIT-ArtifactMonitor to the stack-walker.

Closes: #22371
Fixes: #19249

### CODE REVIEW

**Comment by rmnattas** [comment]
@vijaysun-omr @zl-wang

File: runtime/codert_vm/jswalk.c [hunk 1]
```diff
@@ -172,6 +172,7 @@ UDATA  jitWalkStackFrames(J9StackWalkState *walkState)
 	walkState->dropToCurrentFrame = jitDropToCurrentFrame;
 
 	while ((walkState->jitInfo = jitGetExceptionTable(walkState)) != NULL) {
+		jitInfoSecondTryMatch:;
```
Comment (zl-wang) [inline runtime/codert_vm/jswalk.c]: goto inside-loop from outside-loop looks fairly exceptional.  i am wondering if there is a better way to code it up.

File: runtime/oti/j9nonbuilder.h [hunk 2]
```diff
@@ -6749,6 +6749,7 @@ typedef struct J9JavaVM {
 	/* Protects constRefArrayPool and J9Class.constRefArrays. */
 	omrthread_monitor_t constRefsMutex;
 #endif /* defined(J9VM_OPT_OPENJDK_METHODHANDLE) */
+	omrthread_monitor_t jitArtifactMonitor;
```
Comment (zl-wang) [inline runtime/oti/j9nonbuilder.h:6752]: otherwise, it looks reasonable to me. I would request a review from @TobiAjila and @babsingh

Comment (babsingh) [reply runtime/oti/j9nonbuilder.h:6752]: Added @gacholio for the review.

File: runtime/codert_vm/jswalk.c (hunk 1 above)
Comment (rmnattas) [reply runtime/codert_vm/jswalk.c]: Another possibility would be recursive calling of `jitWalkStackFrames`, but not positive if there would be side-effects that would deem it un-sound, have to look further. Also theoretically can end up calling the recursive fallback more than once.

Another possibility is returning with `J9_STACKWALK_KEEP_ITERATING` which might end up re-calling `jitWalkStackFrames` given the parent loop, but seem to have more side-effects that need to be checked for correct execution.

This is safe as there's no induction variable affected by the goto, and goto is shortly after the while-loop end point (no side-effects in between). Also this is for fallback only and there's few goto's in the stack-walker code already. Hence my direction to use it.

Comment (gacholio) [inline runtime/codert_vm/jswalk.c]: Labels at the start of the line, please.

File: runtime/codert_vm/jswalk.c [hunk 3]
```diff
@@ -274,6 +275,10 @@ UDATA  jitWalkStackFrames(J9StackWalkState *walkState)
 				goto i2jTransition;
 			}
 		}
+		// Before determining its an invalidJITReturnAddress, try loading jitInfo again synchronized
```
Comment (gacholio) [inline runtime/codert_vm/jswalk.c]: This will need to be excluded in ASGCT mode, i.e. the opposite of:

https://github.com/eclipse-openj9/openj9/blob/aa078f626997a78e97f13a4a953762f21a44ea27/runtime/vm/swalk.c#L162

Also, C++ comments not allowed in C files.

Comment (gacholio) [reply runtime/codert_vm/jswalk.c]: (opposite is NO_BITS_SET)

**Comment by gacholio** [comment]
Under exactly what circumstances could a compled method be running on a stack and not in the exception table (which clearly happens during compilation)?

**Comment by gacholio** [comment]
Also, I see no use of the monitor other than in the sync retry, so it's not protecting anything at all.

File: runtime/codert_vm/jswalk.c (hunk 3 above)
Comment (zl-wang) [reply runtime/codert_vm/jswalk.c]: also, is there a possibility of dead-loop? i.e. do we need to (or, put code in place to) prevent it from this goto again and again?

**Comment by zl-wang** [comment]
> Also, I see no use of the monitor other than in the sync retry, so it's not protecting anything at all.

presumably, the monitor was used in certain case(s) when JIT compiler thread(s) updated the AVL trees (if not, why creating it in the first place)? after all, there are multiple threads potentially updating it at roughly the same time.

**Comment by rmnattas** [comment]
> Also, I see no use of the monitor other than in the sync retry, so it's not protecting anything at all.

[HERE](https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/runtime/ArtifactManager.cpp#L140)'s an exapmle where its used, it locks the monitor in the constructor and frees it in the destructor.

> Under exactly what circumstances could a compled method be running on a stack and not in the exception table (which clearly happens during compilation)?

Not sure what you mean here?

**Comment by zl-wang** [comment]
> Under exactly what circumstances could a compled method be running on a stack and not in the exception table (which clearly happens during compilation)?

we examined a few core files.  the metaData were still in AVL trees, but the modified (in this PR) look-up failed to find it. such that, reasonably suspecting out-of-sync (update and look-up) did the trick.  so, this solution without paying costly performance overhead.

File: runtime/codert_vm/jswalk.c (hunk 3 above)
Comment (rmnattas) [reply runtime/codert_vm/jswalk.c]: > This will need to be excluded in ASGCT mode

I'll add code to not perform the second synchronized loading if `J9_PRIVATE_FLAGS2_ASYNC_GET_CALL_TRACE` is set.

Comment (rmnattas) [reply runtime/codert_vm/jswalk.c]: > also, is there a possibility of dead-loop? i.e. do we need to (or, put code in place to) prevent it from this goto again and again?

I don't see how that's possible. The condition to enter the loop using the goto is the same as the while-loop condition (retrieved jitInfo is not NULL). There's only `return` statements in the while-loop, no `break` statements. 

If it reaches the fallback path again it 1) broke out of the while-loop naturally by breaking the while-loop condition (retrieving NULL for the jitInfo) and 2) passed by the interpreter i2jReturnTable check.

File: runtime/codert_vm/jswalk.c (hunk 1 above)
Comment (rmnattas) [reply runtime/codert_vm/jswalk.c]: Fixed

File: runtime/codert_vm/jswalk.c (hunk 3 above)
Comment (rmnattas) [reply runtime/codert_vm/jswalk.c]: Fixed `J9_PRIVATE_FLAGS2_ASYNC_GET_CALL_TRACE` and comment

File: runtime/compiler/runtime/ArtifactManager.cpp [hunk 4]
```diff
@@ -74,6 +74,7 @@ TR_TranslationArtifactManager::TR_TranslationArtifactManager(J9AVLTree *translat
     TR_ASSERT(translationArtifacts, "translationArtifacts must not be null");
     TR_ASSERT(vm, "vm must not be null");
     TR_ASSERT(monitor, "monitor must not be null");
+    vm->jitArtifactMonitor = (omrthread_monitor_t)_monitor->getVMMonitor();
```
Comment (gacholio) [inline runtime/compiler/runtime/ArtifactManager.cpp:77]: Does this assert on failure?

**Comment by gacholio** [comment]
> locks the monitor in the constructor and frees it in the destructor.

Apologies, missed the critical section indirection of the montior.

In general, I dislike making a change without understanding why it fixes something (if this even does - do we know, or is this speculative?).

The AVL trees are modified only under exclusive VM access, and all stack walks must take place with VM access (or exclusive), so there is no possibility that we miss an AVL update in another thread.

There may need to be a read barrier in `hash_jit_artifact_search` and a final write barrier at the end of `hash_jit_artifact_insert`.

The new monitor use would issue those barriers as part of the contract even if it added no other actual protection.

I do agree that this change is basically harmless in that we take the expected fast path every time the metadata is correct.

**Comment by zl-wang** [comment]
we have never been able to recreate the failure by running the test ourselves.  it only happened once every couple months in Jenkins tests (across platforms i believed, albeit more often on p).

**Comment by zl-wang** [comment]
out of curiosity, @gacholio :   compilation threads are not in the EXCLUSIVE set, right? so, i can imagine two or more of them can request for EXCLUSIVE, and granted at roughly the same time?  or not?

**Comment by rmnattas** [comment]
The race-condition is in the hash-table (that stores jitInfo) pointed at by the AVL Tree, which this code solves by taking the monitor synchronizing accesses to the hash-table.

JIT uses ArtifactManager's `retrieveArtifact()` which gets the monitor then calls `hash_jit_artifact_search` (providing the hash-table from the AVL Tree), while the stack-walker calls `hash_jit_artifact_search` directly without synchronizing.

**Comment by rmnattas** [comment]
> There may need to be a read barrier in hash_jit_artifact_search and a final write barrier at the end of hash_jit_artifact_insert. 

There's write barrier in `hash_jit_artifact_insert_range`, but doesn't seem to be a corresponding read barrier in `hash_jit_artifact_search`.

**Comment by rmnattas** [comment]
> The AVL trees are modified only under exclusive VM access, and all stack walks must take place with VM access (or exclusive), so there is no possibility that we miss an AVL update in another thread.

But modifying the hash-table only uses the monitor, not VMAccess. AVL Tree is modified when insert/remove codeCache. Hash-table is for jitInfo synchronized by the monitor.

**Comment by gacholio** [comment]
The existing write barrier is to ensure all writes take place before we put the entry in the hash table. Should there be another at the end?

**Comment by gacholio** [comment]
A race populating the hash table would result in a lost entry (i.e. two threads cosuming the same slot). That is not what was reported here, IIRC (entry in the table correctly but somehow not found in the lookup).

**Comment by rmnattas** [comment]
I believe the failing situation addressed here is a race between one populating the hash-table (holding the monitor) and one retrieving from it (stack-walker, not holding it), causing the retriever to get incorrect data.

**Comment by zl-wang** [comment]
> A race populating the hash table would result in a lost entry (i.e. two threads cosuming the same slot). That is not what was reported here, IIRC (entry in the table correctly but somehow not found in the lookup).

Sure. I didn't think of hashing to the same slot. Just curious of the possibility.  Sorry, for the deviation.
Hashing conflict does increase the chances of observing out of order (if not entirely losing it).

File: runtime/compiler/runtime/ArtifactManager.cpp (hunk 4 above)
Comment (zl-wang) [reply runtime/compiler/runtime/ArtifactManager.cpp:77]: no.  the failure error msg always been:  Invalid JIT return addr (in jswalk).

**Comment by zl-wang** [comment]
hopefully addressed all of your questions and concerns. please consider ticking it off when ready. i will follow up then.

File: runtime/compiler/runtime/ArtifactManager.cpp (hunk 4 above)
Comment (gacholio) [reply runtime/compiler/runtime/ArtifactManager.cpp:77]: This does not answer the question - monitor allocation can fail, and there's no check here. Presumably we would crash trying to enter a NULL monitor later on.

**Comment by gacholio** [comment]
> please consider ticking it off

I'd rather see it fixed properly than stick in a work-around. Would the extra barriers suffice for the mis-read case that we believe is occurring?

It occurs to me that there must already be external synchronization around the insert, or we would end up in the race fr the slot. We would be seeing failures all over the place if that were the case.

File: runtime/compiler/runtime/ArtifactManager.cpp (hunk 4 above)
Comment (zl-wang) [reply runtime/compiler/runtime/ArtifactManager.cpp:77]: it looks like more appropriate to fail it earlier outside proactively (when it was allocated), instead of passively late checking. certainly beyond this PR.

Comment (rmnattas) [reply runtime/compiler/runtime/ArtifactManager.cpp:77]: The `TR_TranslationArtifactManager` object is not constructed if monitor is NULL, which kinda makes the assert redundant:
https://github.com/eclipse-openj9/openj9/blob/master/runtime/compiler/runtime/ArtifactManager.cpp#L54-L59

Also the criticalSection usage doesn't check if monitor is NULL either. Hence would fail there too.

**Comment by zl-wang** [comment]
i would think this is a proper fix, since the same monitor is used in insertion and 2nd pass of extraction, while you are not willing to pay the expected/verified (as well) high cost of extracting always under monitor.

**Review by gacholio — APPROVED** [review]

**Review by zl-wang — APPROVED** [review]

**Comment by zl-wang** [comment]
Jenkins test sanity aix,plinux,xlinux,zlinux jdk8,jdk21

**Comment by zl-wang** [comment]
3 failures in total: all known occasional happening and unrelated to this PR.  merging ...

File: runtime/codert_vm/jswalk.c [hunk 5]
```diff
@@ -274,6 +275,11 @@ UDATA  jitWalkStackFrames(J9StackWalkState *walkState)
 				goto i2jTransition;
 			}
 		}
+		/* Before determining its an invalidJITReturnAddress, try loading jitInfo again synchronized */
+		if ((J9_ARE_NO_BITS_SET(walkState->currentThread->privateFlags2, J9_PRIVATE_FLAGS2_ASYNC_GET_CALL_TRACE)) &&
+			((walkState->jitInfo = jitGetExceptionTableFromPCSync(walkState->walkThread, (UDATA)walkState->pc, TRUE)) != NULL)) {
```
Comment (keithc-ca) [inline runtime/codert_vm/jswalk.c:280]: Formatting: `&&` should begin the second line and `) {` should be on a third line by itself.

File: runtime/codert_vm/jswalk.c [hunk 6]
```diff
@@ -1424,6 +1430,11 @@ static J9JITExceptionTable * jitGetExceptionTable(J9StackWalkState * walkState)
 
 	if (result) return result;
 
+	// Try loading jitInfo again with synchronization
```
Comment (keithc-ca) [inline runtime/codert_vm/jswalk.c:1433]: This is C code, C++ style comments are not allowed (and a period is missing).

File: runtime/codert_vm/jswalk.c [hunk 7]
```diff
@@ -1424,6 +1430,11 @@ static J9JITExceptionTable * jitGetExceptionTable(J9StackWalkState * walkState)
...
+	result = jitGetExceptionTableFromPCSync(walkState->walkThread, (UDATA)walkState->pc, TRUE);
+
+	if (result) return result;
```
Comment (keithc-ca) [inline runtime/codert_vm/jswalk.c:1436]: Missing braces, should not be on one line.

**Review by keithc-ca — COMMENTED** [review]
Please create a follow-up change to address these issues.

**Comment by keithc-ca** [comment]
@rmnattas A gentle reminder regarding https://github.com/eclipse-openj9/openj9/pull/23742#pullrequestreview-4129238865.
