### PR TITLE
Ensure env is not NULL when calling checked JNI functions

### LINKED ISSUE #16665: Xcheck:jni does not validate NULL value of JNIEnv
Java -version output
------------------
openjdk version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Open Edition 11.0.16.1 (build 11.0.16.1+1)
Eclipse OpenJ9 VM 11.0.16.1 (build openj9-0.33.1, JRE 11 Linux amd64-64-Bit Compressed References 20220818_500 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 84b84a0409 based on jdk-11.0.16.1+1)

Summary of problem
------------------
OpenJ9 cannot validate the use of NULL for JNIEnv even Xcheck:jni is enabled.
e.g., GetBooleanField(**NULL**, jobject, jfieldID)

According to the JNI specification, the first argument of GetBooleanField  must not be NULL.
Passing a NULL as a first argument of GetBooleanField lead to a segmentation fault on OpenJ9.
However, Hotspot handles this situation correctly and returns an error message.

```
Testing_EAN_JNI: FATAL ERROR in native method: Using JNIEnv in the wrong thread
```

### PR DESCRIPTION
**Pull request by ehrenjulzert**
Fixes #16665

### CODE REVIEW

**Comment by ehrenjulzert** [comment]
@tajila , @gacholio , does this look like a reasonable approach to solving this issue? Basically I've added a `globalJavaVM` variable that stores a reference to the java VM when `jniCheckMemoryInit` is called, which is then used in `jniCheckFatalErrorNLS` to get the `env` when `env` is null. I also needed to change every checked JNI method to not use the `env` before calling `jniCheckArgs`, since the `env` passed in could be null.

**Comment by gacholio** [comment]
The idea is right, but I would just use the global VM directly. Also, the check for the env should be comparing it to the result of `currentVMThread(globalVM)` rather than explicitly NULL checking it (the result of the function call itself should be NULL checked to test if the current thread is attached to the VM).

**Comment by ehrenjulzert** [comment]
> the check for the env should be comparing it to the result of currentVMThread(globalVM)

I'm only checking for NULL because there is already an existing check in `jniCheckArgs` that ensures the thread is the current VM thread here: https://github.com/mushfek/openj9_dev/blob/5b2b4680c8ed5cc2b593b2ba772c04e1d964484a/runtime/jnichk/jnicheck.c#L564

Do you think I should just lump the NULL case into the existing check instead of having it separate?

**Comment by gacholio** [comment]
I think combining them makes sense. The NULL case is something that basically never occurs outside of error test cases.

**Comment by ehrenjulzert** [comment]
Okay I added your suggestions @gacholio , and am ready for review

File: runtime/jnichk/jnicheck.c [hunk 1]
```diff
@@ -548,21 +548,26 @@ jniCheckCallA(const char* function, JNIEnv* env, jobject receiver, UDATA methodT
 void
 jniCheckArgs(const char *function, int exceptionSafe, int criticalSafe, J9JniCheckLocalRefState *refTracking, const U_32 *descriptor, JNIEnv *env, ...)
 {
-	J9JavaVM *vm = ((J9VMThread*)env)->javaVM;
-	PORT_ACCESS_FROM_JAVAVM(vm);
+	J9JavaVM *vm = NULL;
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.c:551]: This should be eliminated entirely (use the global). Also allows trace/warn to be initialized in the declaration.

File: runtime/jnichk/jnicheck.c [hunk 2]
```diff
@@ -548,21 +548,26 @@ jniCheckCallA(const char* function, JNIEnv* env, jobject receiver, UDATA methodT
...
 	va_list va;
 	const U_32 *code;
 	int argNum = 2;
-	UDATA trace = vm->checkJNIData.options & JNICHK_TRACE;
-	UDATA warn = (0 == (vm->checkJNIData.options & JNICHK_NOWARN));
-	J9VMThread * vmThread = (J9VMThread*)env;
+	UDATA trace;
+	UDATA warn;
+	J9VMThread *vmThread = (J9VMThread*)env;
+	J9VMThread *currentVMThread = globalJavaVM->internalVMFunctions->currentVMThread(globalJavaVM);
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.c:558]: This should be NULL checked and a different error output (thread not attached to the VM).

File: runtime/jnichk/jnicheck.c [hunk 3]
```diff
@@ -548,21 +548,26 @@ jniCheckCallA(const char* function, JNIEnv* env, jobject receiver, UDATA methodT
...
 	}
 
-	if (vm->internalVMFunctions->currentVMThread(vm) != vmThread) {
-		jniCheckFatalErrorNLS(env, J9NLS_JNICHK_WRONG_ENV, function);
+	vm = ((J9VMThread*)env)->javaVM;
+	PORT_ACCESS_FROM_JAVAVM(vm);
+	trace = vm->checkJNIData.options & JNICHK_TRACE;
+	warn = (0 == (vm->checkJNIData.options & JNICHK_NOWARN));
+
+	if (vm->reserved1_identifier != (void*)J9VM_IDENTIFIER) {
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.c:569]: This should be replaced by a check that `env->javaVM` matches the global.

File: runtime/jnichk/jnicwrappers.c [hunk 4]
```diff
@@ -258,13 +258,14 @@ static jobjectRefType JNICALL checkGetObjectRefType(JNIEnv *env, jobject obj);
 static jint JNICALL
 checkGetVersion(JNIEnv *env)
 { 	
-	J9JavaVM* j9vm = ((J9VMThread*)env)->javaVM;
+	J9JavaVM* j9vm = NULL;
```
Comment (gacholio) [inline runtime/jnichk/jnicwrappers.c:261]: Again, just use the global in all these cases.

File: runtime/jnichk/jnicheck.h [hunk 5]
```diff
@@ -26,6 +26,7 @@
 #include "jnichk_internal.h"
 
 IDATA J9VMDllMain(J9JavaVM* vm, IDATA stage, void* reserved);
+J9JavaVM* globalJavaVM;
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.h:29]: This needs an `extern` declaration (in fact, it's probably better to just extern it in the C files that use it to avoid conflict with the actual declaration).

File: runtime/jnichk/jnicheck.c (hunk 1 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.c]: updated in [47d194e](https://github.com/eclipse-openj9/openj9/commit/47d194ea2e0f95330bdcc673ddb0949d29409dac)

File: runtime/jnichk/jnicheck.c (hunk 2 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.c:558]: updated in [47d194e](https://github.com/eclipse-openj9/openj9/commit/47d194ea2e0f95330bdcc673ddb0949d29409dac), I added a new error message for it in jnichk.nls

File: runtime/jnichk/jnicwrappers.c (hunk 4 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicwrappers.c]: I updated all the usages of the vm in jnicwrappers.c, but I wasn't sure if you thought all the usages in jnicheck.c (outside of jniCheckArgs.c) should also be updated?

File: runtime/jnichk/jnicheck.h (hunk 5 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.h]: added in [47d194e](https://github.com/eclipse-openj9/openj9/commit/47d194ea2e0f95330bdcc673ddb0949d29409dac)

File: runtime/jnichk/jnicheck.c (hunk 3 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.c]: updated in [47d194e](https://github.com/eclipse-openj9/openj9/commit/47d194ea2e0f95330bdcc673ddb0949d29409dac)

File: runtime/jnichk/jnicheck.c [hunk 6]
```diff
@@ -548,21 +548,25 @@ jniCheckCallA(const char* function, JNIEnv* env, jobject receiver, UDATA methodT
...
+		jniCheckFatalErrorNLS((JNIEnv*)currentVMThread, J9NLS_JNICHK_THREAD_NOT_ATTACHED_TO_VM, function);
+	}
+
+	if (currentVMThread != vmThread) {
+		jniCheckFatalErrorNLS((JNIEnv*)currentVMThread, J9NLS_JNICHK_WRONG_ENV, function);
 	}
 
-	if (vm->internalVMFunctions->currentVMThread(vm) != vmThread) {
-		jniCheckFatalErrorNLS(env, J9NLS_JNICHK_WRONG_ENV, function);
+	if (((J9VMThread*)env)->javaVM != globalJavaVM) {
```
Comment (gacholio) [inline runtime/jnichk/jnicheck.c:568]: Actually, since we've verified that the thread is not NULL and is the current thread, this check is entirely redundant.

File: runtime/jnichk/jnicheck.c [hunk 7]
```diff
@@ -548,21 +548,25 @@ jniCheckCallA(const char* function, JNIEnv* env, jobject receiver, UDATA methodT
...
-	J9VMThread * vmThread = (J9VMThread*)env;
+	UDATA trace = globalJavaVM->checkJNIData.options & JNICHK_TRACE;
+	UDATA warn = (0 == (globalJavaVM->checkJNIData.options & JNICHK_NOWARN));
+	J9VMThread *vmThread = (J9VMThread*)env;
+	J9VMThread *currentVMThread = globalJavaVM->internalVMFunctions->currentVMThread(globalJavaVM);
 
-	if (vm->reserved1_identifier != (void*)J9VM_IDENTIFIER) {
-		jniCheckFatalErrorNLS(env, J9NLS_JNICHK_INVALID_ENV, function);
+	if (NULL == currentVMThread) {
+		jniCheckFatalErrorNLS((JNIEnv*)currentVMThread, J9NLS_JNICHK_THREAD_NOT_ATTACHED_TO_VM, function);
```
Comment (ehrenjulzert) [inline runtime/jnichk/jnicheck.c:561]: Come to think of it, if `currentVMThread` is null then there's no way calling `jniCheckFatalErrorNLS` will ever work properly. Do you think in this case using a lower level print function would make sense?

Comment (gacholio) [reply runtime/jnichk/jnicheck.c:561]: The error function should be using the global VM for anything important (like finding the port library to do the printing), and use the env only as the printed value of the invalid thread.

File: runtime/jnichk/jnicwrappers.c (hunk 4 above)
Comment (gacholio) [reply runtime/jnichk/jnicwrappers.c]: Ideally, all uses should be updated (all uses have to at least be examined to prove the initial verification has been done).

**Comment by gacholio** [comment]
For consistency (and correctness) I think all uses of the env that are not for printing the value need to be replaced with the global VM. This will mean a lot of arguably unnecessary changes, but that's better than missing a corner case.

**Comment by ehrenjulzert** [comment]
> for printing the value 

By "printing the value" do you mean printing the environment itself? And does that include when `jniCheckWarningNLS` and `jniCheckFatalErrorNLS` are called?

**Comment by gacholio** [comment]
Yes, I mean if the error functions print the value of the env. It should not be used for any other purpose (other then verifying its validity).

File: runtime/jnichk/jnicheck.c (hunk 7 above)
Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.c:561]: `currentVMThread` is already the thread that comes from the global VM though, so if it's null then there's no other thread to use.

**Comment by ehrenjulzert** [comment]
When you say "all uses of the env" do you mean the entire `jnicheck.c` file or just in `jniCheckArgs` and the functions it calls?

**Comment by gacholio** [comment]
That was my initial thought, but maybe that's going too far. As long as the incorrect/NULL env is a fatal error, I suppose subsequent changes aren't necessary.

**Comment by ehrenjulzert** [comment]
Ok, in that case what I just pushed should be sufficient (All I did was remove the redundant check you pointed out)

File: runtime/jnichk/jnicheck.c (hunk 7 above)
Comment (gacholio) [reply runtime/jnichk/jnicheck.c:561]: I'm saying `jniCheckFatalErrorNLS` needs to be updated to get the port library from the global VM and not from deferencing a possibly NULL thread. All of the warning/error functions should be modified for consistency.

Comment (gacholio) [reply runtime/jnichk/jnicheck.c:561]: Essentially, every `->javaVM` reference that is not preceded by the arg check needs to either be replaced with the global.

Comment (gacholio) [reply runtime/jnichk/jnicheck.c:561]: That would be fine.

Comment (ehrenjulzert) [reply runtime/jnichk/jnicheck.c]: Ok, I removed the `env` parameter from those functions in [810142c](https://github.com/eclipse-openj9/openj9/commit/810142cf74341d58e1e1cca7aef7f1927afc364d).

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
@ehrenjulzert you can open a PR for [the 0.38 branch](https://github.com/eclipse-openj9/openj9/tree/v0.38.0-release) which we'll merge once we ensure the change isn't causing any problems in the builds.

**Comment by ehrenjulzert** [comment]
Sure, #16814
