### PR TITLE
Correct casting instanceFieldOffset error value to U_64

### LINKED ISSUE #23673: jsr292Test ASSERTION FAILED runtime\jcl\common\java_dyn_methodhandle.c:571: (((J9ROMFieldShape *)(*romField)) != NULL)
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1/1110/console
jsr292Test_jdk8_special_0
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/1108
jsr292Test_JitCount0_jdk8_0
jsr292Test_jdk8_0
```
23:08:30  testIdentity.3
23:08:30  03:08:30.810 0x2264e600   j9jcl.191    *   ** ASSERTION FAILED ** at F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_Nightly\openj9\runtime\jcl\common\java_dyn_methodhandle.c:571: (((J9ROMFieldShape *)(*romField)) != NULL)
```

Changes
https://github.com/eclipse-openj9/openj9/compare/bc935e44dc7...4430f6a3ffd
https://github.com/eclipse-openj9/openj9-omr/compare/ac41e565cd4...01e2beb1a74

Perhaps https://github.com/eclipse-openj9/openj9/pull/23301

### PR DESCRIPTION
**Pull request by theresa-m**
Fixes: https://github.com/eclipse-openj9/openj9/issues/23673

extended tests with change: http://vmfarm.rtp.raleigh.ibm.com/build_info.php?build_id=115885
The failures look unrelated to my change.

### CODE REVIEW

File: runtime/jcl/common/java_dyn_methodhandle.c [hunk 1]
```diff
@@ -556,7 +556,7 @@ lookupField(JNIEnv *env, jboolean isStatic, J9Class *j9LookupClass, jstring name
 		field = (UDATA) field - (UDATA) (*definingClass)->ramStatics;
 		field |= J9_SUN_STATIC_FIELD_OFFSET_TAG;
 	} else {
-		field = (UDATA) vmFuncs->instanceFieldOffset(vmThread, j9LookupClass, J9UTF8_DATA(nameUTF8), J9UTF8_LENGTH(nameUTF8), J9UTF8_DATA(sigUTF), J9UTF8_LENGTH(sigUTF), definingClass, romField, 0);
+		field = vmFuncs->instanceFieldOffset(vmThread, j9LookupClass, J9UTF8_DATA(nameUTF8), J9UTF8_LENGTH(nameUTF8), J9UTF8_DATA(sigUTF), J9UTF8_LENGTH(sigUTF), definingClass, romField, 0);
```
Comment (hangshao0) [inline runtime/jcl/common/java_dyn_methodhandle.c:559]: Could you double check whether the following check` if (-1 == field)` capture all the error cases ? i.e. Could `instanceFieldOffset()` return other negative values or 0 ?

Comment (theresa-m) [reply runtime/jcl/common/java_dyn_methodhandle.c:559]: I checked and instanceFieldOffset will return either -1 or a valid offset.

**Comment by hangshao0** [comment]
jenkins test sanity.functional,extended.functional alinux64 jdk11

**Comment by hangshao0** [comment]
jenkins test sanity.functional,extended.functional win32 jdk8

**Review by hangshao0 — APPROVED** [review]
