### PR TITLE
Replace hard-code JAVA_MODULE_VERSION with JAVA_SPEC_VERSION_STRING

### LINKED ISSUE #13048: Weird stacktrace when using an invalid Security Manager
Java -version output
--------------------
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

Summary of problem
------------------
While playing around with the security manager, I've found out this weird stack trace: It includes the module name and version using slashes and the version is 9, even though I'm using JDK 16.

Diagnostic files
----------------
```
/jvms/jdk-16-openj9/bin/java -Djava.security.manager=x -version
Exception in thread "(unnamed thread)" java/lang/Error: JVM can't set custom SecurityManager due to java.lang.ClassNotFoundException: x
        at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:240)
        at java/lang/Thread.initialize (java.base@9/Thread.java:444)
        at java/lang/Thread.<init> (java.base@9/Thread.java:161)
```
This is the output of Hotspot:
```
/jvms/jdk-16/bin/java -Djava.security.manager=x -version
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager
        at java.lang.System.initPhase3(java.base@16.0.1/System.java:2120)
Caused by: java.lang.ClassNotFoundException: x
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@16.0.1/BuiltinClassLoader.java:636)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@16.0.1/ClassLoaders.java:182)
        at java.lang.ClassLoader.loadClass(java.base@16.0.1/ClassLoader.java:519)
        at java.lang.Class.forName0(java.base@16.0.1/Native Method)
        at java.lang.Class.forName(java.base@16.0.1/Class.java:466)
        at java.lang.System.initPhase3(java.base@16.0.1/System.java:2105)
```

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Consolidate macro `J9_STR_`/`J9_STR` into `j9comp.h`;
Format refactoring within the methods affected.

close #13048 

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

File: runtime/oti/jvminit.h [hunk 1]
```diff
@@ -616,7 +616,6 @@ enum INIT_STAGE {
 #define SYSPROP_JDK_MODULE_PATCH "jdk.module.patch."
 #define SYSPROP_JDK_MODULE_ILLEGALACCESS "jdk.module.illegalAccess"
 #define JAVA_BASE_MODULE "java.base"
-#define JAVA_MODULE_VERSION "9"
```
Comment (DanHeidinga) [inline runtime/oti/jvminit.h:619]: Would it be a more straightforward change to use the preprocessor to stringify the JAVA_SPEC_VERSION here?

https://gcc.gnu.org/onlinedocs/gcc-4.8.5/cpp/Stringification.html

File: runtime/vm/exceptiondescribe.c [hunk 2]
```diff
@@ -165,46 +162,35 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
-						J9NLS_DO_NOT_PRINT_MESSAGE_TAG,
-						J9NLS_VM_STACK_TRACE_WITH_MODULE_VERSION_LINE,
-						"\tat %.*s.%.*s (%s@%s/%.*s:%u)\n");
-				} else {
-					format = j9nls_lookup_message(
-						J9NLS_DO_NOT_PRINT_MESSAGE_TAG,
-						J9NLS_VM_STACK_TRACE_WITH_MODULE_VERSION,
-						"\tat %.*s.%.*s (%s@%s/%.*s)\n");
-				}
+			if (lineNumber) {
```
Comment (gacholio) [inline runtime/vm/exceptiondescribe.c:165]: Since you're fixing everything else, please make this `0 != lineNumber`

File: runtime/jcl/common/jclexception.c [hunk 3]
```diff
@@ -146,24 +144,28 @@ getStackTraceIterator(J9VMThread * vmThread, void * voidUserData, UDATA bytecode
...
 				J9Module *module = NULL;
-				if (classLoader != NULL) {
+				if (NULL != classLoader) {
 					j9object_t classLoaderName = J9VMJAVALANGCLASSLOADER_CLASSLOADERNAME(vmThread, classLoader->classLoaderObject);
 					J9VMJAVALANGSTACKTRACEELEMENT_SET_CLASSLOADERNAME(vmThread, element, classLoaderName);
 				}
 				if (J9_ARE_NO_BITS_SET(vm->runtimeFlags, J9_RUNTIME_JAVA_BASE_MODULE_CREATED)) {
+					PORT_ACCESS_FROM_JAVAVM(vm);
+					char javaModuleVersion[4] = {0};
+					UDATA verLength = j9str_printf(PORTLIB, javaModuleVersion, 4, "%u", JAVA_SPEC_VERSION);
```
Comment (pshipton) [inline runtime/jcl/common/jclexception.c:156]: This can be done via a macro, see https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/vmprops.c#L578-L580

File: runtime/vm/exceptiondescribe.c [hunk 4]
```diff
@@ -165,46 +162,35 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
+				format = j9nls_lookup_message(
+					J9NLS_DO_NOT_PRINT_MESSAGE_TAG,
+					J9NLS_VM_STACK_TRACE_WITH_MODULE_VERSION_LINE,
+					(NULL == moduleVersionUTF) ? "\tat %.*s.%.*s (%s@%u/%.*s:%u)\n" : "\tat %.*s.%.*s (%s@%s/%.*s:%u)\n");
```
Comment (pshipton) [inline runtime/vm/exceptiondescribe.c:169]: This can be avoided/simplified by using a macro, see This can be done via a macro, see https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/vmprops.c#L578-L580

File: runtime/jcl/common/jclexception.c (hunk 3 above)
Comment (gacholio) [reply runtime/jcl/common/jclexception.c:156]: Perhaps we should move `J9_STR` to `j9.h`

File: runtime/oti/jvminit.h (hunk 1 above)
Comment (JasonFengJ9) [reply runtime/oti/jvminit.h:619]: Modified to use `J9_STR(JAVA_SPEC_VERSION)`.

File: runtime/vm/exceptiondescribe.c (hunk 2 above)
Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c]: Updated.

File: runtime/jcl/common/jclexception.c (hunk 3 above)
Comment (JasonFengJ9) [reply runtime/jcl/common/jclexception.c]: Moved to `j9comp.h`.

File: runtime/vm/exceptiondescribe.c (hunk 4 above)
Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c]: Yeah, use `J9_STR(JAVA_SPEC_VERSION)`.

**Comment by JasonFengJ9** [comment]
Updated the PR, please have another look.

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity,extended win jdk11

**Comment by gacholio** [comment]
jenkins test sanity,extended win jdk8

File: runtime/vm/exceptiondescribe.c [hunk 5]
```diff
@@ -154,62 +151,45 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
-					sourceFileNameLen, sourceFileName,
-					lineNumber); /* line number will be ignored in if it's not used in the format string */
+				format = j9nls_lookup_message(
+					J9NLS_DO_NOT_PRINT_MESSAGE_TAG,
+					J9NLS_VM_STACK_TRACE_WITH_MODULE_VERSION,
+					"\tat %.*s.%.*s (%s@%s/%.*s)\n");
+			}
+			if (NULL == moduleVersionUTF) {
+				moduleVersionUTF = J9_STR(JAVA_SPEC_VERSION);
+			}
```
Comment (DanHeidinga) [inline runtime/vm/exceptiondescribe.c:178]: Does this code handle unnamed modules correctly?  I'm finding the diff a little hard to track

Comment (gacholio) [reply runtime/vm/exceptiondescribe.c:178]: I'm hoping that testing would catch this if it's wrong.

Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c:178]: The code in question `moduleVersionUTF = J9_STR(JAVA_SPEC_VERSION)` only affects early booting stage when `java.base` module hasn't been created yet.
Afterwards, the module version is derived from `module->version`.

Comment (DanHeidinga) [reply runtime/vm/exceptiondescribe.c:178]: Which says the window for getting it wrong is small (until java.base is created) but will still affect agents that boot early.  I doubt we have tests for this early condition

Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c:178]: `moduleVersionUTF` related code is under `if (NULL != moduleNameUTF)` which assumes a named module.

Comment (DanHeidinga) [reply runtime/vm/exceptiondescribe.c:178]: https://github.com/eclipse-openj9/openj9/blob/dcf40227cde9c4e744b0c9302d3d605b74c4b65e/runtime/vm/exceptiondescribe.c#L127-L128

If we're java11+, `moduleNameUTF` will never be null.

https://github.com/eclipse-openj9/openj9/blob/dcf40227cde9c4e744b0c9302d3d605b74c4b65e/runtime/vm/exceptiondescribe.c#L135

And assuming `findModuleForPackage` returns null for the unnamed module, then we'll treat all class path entries as being in `JAVA_BASE_MODULE` as we'll never change `moduleNameUTF` to be null

Comment (DanHeidinga) [reply runtime/vm/exceptiondescribe.c:178]: https://github.com/eclipse-openj9/openj9/blob/dcf40227cde9c4e744b0c9302d3d605b74c4b65e/runtime/vm/exceptiondescribe.c#L164-L178

And all of this code will see `moduleNameUTF == JAVA_BASE_MODULE` and print as though it's in a module

Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c:178]: Okay, I see that's an existing problem, will set `moduleNameUTF` to `NULL` when the `findModuleForPackage ` returns `NULL` which means an unnamed module.
I think before `java.base` is created, it can assume bootstrap code instead of unnamed module code.

File: runtime/jcl/common/jclexception.c [hunk 6]
```diff
@@ -146,24 +144,26 @@ getStackTraceIterator(J9VMThread * vmThread, void * voidUserData, UDATA bytecode
...
+			if (JAVA_SPEC_VERSION >= 11) {
+				if (NULL != classLoader) {
 					j9object_t classLoaderName = J9VMJAVALANGCLASSLOADER_CLASSLOADERNAME(vmThread, classLoader->classLoaderObject);
 					J9VMJAVALANGSTACKTRACEELEMENT_SET_CLASSLOADERNAME(vmThread, element, classLoaderName);
 				}
 				if (J9_ARE_NO_BITS_SET(vm->runtimeFlags, J9_RUNTIME_JAVA_BASE_MODULE_CREATED)) {
-					string = mmfns->j9gc_createJavaLangString(vmThread, (U_8 *)JAVA_BASE_MODULE, LITERAL_STRLEN(JAVA_BASE_MODULE), J9_STR_XLAT);
-					if (string == NULL) {
+					const char* javaModuleVersion = J9_STR(JAVA_SPEC_VERSION);
+					UDATA verLength = LITERAL_STRLEN(javaModuleVersion);
```
Comment (pshipton) [inline runtime/jcl/common/jclexception.c:154]: LITERAL_STRLEN only works on literals, not variables. It uses sizeof().

Comment (gacholio) [reply runtime/jcl/common/jclexception.c:154]: siezeof is also wrong if used on the variable. LITERAL_STRLEN on JAVA_SPEC_VERSION is correct.

Comment (gacholio) [reply runtime/jcl/common/jclexception.c:154]: A better alternative would be to define a macro for the stringized version, and use that instead of making local variables at all. Then the literal code will work, and is the most performant.

File: runtime/vm/exceptiondescribe.c (hunk 5 above)
Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c:184]: Fixed the case for unnamed module.

File: runtime/jcl/common/jclexception.c (hunk 6 above)
Comment (JasonFengJ9) [reply runtime/jcl/common/jclexception.c]: Added a macro `J9_STR_LITERAL_LEN(x)` as `LITERAL_STRLEN(J9_STR(x))`.

Comment (gacholio) [reply runtime/jcl/common/jclexception.c]: Not a fan of that approach - extremely confusing name. What I suggest is defining `JAVA_SPEC_VERSION_STRING` as `J9_STR(JAVA_SPEC_VERSION)`. I would put this in the same place as `JAVA_SPEC_VERSION` is defined rather than putting it here.

Comment (JasonFengJ9) [reply runtime/jcl/common/jclexception.c]: It turns out that `JAVA_SPEC_VERSION_STRING` already is defined at https://github.com/eclipse-openj9/openj9/blob/09971ec709ccfd48bea8b129fcfb8d0dc03f20c5/runtime/include/j9cfg.h.in#L45-L46
Updated PR accordingly.

File: runtime/vm/exceptiondescribe.c [hunk 7]
```diff
@@ -138,78 +134,68 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
-					moduleNameUTF,
-					sourceFileNameLen, sourceFileName,
-					lineNumber); /* line number will be ignored in if it's not used in the format string */
+				format = j9nls_lookup_message(
+					J9NLS_DO_NOT_PRINT_MESSAGE_TAG,
+					J9NLS_VM_STACK_TRACE_WITH_MODULE_VERSION,
+					"\tat %.*s.%.*s (%s@%s/%.*s)\n");
+			}
+			if (NULL == moduleVersionUTF) {
+				moduleVersionUTF = JAVA_SPEC_VERSION_STRING;
```
Comment (DanHeidinga) [inline runtime/vm/exceptiondescribe.c:183]: There are two places that set `moduleNameUTF = JAVA_BASE_MODULE;` - can setting `moduleVersionUTF` be done in the same places and the null check be removed?

Comment (JasonFengJ9) [reply runtime/vm/exceptiondescribe.c]: Agreed. Also derive `java.base` module version from `module->version`, if the result is `null`, fall back to `JAVA_SPEC_VERSION_STRING`.

**Review by DanHeidinga — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk11

**Comment by pshipton** [comment]
jenkins compile win jdk8,jdk11
