### PR TITLE
Fix romclass comparison and J9Class lookup given a romclass

### LINKED ISSUE #19781: AOT  jsr292Test test_bindTo_interfaceMethodImplementation_package - Successfully invoked package private implementation of an interface method, StackWalkerTest testClassLoaderName Wrong classloader name expected
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_extended.functional_s390x_linux_aot_Personal/232/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_aot_Personal_testList_1/270/
 jsr292Test_1
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_aot_Personal_testList_0/270
jsr292Test_0
```
=== AOT ITERATION 2 ===

07:27:01  FAILED: test_bindTo_interfaceMethodImplementation_package
07:27:01  java.lang.AssertionError: Successfully invoked package private implementation of an interface method.
07:27:01  	at org.testng.Assert.fail(Assert.java:96)
07:27:01  	at com.ibm.j9.jsr292.InterfaceHandleTest.test_bindTo_interfaceMethodImplementation_package(InterfaceHandleTest.java:102)
```

This is related so I didn't open another issue.

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_s390x_linux_aot_Personal_testList_0/270
StackWalkerTest_0
```
09:06:16  FAILED: testClassLoaderName
09:06:16  java.lang.AssertionError: Wrong classloader name expected [TestMyloaderInstance] but found [null]
09:06:16  	at org.testng.Assert.fail(Assert.java:96)
09:06:16  	at org.testng.Assert.failNotEquals(Assert.java:776)
09:06:16  	at org.testng.Assert.assertEqualsImpl(Assert.java:132)
09:06:16  	at org.testng.Assert.assertEquals(Assert.java:118)
09:06:16  	at org.testng.Assert.assertEquals(Assert.java:453)
09:06:16  	at org.openj9.test.stackWalker.MyRunnable.run(MyRunnable.java:45)
09:06:16  	at org.openj9.test.stackWalker.StackWalkerTest.testClassLoaderName(StackWalkerTest.java:243)
```

Changes from last successful build https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-AOT/291/
https://github.com/eclipse-openj9/openj9/compare/bc7affe3fed31...581a248f98c
https://github.com/eclipse-openj9/openj9-omr/compare/3a218f25ea0...770936378ec
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/839808e0...720cbbf6053

### PR DESCRIPTION
**Pull request by hangshao0**
1. The romclass comparsion should include the ROM_CLASS_MODIFIERS.
2. For a ROMClass from SCC, its rom memory segment always belongs to the bootstrap class loader. But the class might not be actually loaded by the bootstrap loader. Search all live class loaders to find its defining class loader and the corresponding J9Class.

Fixes #19781

### CODE REVIEW

**Comment by pshipton** [comment]
What testing has already been run?

File: runtime/vm/exceptiondescribe.c [hunk 1]
```diff
@@ -219,6 +220,53 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
+	J9JavaVM *vm = vmThread->javaVM;
+	J9Class* ret = NULL;
+	if (j9shr_Query_IsAddressInCache(vm, romClass, romClass->romSize)) {
+		J9ClassLoaderWalkState walkState;
+		J9ClassLoader* classLoader = NULL;
+		BOOLEAN fastMode = J9_ARE_ALL_BITS_SET(vm->extendedRuntimeFlags, J9_EXTENDED_RUNTIME_FAST_CLASS_HASH_TABLE);
+		if (!fastMode) {
+			omrthread_monitor_enter(vm->classTableMutex);
+		}
+		classLoader = vm->internalVMFunctions->allClassLoadersStartDo(&walkState, vm, 0);
```
Comment (pshipton) [inline runtime/vm/exceptiondescribe.c:245]: Will the bootstrap classloader always be iterated first? Otherwise there might be a performance issue.

**Comment by hangshao0** [comment]
> What testing has already been run?

I have run `jsr292Test_0` and `StackWalkerTest_0` with SCC and AOT enabled.

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.openjdk amac jdk11

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.openjdk,sanity.system,extended.system amac jdk11

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.openjdk_aarch64_mac_Personal_testList_0/23/
failed java/lang/StackTraceElement/ModuleFrames.java

File: runtime/vm/exceptiondescribe.c (hunk 1 above)
Comment (hangshao0) [reply runtime/vm/exceptiondescribe.c:245]: > Will the bootstrap classloader always be iterated first? 

It depends. Bootstrap class loader is the first class loader in the first puddle. If more class loaders have been allocated to the extend that triggers new puddles to be added, the new puddle is added as the new head of the J9Pool. In this case bootstrap class loader won't be the first to be iterated.

Comment (pshipton) [reply runtime/vm/exceptiondescribe.c:245]: I suggest checking the bootstrap loader first before iterating through them all, in the hopes it minimizes the perf impact.

Comment (hangshao0) [reply runtime/vm/exceptiondescribe.c:245]: > I suggest checking the bootstrap loader first before iterating through them all,

I will push the change once the PR builds finish (in case there are more failures).

**Comment by hangshao0** [comment]
Other PR builds passed:

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_aarch64_mac_Personal/33/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.system_aarch64_mac_Personal/8/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_aarch64_mac_Personal/190/
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.system_aarch64_mac_Personal/12/

File: runtime/vm/exceptiondescribe.c (hunk 1 above)
Comment (hangshao0) [reply runtime/vm/exceptiondescribe.c:277]: The same as the existing code before this change, I've added code to probe bootstrap class loader as well as app class loader, which further minimizes the chance of iterating all the class loaders.

**Comment by hangshao0** [comment]
Internal JDK11 sanity.openjdk personal [build](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/23144/) on aarch64_mac passed with the current change. 

This can be reviewed again.

File: runtime/vm/exceptiondescribe.c [hunk 2]
```diff
@@ -219,6 +220,86 @@ printStackTraceEntry(J9VMThread * vmThread, void * voidUserData, UDATA bytecodeO
...
+			&& (romClass == ramClass->romClass)
+		) {
+			ret = ramClass;
+			if (!fastMode) {
+				omrthread_monitor_exit(vm->classTableMutex);
+			}
+			goto done;
+		}
+
+		ramClass = hashClassTableAt(vm->applicationClassLoader, J9UTF8_DATA(utfClassName), J9UTF8_LENGTH(utfClassName));
```
[the remark this answers is not in the document]
Comment (hangshao0) [reply runtime/vm/exceptiondescribe.c:277]: Added.

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.openjdk,sanity.system,extended.system amac jdk11

**Review by pshipton — APPROVED** [review]
