### PR TITLE
Move KeyHashTableClassEntry typedef to a dedicated header

### LINKED ISSUE #23766: SE80_GIT testDDRExt_General_0 DDRInteractiveCommandException: Unrecognized type 'KeyHashTableClassEntry'
Failure link
------------

From [an internal build](http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=125415271):
```
java version "1.8.0_491"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxl6480sr9-20260327_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20260416_115986 (JIT enabled, AOT enabled)
OpenJ9   - a7234b698ce
OMR      - 4a4463e19
IBM      - 764a44b)
JCL - 20260318_01 based on Oracle jdk8u491-b09
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
Running test testDDRExt_General_0 ...
===============================================
testDDRExt_General_0 Start Time: Thu Apr 16 22:21:55 2026 Epoch Time (ms): 1776392515790
variation: NoOptions
JVM_OPTIONS:  

     [java] [AutoRun] [INFO] Starting testWalkJ9Pool(j9vm.test.ddrext.junit.TestDDRExtensionGeneral)
     [java] 1050624021627263506543659216372801047104857632768331201310720-120484549480262144000000130736256214528130736256214568130736256214608130736256214648300001307363594053120130736254365136524288096324525632451110013107213073633905740802048151316323200100112345429261516384409611111111110111111110083650000192512-108160010000000105-11748000276801307362562146881307362562147280-13000128011101024102560800523275600058182430464669066553637610409681624[DDRExtTesterBase] [INFO] Validation started for : '!walkj9pool 0x000076E768127520'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!walkj9pool 0x000076E768127520'
     [java] 32125409681620[DDRExtTesterBase] [INFO] Validation started for : '!walkj9pool 0x000076E7681263E0'
     [java] [DDRExtTesterBase] [INFO] Validation passed for : '!walkj9pool 0x000076E7681263E0'
     [java] 112354096816214748365018[DDRExtTesterBase] [ERROR] '!walkj9hashtable 0x000076E7681375E0 KeyHashTableClassEntry' output contains common failure key : DDRInteractiveCommandException
     [java] [DDRExtTesterBase] [ERROR] '!walkj9hashtable 0x000076E7681375E0 KeyHashTableClassEntry' output :
     [java] Problem running command:
     [java] com.ibm.j9ddr.tools.ddrinteractive.DDRInteractiveCommandException: Unrecognized type 'KeyHashTableClassEntry'
     [java] 	at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.WalkJ9HashTableCommand.run(WalkJ9HashTableCommand.java:111)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:220)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:196)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:176)
     [java] 	at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:361)
     [java] 	at j9vm.test.ddrext.DDRExtTesterBase.exec(DDRExtTesterBase.java:97)
     [java] 	at j9vm.test.ddrext.junit.TestDDRExtensionGeneral.testWalkJ9HashTableforClassHashTable(TestDDRExtensionGeneral.java:674)
     [java] 	at j9vm.test.ddrext.junit.TestDDRExtensionGeneral.testWalkJ9HashTablesForCLHashTables(TestDDRExtensionGeneral.java:647)
     [java] 	at j9vm.test.ddrext.junit.TestDDRExtensionGeneral.testWalkJ9HashTable(TestDDRExtensionGeneral.java:619)
```

It seems related to 
* https://github.com/eclipse-openj9/openj9/pull/23526

FYI @tomal-majumder @keithc-ca

### PR DESCRIPTION
**Pull request by tomal-majumder**
The type was defined only in KeyHashTable.c, making it invisible to the legacy DDR toolchain. This caused !walkj9hashtable called with type KeyHashTableClassEntry to fail with:

  DDRInteractiveCommandException: Unrecognized type 'KeyHashTableClassEntry'

Move the typedef to keyhhashtableclassentry.h and add it to vmddrstructs.properties so the type is visible to the legacy DDR toolchain.

Fixes: #23766

### CODE REVIEW

File: runtime/vm/KeyHashTable.h [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ * [1] https://www.gnu.org/software/classpath/license.html
+ * [2] https://openjdk.org/legal/assembly-exception.html
+ *
+ * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
+ *******************************************************************************/
+
+#ifndef KEYHHASHTABLECLASSENTRY_H_
+#define KEYHHASHTABLECLASSENTRY_H_
+
```
Comment (keithc-ca) [inline runtime/vm/KeyHashTable.h:27]: This must include header files that define `UDATA` and `J9PackageIDTableEntry`.
After that, there should be forward declarations for `J9Class` and `J9UTF8` if necessary.

File: runtime/vm/KeyHashTable.c [hunk 2]
```diff
@@ -27,6 +27,7 @@
 #include "j9port_generated.h"
 #endif /* defined(J9VM_OPT_SNAPSHOTS) */
 #include "j9protos.h"
+#include "keyhhashtableclassentry.h"
```
Comment (keithc-ca) [inline runtime/vm/KeyHashTable.c]: Perhaps the new header file should be named `KeyHashTable.h` to be more general in case other declarations need to move there.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: runtime/vm/KeyHashTable.h (hunk 1 above)
Comment (tomal-majumder) [reply runtime/vm/KeyHashTable.h:27]: Will including `j9nonbuilder.h` be sufficient here as it provides `UDATA` (via j9consts.h → j9comp.h → omrcomp.h) and defines `J9PackageIDTableEntry`, `J9Class`, and `J9UTF8` directly?

File: runtime/vm/KeyHashTable.c (hunk 2 above)
Comment (keithc-ca) [reply runtime/vm/KeyHashTable.c]: I expect it's sufficient, but excessive. A header file should include only what is necessary, nothing more, to allow it to be included alone.

Comment (keithc-ca) [reply runtime/vm/KeyHashTable.c]: I take that back: `J9PackageIDTableEntry` is declared in `j9nonbuilder.h` so that's the right file to include. (It also ensures that `UDATA` is declared.)

Comment (tomal-majumder) [reply runtime/vm/KeyHashTable.c]: Yeah, and I think forward declarations for J9Class and J9UTF8 are also not required; as `j9nonbuilder.h` defines them directly.

**Comment by keithc-ca** [comment]
Looks good, pending internal testing.

**Comment by tomal-majumder** [comment]
Internal build link passed `testDDRExt_General_0`: 
http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=125454593

```java version "1.8.0_491"
Java(TM) SE Runtime Environment (build 8.0.9.0 - pxa6480sr9-20260327_01(SR9))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20260417_116043 
(JIT enabled, AOT enabled)
OpenJ9   - d35f5b4
OMR      - 4a4463e
IBM      - 764a44b)
JCL - 20260318_01 based on Oracle jdk8u491-b09
```

**Comment by keithc-ca** [comment]
Jenkins test extended.functional amac jdk21

**Review by keithc-ca — APPROVED** [review]
