### PR TITLE
Split loadArrayElement into two APIs

### LINKED ISSUE #13540: Valhalla build crash with --enable-inline-types
The crash happens during JVM build with `--enable-inline-types`. The crash is reproducible with `limit={jdk/internal/module/ModulePath.readExplodedModule(Ljava/nio/file/Path;)Ljava/lang/module/ModuleReference;,` although the crash is not limited to this method. It's also reproducible by excluding this method. 

It looks that the last known good Build_JDKnext_x86-64_linux_valhalla_Nightly is 472. It was built with jdk17 in Aug  
```
[2021-08-24T01:54:22.522Z] + build/linux-x86_64-server-release/images/jdk/bin/java -Xjit -version
[2021-08-24T01:54:22.522Z] openjdk version "17-internal" 2021-09-14
[2021-08-24T01:54:22.522Z] OpenJDK Runtime Environment (build 17-internal+0-adhoc.jenkins.BuildJDKnextx86-64linuxvalhallaNightly)
[2021-08-24T01:54:22.522Z] Eclipse OpenJ9 VM (build master-f29e6446a54, JRE 17 Linux amd64-64-Bit Compressed References 20210823_472 (JIT enabled, AOT enabled)
[2021-08-24T01:54:22.522Z] OpenJ9   - f29e6446a54
[2021-08-24T01:54:22.522Z] OMR      - 1d8fb435675
[2021-08-24T01:54:22.522Z] JCL      - 067436e5a5a based on jdk-17+18)
```
I tried to build OpenJ9(f29e6446a54) and OMR(1d8fb435675) with jdk tag jdk-18+0 (a14b0cfcfc7). It also crashed with `--enable-inline-types`. 

So far it could crash in two places: inliner(`0x000501ff`) `findAndUpdateCallSiteInGraph` [1] or codegen(vmState=`0x0005ff04`) `TR_J9VMBase::reserveTrampolineIfNecessary` [2]. They try to cast either `TR::Symbol `or `TR::MethodSymbol ` to `TR::ResolvedMethodSymbol`, but in both cases, `Symbol::isResolvedMethod()` is false. 

Attach the log file from the crash in `TR_J9VMBase::reserveTrampolineIfNecessary`. 
[log.16977.70551.20210920.204231.16977.zip](https://github.com/eclipse-openj9/openj9/files/7198755/log.16977.70551.20210920.204231.16977.zip)

```
  ============================================================
  1e: JBinvokedynamic
   /--- (Stack after load from callsite table) ------------------------
   @3 n51n     (  1)  acall  unknown[#368  helper Method] (obj3) [flags 0x400 0x0 ]                        [0x7f7bade057c0] bci=[-1,30,689] rc=1 vc=0 vn=- li=- udi=- nc=2
      n48n     (  1)    iconst 1                                                                           [0x7f7bade056d0] bci=[-1,30,689] rc=1 vc=0 vn=- li=- udi=- nc=0
      n47n     (  2)    aload  <callSite entry @22     0x12fe78>[#367  Static] (obj2) [flags 0x307 0x8 ]   [0x7f7bade05680] bci=[-1,30,689] rc=2 vc=0 vn=- li=- udi=- nc=0
...
...
============================================================
; Live regs: GPR=4 FPR=0 VRF=0 {&GPR_0192, &GPR_0140, &GPR_0049, &GPR_0048}
------------------------------
 n52n     (  0)  treetop                                                                              [0x7f7bade80000] bci=[-1,30,689] rc=0 vc=999 vn=- li=4 udi=- nc=1
 n51n     (  4)    acall  unknown[#368  helper Method] (obj3) [flags 0x400 0x0 ] (X>=0 sharedMemory )  [0x7f7bade057c0] bci=[-1,30,689] rc=4 vc=999 vn=- li=4 udi=- nc=2 flg=0x100
 n48n     (  1)      iconst 1 (X!=0 X>=0 )                                                            [0x7f7bade056d0] bci=[-1,30,689] rc=1 vc=999 vn=- li=4 udi=- nc=0 flg=0x104
 n47n     (  1)      aload  <callSite entry @22     0x12fe78>[#367  Static] (obj2) [flags 0x307 0x8 ]  [0x7f7bade05680] bci=[-1,30,689] rc=1 vc=999 vn=- li=4 udi=- nc=0
------------------------------
DEBUG CRASH: symRef 00007F7BADE72530 #368 isMethod 1 isResolvedMethod 0 resolvedMethod 00007F7BADE72430
```

[1]
```
#12 <signal handler called>
#13 0x00007f3adf806ad8 in TR_InlinerBase::findAndUpdateCallSiteInGraph (this=this@entry=0x7f3adc2e8870, 
    callStack=callStack@entry=0x7f3adc2e72e0, bcInfo=..., tt=tt@entry=0x7f3a90853760, parent=0x7f3a907b8fc0, 
    callNode=0x7f3a907b8f70, calltarget=0x7f3a90545f30)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/Inliner.cpp:4440
#14 0x00007f3adf807aec in TR_InlinerBase::inlineFromGraph (this=this@entry=0x7f3adc2e8870, 
    prevCallStack=prevCallStack@entry=0x7f3adc2e7700, calltarget=calltarget@entry=0x7f3a90545f30, 
    innerPrexInfo=innerPrexInfo@entry=0x7f3a904b6bf0)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/Inliner.cpp:4604
#15 0x00007f3adf80ca5c in TR_InlinerBase::inlineCallTarget2 (this=this@entry=0x7f3adc2e8870, 
    callStack=callStack@entry=0x7f3adc2e7700, calltarget=calltarget@entry=0x7f3a90545f30, 
    cursorTreeTop=cursorTreeTop@entry=0x7f3adc2e76d0, inlinefromgraph=inlinefromgraph@entry=true)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/Inliner.cpp:4844
#16 0x00007f3adf56c8f4 in TR_InlinerBase::inlineCallTarget (this=this@entry=0x7f3adc2e8870, 
    callStack=callStack@entry=0x7f3adc2e7700, calltarget=calltarget@entry=0x7f3a90545f30, 
    inlinefromgraph=inlinefromgraph@entry=true, argInfo=<optimized out>, argInfo@entry=0x0, 
    cursorTreeTop=cursorTreeTop@entry=0x7f3adc2e76d0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/openj9/runtime/compiler/optimizer/J9Inliner.cpp:498
#17 0x00007f3adf54da8f in TR_MultipleCallTargetInliner::inlineCallTargets (this=0x7f3adc2e8870, 
    callerSymbol=<optimized out>, prevCallStack=<optimized out>, innerPrexInfo=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/openj9/runtime/compiler/optimizer/InlinerTempForJ9.cpp:3503
#18 0x00007f3adf80d77e in TR_InlinerBase::performInlining (this=this@entry=0x7f3adc2e8870, 
    callerSymbol=callerSymbol@entry=0x7f3a90405850)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/Inliner.cpp:453
#19 0x00007f3adf5449b6 in TR_Inliner::perform (this=0x7f3a90410220)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/openj9/runtime/compiler/optimizer/InlinerTempForJ9.cpp:2575
#20 0x00007f3adf91b2b7 in OMR::Optimizer::performOptimization (this=this@entry=0x7f3a904a0880, 
    optimization=optimization@entry=0x7f3adfbc2560 <cheapWarmStrategyOpts+32>, firstOptIndex=firstOptIndex@entry=0, 
    lastOptIndex=lastOptIndex@entry=2147483647, doTiming=doTiming@entry=0)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/OMROptimizer.cpp:2053
#21 0x00007f3adf91cb0b in OMR::Optimizer::optimize (this=0x7f3a904a0880)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/optimizer/OMROptimizer.cpp:1128
#22 0x00007f3adf719ae7 in OMR::Compilation::performOptimizations (this=this@entry=0x7f3a90400000)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/compile/OMRCompilation.cpp:1270
#23 0x00007f3adf71f0e5 in OMR::Compilation::compile (this=this@entry=0x7f3a90400000)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/omr/compiler/compile/OMRCompilation.cpp:1066
#24 0x00007f3adf35306b in TR::CompilationInfoPerThreadBase::compile (this=this@entry=0x7f3adc509930, 
    vmThread=vmThread@entry=0x22500, compiler=<optimized out>, compilee=compilee@entry=0x7f3adc2eda08, vm=..., 
    optimizationPlan=<optimized out>, scratchSegmentProvider=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk17-saved-2/openj9/runtime/compiler/control/CompilationThread.cpp:9253
...
```
[2]
```
#12 <signal handler called>
#13 0x0000000000000000 in ?? ()
#14 0x00007f1a355227da in TR_J9VMBase::reserveTrampolineIfNecessary (this=0x7f1a1800a0f0, comp=0x7f19e2000000, 
    symRef=0x7f19e2072530, inBinaryEncoding=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/env/VMJ9.cpp:5559
#15 0x00007f1a357a7ea0 in J9::X86::PrivateLinkage::buildDirectCall (this=this@entry=0x7f19e2467d60, 
    methodSymRef=0x7f19e2072530, site=...)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/x/codegen/X86PrivateLinkage.cpp:1905
#16 0x00007f1a357abb2f in J9::X86::PrivateLinkage::buildDirectDispatch (this=0x7f19e2467d60, callNode=0x7f19e20057c0, 
    spillFPRegs=<optimized out>)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/x/codegen/X86PrivateLinkage.cpp:1111
#17 0x00007f1a35bc609b in OMR::X86::TreeEvaluator::performCall (node=node@entry=0x7f19e20057c0, 
    isIndirect=isIndirect@entry=false, spillFPRegs=spillFPRegs@entry=true, cg=cg@entry=0x7f19e2005cd0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/x/codegen/OMRTreeEvaluator.cpp:2831
#18 0x00007f1a35bc6292 in OMR::X86::TreeEvaluator::directCallEvaluator (node=0x7f19e20057c0, cg=0x7f19e2005cd0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/x/codegen/OMRTreeEvaluator.cpp:3093
#19 0x00007f1a357cdfcf in OMR::CodeGenerator::evaluate (this=this@entry=0x7f19e2005cd0, node=node@entry=0x7f19e20057c0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/codegen/NodeEvaluation.cpp:181
#20 0x00007f1a35bc684c in OMR::X86::TreeEvaluator::treetopEvaluator (node=<optimized out>, cg=0x7f19e2005cd0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/x/codegen/OMRTreeEvaluator.cpp:3143
--Type <RET> for more, q to quit, c to continue without paging--
#21 0x00007f1a357cdfcf in OMR::CodeGenerator::evaluate (this=this@entry=0x7f19e2005cd0, node=node@entry=0x7f19e2080000)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/codegen/NodeEvaluation.cpp:181
#22 0x00007f1a35408f1e in J9::CodeGenerator::doInstructionSelection (this=this@entry=0x7f19e2005cd0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/openj9/runtime/compiler/codegen/J9CodeGenerator.cpp:2109
#23 0x00007f1a357db412 in OMR::CodeGenPhase::performInstructionSelectionPhase (cg=0x7f19e2005cd0, phase=0x7f19e2006100)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/codegen/OMRCodeGenPhase.cpp:412
#24 0x00007f1a357d9d42 in OMR::CodeGenPhase::performAll (this=this@entry=0x7f19e2006100)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/codegen/OMRCodeGenPhase.cpp:136
#25 0x00007f1a357d7cb3 in OMR::CodeGenerator::generateCode (this=0x7f19e2005cd0)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/codegen/OMRCodeGenerator.cpp:1383
#26 0x00007f1a3580661d in OMR::Compilation::compile (this=this@entry=0x7f19e2000000)
    at /root/home/ahuo/src/openj9-openjdk-jdk/omr/compiler/compile/OMRCompilation.cpp:1114
...
```

### PR DESCRIPTION
**Pull request by a7ehuo**
When value type is enabled, loadArrayElement in ILGen uses helper
calls jitLoadFlattenableArrayElement to load array elements.
In some cases, if arrays are known not to be value types, we need
an API to do regular array element load.

Fixes #13540

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

File: runtime/compiler/ilgen/Walker.cpp [hunk 1]
```diff
@@ -6086,6 +6086,12 @@ TR_J9ByteCodeIlGenerator::loadArrayElement(TR::DataType dataType, TR::ILOpCodes
       return;
       }
 
+   loadArrayElementWithoutHelper(dataType, nodeop, checks);
+   }
+
+void
+TR_J9ByteCodeIlGenerator::loadArrayElementWithoutHelper(TR::DataType dataType, TR::ILOpCodes nodeop, bool checks)
```
Comment (hzongaro) [inline runtime/compiler/ilgen/Walker.cpp:6093]: I think the changes look correct.  One suggestion I have is to keep the single `loadArrayElement` method, and instead add an extra `bool isNotFlattened` or `isNotValueType` argument, which would be `false` by default and `true` in the case of `loadInvokeCacheArrayElements`.  That would make the treatment similar to the treatment for `checks`.

Comment (a7ehuo) [reply runtime/compiler/ilgen/Walker.cpp]: Updated in  5e0c88e

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

File: runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp [hunk 2]
```diff
@@ -197,7 +197,7 @@ class TR_J9ByteCodeIlGenerator : public TR_IlGenerator, public TR_J9ByteCodeIter
    TR::SymbolReference *loadClassObjectForTypeTest(int32_t cpIndex, TR_CompilationOptions aotInhibit);
    void         loadClassObject(TR_OpaqueClassBlock *opaqueClass);
    void         loadArrayElement(TR::DataType dt){ loadArrayElement(dt, comp()->il.opCodeForIndirectArrayLoad(dt)); }
-   void         loadArrayElement(TR::DataType dt, TR::ILOpCodes opCode, bool checks = true);
+   void         loadArrayElement(TR::DataType dt, TR::ILOpCodes opCode, bool checks = true, bool isNotValueType = false);
```
Comment (0xdaryl) [inline runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp:200]: I find the default negative naming to be a bit confusing.  How about naming this `bool mayBeValueType = true` ?  The presumption being that it may be a value type until proven otherwise.  If you agree, the consumers of this parameter will have to flip their polarity.

Comment (a7ehuo) [reply runtime/compiler/ilgen/J9ByteCodeIlGenerator.hpp]: Updated in fa98a9c

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by a7ehuo** [comment]
[Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal](https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal/9/console) failed likely because of infrastructure 
```
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to ub20-x86-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
		at jdk.internal.reflect.GeneratedMethodAccessor497.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
		at com.sun.proxy.$Proxy72.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1223)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1301)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$558/0x0000000000000000.run(Unknown Source)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

We should test with a non-Valhalla build too.

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

Aborted it seems.

**Comment by a7ehuo** [comment]
Functional test build failed with the following error in `SCHelperCompatTests/playlist.xml`. Likely it's fixed by #13592. I'll rebase and do another push. 

```
09:18:24  Error: schema validation failed for /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/aqa-tests/TKG/../functional/cmdLineTests/shareClassTests/SCHelperCompatTests/playlist.xml with exception:
09:18:24  
09:18:24  Line: 52
09:18:24  Column: 8
09:18:24  Message: cvc-complex-type.2.4.a: Invalid content was found starting with element 'aot'. One of '{disables, capabilities, platform, types, vendors, versions}' is expected.
09:18:25  makeGen.mk:45: recipe for target 'autogen' failed
09:18:25  make[1]: *** [autogen] Error 1
```

**Comment by a7ehuo** [comment]
@0xdaryl Ready to relaunch jdk11 and jdknext sanity test again, maybe xlinuxval jdknext too which passed previously. Thanks!

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by a7ehuo** [comment]
JDK11 sanity.functional tests have passed. 
[JDKNext sanity.functional tests](https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_vt_standard_Personal/11/) failed in 4 tests. They seem to be a known issue in JDK18 "`Expected exception of type class ... but got ...`" tracked in #12942

Jep397Tests_testSubClassOfSealedSuperFromDifferentPackageInSameUnamedModule_0
```
FAILED: test_subClassInTheDifferentPackageFromSealedSuperClass
org.testng.TestException: 
Expected exception of type class java.lang.IncompatibleClassChangeError but got java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=TestSubclass, offset=6
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
...
```


CloseScope0Tests_0
```
FAILED: closeScopeDuringAccess
org.testng.TestException: 
Expected exception of type class java.lang.IllegalStateException but got java.lang.ClassNotFoundException: jdk.internal.foreign.MemoryScope
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
...
```

Jep360Tests_0
```
FAILED: test_redefineClass_addPermittedSubclassEntry
org.testng.TestException: 
Expected exception of type class java.lang.UnsupportedOperationException but got java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=TestClassSealed, offset=6
...
```

Jep397Tests_testSubClassOfSealedSuperFromDifferentModule_0
```
FAILED: test_subClassInTheDifferentModuleFromSealedSuperClass
org.testng.TestException: 
Expected exception of type class java.lang.IncompatibleClassChangeError but got java.lang.UnsupportedClassVersionError: JVMCFRE163 Class file is a preview version but has the wrong major version or preview is not enabled.; class=TestSubclass, offset=6
	at testng/org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
...
```

**Review by 0xdaryl — APPROVED** [review]
