### PR TITLE
Push/pop the array object into/from special frame in slow path

### LINKED ISSUE #13848: Crash with value type array element flattening enabled with -Xint
I ran into a crash in `GC_ArrayletObjectModel::getDataSizeInBytes` [1] with the following code [2] when value type array element flattening is enabled (JDK18). It looks `clazzPtr` is not a legit `J9Class`. Attached the test code [3]. 

* Using `new SingleFieldPrimitive(j)` to create value type arrays is fine but using `new SingleFieldPrimitive()` causes the crash
* Only happens when array element flattening is enabled

Options used
```
-Xshareclasses:none -Xverify:none -XX:+EnableValhalla -XX:+EnableArrayFlattening -XX:ValueTypeFlatteningThreshold=999999 -Xint TestSingleFieldPrimitive
```

Running the following option without array element flattening is fine 
```
-Xshareclasses:none -Xverify:none -XX:+EnableValhalla -Xint TestSingleFieldPrimitive
```

[1]
```
#12 <signal handler called>
#13 0x00007fc52a81edce in GC_ArrayletObjectModel::getDataSizeInBytes (numberOfElements=4294615088, clazzPtr=0xffe17400, 
    this=0x7fc52c0297b8) at /root/hostdir/openj9/runtime/gc_glue_java/ArrayletObjectModel.hpp:369
#14 GC_ArrayletObjectModel::getDataSizeInBytes (arrayPtr=0xfffaa020, this=0x7fc52c0297b8)
    at /root/hostdir/openj9/runtime/gc_glue_java/ArrayletObjectModel.hpp:353
#15 GC_ArrayletObjectModel::getArrayLayout (objPtr=0xfffaa020, this=0x7fc52c0297b8)
    at /root/hostdir/openj9/runtime/gc_glue_java/ArrayletObjectModel.hpp:407
#16 MM_ObjectAccessBarrier::indexableEffectiveAddress (elementSize=4, index=4105, array=0xfffaa020, vmThread=0x1aa00, 
    this=0x7fc52c036270) at /root/hostdir/openj9/runtime/gc_base/ObjectAccessBarrier.hpp:110
#17 MM_ObjectAccessBarrier::copyObjectFieldsFromFlattenedArrayElement (this=0x7fc52c036270, vmThread=0x1aa00, 
    arrayClazz=0x159b00, destObject=0xffe7f270, arrayRef=0xfffaa020, index=4105)
    at /root/hostdir/openj9/runtime/gc_base/ObjectAccessBarrier.cpp:1159
#18 0x00007fc530a5211c in MM_ObjectAccessBarrierAPICompressed::copyObjectFieldsFromFlattenedArrayElement (
    index=<optimized out>, arrayRef=<optimized out>, destObject=<optimized out>, arrayClazz=<optimized out>, 
    vmThread=<optimized out>, this=<optimized out>)
    at /root/hostdir/openj9/runtime/gc_include/ObjectAccessBarrierAPI.hpp:397
#19 VM_ValueTypeHelpersCompressed::loadFlattenableArrayElement (fast=<optimized out>, index=<optimized out>, 
    receiverObject=<optimized out>, _objectAllocate=..., _objectAccessBarrier=..., currentThread=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/ValueTypeHelpers.hpp:495
#20 VM_BytecodeInterpreterCompressed::aaload (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:6175
#21 VM_BytecodeInterpreterCompressed::run (this=0x7fc531a0a800, vmThread=0x0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:10667
#22 0x00007fc530a3cbe5 in bytecodeLoopCompressed (currentThread=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.inc:112
#23 0x00007fc530af1e92 in c_cInterpreter () at /root/hostdir/build/linux-x86_64-server-release/vm/runtime/vm/xcinterp.s:158
#24 0x00007fc5309c6c8f in runCallInMethod (env=0x7fc531a0a910, receiver=0x0, clazz=0xe33e0, methodID=0x7fc52c456608, 
    args=0x7fc531a0ad78) at /root/hostdir/openj9/runtime/vm/callin.cpp:1123
#25 0x00007fc5309eaca9 in gpProtectedRunCallInMethod (entryArg=0x7fc531a0ad30)
    at /root/hostdir/openj9/runtime/vm/jnicsup.cpp:301
#26 0x00007fc52bdb4f03 in omrsig_protect (portLibrary=0x7fc531207340 <j9portLibrary>, 
    fn=0x7fc530afd290 <signalProtectAndRunGlue>, fn_arg=0x7fc531a0acd0, handler=0x7fc5309e7ce0 <structuredSignalHandler>, 
    handler_arg=0x1aa00, flags=506, result=0x7fc531a0acc8) at /root/hostdir/omr/port/unix/omrsignal.c:425
#27 0x00007fc530afd32c in gpProtectAndRun (function=0x7fc5309eac70 <gpProtectedRunCallInMethod(void*)>, env=0x1aa00, 
    args=0x7fc531a0ad30) at /root/hostdir/openj9/runtime/util/jniprotect.c:78
#28 0x00007fc5309ec644 in gpCheckCallin (env=0x1aa00, receiver=receiver@entry=0x0, cls=0xe33e0, methodID=0x7fc52c456608, 
    args=args@entry=0x7fc531a0ad78) at /root/hostdir/openj9/runtime/vm/jnicsup.cpp:489
#29 0x00007fc5309ea67a in callStaticVoidMethod (env=<optimized out>, cls=<optimized out>, methodID=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/jnicgen.c:384
#30 0x00007fc532658396 in JavaMain (_args=<optimized out>) at src/java.base/share/native/libjli/java.c:545
#31 0x00007fc53265b339 in ThreadJavaMain (args=<optimized out>) at src/java.base/unix/native/libjli/java_md.c:677
#32 0x00007fc531c296db in start_thread (arg=0x7fc531a0b700) at pthread_create.c:463
#33 0x00007fc532383a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:9

(gdb) fr 13
#13 0x00007fc52a81edce in GC_ArrayletObjectModel::getDataSizeInBytes (numberOfElements=4294615088, clazzPtr=0xffe17400, 
    this=0x7fc52c0297b8) at /root/hostdir/openj9/runtime/gc_glue_java/ArrayletObjectModel.hpp:369
369			if ((size / stride) == numberOfElements) {
(gdb) print size
$1 = 0
(gdb) print stride
$2 = 0
(gdb) print numberOfElements
$3 = 4294615088
(gdb) print clazzPtr
$16 = (J9Class *) 0xffe17400
(gdb) print *clazzPtr
$5 = {eyecatcher = 35184373504784, romClass = 0xffe17410, superclasses = 0x0, classDepthAndFlags = 0, 
  classDepthWithFlags = 0, classFlags = 0, classLoader = 0x0, classObject = 0x0, initializeStatus = 0, ramMethods = 0x0, 
  ramStatics = 0x0, arrayClass = 0x0, totalInstanceSize = 0, lastITable = 0x0, instanceDescription = 0x0, 
  instanceLeafDescription = 0x0, instanceHotFieldDescription = 0, selfReferencingField1 = 0, selfReferencingField2 = 0, 
  initializerCache = 0x0, romableAotITable = 0, packageID = 0, module = 0x0, subclassTraversalLink = 0x0, 
  subclassTraversalReverseLink = 0x0, iTable = 0x0, castClassCache = 0, jniIDs = 0x0, lockOffset = 0, 
  paddingForGLRCounters = 0, reservedCounter = 0, cancelCounter = 0, newInstanceCount = 0, backfillOffset = 0, 
  replacedClass = 0x0, finalizeLinkOffset = 0, nextClassInSegment = 0x0, ramConstantPool = 0x0, callSites = 0x0, 
  invokeCache = 0x0, varHandleMethodTypes = 0x0, customSpinOption = 0x0, staticSplitMethodTable = 0x0, 
  specialSplitMethodTable = 0x0, jitMetaDataList = 0x0, gcLink = 0x0, hostClass = 0x0, nestHost = 0x0, 
  flattenedClassCache = 0x0, hotFieldsInfo = 0x0}

(gdb) fr 20
#20 VM_BytecodeInterpreterCompressed::aaload (_pc=<optimized out>, _sp=<optimized out>, this=<optimized out>)
    at /root/hostdir/openj9/runtime/vm/BytecodeInterpreter.hpp:6175
6175						value = VM_ValueTypeHelpers::loadFlattenableArrayElement(_currentThread, _objectAccessBarrier, _objectAllocate, arrayref, index, false);
(gdb) print arrayref
$17 = (j9object_t) 0xfffaa020
(gdb) print *arrayref
$18 = {clazz = 4292965380}
(gdb) print /x *arrayref
$20 = {clazz = 0xffe17404}
```

[2] 
```java
public class TestSingleFieldPrimitive {
    public static int _total;
 
    public static final int ARRAY_LENGTH = 8192;
 
    public static SingleFieldPrimitive[][] arrays = new SingleFieldPrimitive[2][];
 
    public static void main(String[] args) {
        long numIterations = 40;
 
        for (int i = 0; i < arrays.length; i++) {
            SingleFieldPrimitive[] arr = new SingleFieldPrimitive[ARRAY_LENGTH];
            arrays[i] = arr;
 
            for (int j = 0; j < arr.length; j++) {
                arr[j] = new SingleFieldPrimitive();   //<==== crash
                //arr[j] = new SingleFieldPrimitive(j); //<=== good 
            }
        }
 
        for (long loop = 0; loop < numIterations; loop++) {
            SingleFieldPrimitive[] arr = arrays[(int) (loop % 2)];
 
            for (int i = 0; i < arr.length; i++) {
                _total = _total + arr[i].i;
            }
        }
    }
}

```

[3]
[Archive.zip](https://github.com/eclipse-openj9/openj9/files/7456568/Archive.zip)

### PR DESCRIPTION
**Pull request by hangshao0**
In the slow path, loadFlattenableArrayElement() could call into
J9AllocateObject() which might trigger GC. Push/pop the array object
into/from special frame so that we always have the correct array object.

Closes #13848

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
FYI @dmitripivkine, not sure if you are interested in reviewing.

**Comment by hangshao0** [comment]
This PR only fixes `loadFlattenableArrayElement()`. We might have the same issue in other places, but they can be fixed in a separate PR.

**Comment by dmitripivkine** [comment]
Please note this fix is going to work only in case if `receiverObjAddress` passed to `loadFlattenableArrayElement()` is the GC root (slot is fixed up by GC automatically). If this limitation is not a problem I suggest to add comment about this (at least) to prevent possible misuse in the future

**Comment by tajila** [comment]
Looks like we weren't even saving the receiver in a special frame for `old_slow_jitLoadFlattenableArrayElement` so there are two problems here.

**Comment by hangshao0** [comment]
> For this approach to work, the JIT also needs to update their code to provide the address of the receiver object to the runtime helpers, but I am not sure they can since the value may be in a register......

Yeah, I'm not sure about the `cnathelp.cpp` change.

**Comment by gacholio** [comment]
Can the code be changed to not take the indirect pointer (take `j9object_t` instead)? If it's assumed there's a special frame on top of stack, the push/pop special code works.

**Comment by tajila** [comment]
> If it's assumed there's a special frame on top of stack, the push/pop special code works.

Yes, one option is to keep the code as it was an just take a `j9object_t`. In the slow path we can pop the special frame after allocating the object. But we may need to create new `VM_OutOfLineINL_Helpers` to build special stack frames. Also we will need to update the jit helpers to save the receiver.

The other option is to just push and pop in the helper, so we dont need to worry about fixing up all the places that use the helpers.

**Comment by hangshao0** [comment]
I see we are doing push/pop inside `VM_VMHelpers::getFlattenableField()`: https://github.com/eclipse-openj9/openj9/blob/master/runtime/vm/ValueTypeHelpers.hpp#L317to#L319

**Comment by tajila** [comment]
Okay, thats good. Means we dont need new helpers. We should just follow that model for this.

**Comment by gacholio** [comment]
Please document the fact that a special frame needs to be on stack when calling this code.

File: runtime/vm/ValueTypeHelpers.hpp [hunk 1]
```diff
@@ -456,6 +456,8 @@ class VM_ValueTypeHelpers {
 
 	/**
 	 * Performs an aaload operation on an object. Handles flattened and non-flattened cases.
+	 * This function could call into J9AllocateObject() which might trigger GC (in the slow path), so receiverObject might be moved by GC.
```
Comment (tajila) [inline runtime/vm/ValueTypeHelpers.hpp:459]: This only occurs if `fast` is false

File: runtime/vm/ValueTypeHelpers.hpp [hunk 2]
```diff
@@ -456,6 +456,8 @@ class VM_ValueTypeHelpers {
...
+	 * If the caller caches receiverObject and uses it after calling this fucntion, it needs to re-read receiverObject.
 	 *
 	 * Assumes recieverObject is not null.
```
Comment (tajila) [inline runtime/vm/ValueTypeHelpers.hpp:462]: below `If fast == false, special stack frame must be built and receiverObject must be pushed onto it.` that should change as the caller is no longer responsible for putting the receiverObject in the specialFrame

File: runtime/vm/ValueTypeHelpers.hpp (hunk 1 above)
Comment (hangshao0) [reply runtime/vm/ValueTypeHelpers.hpp:459]: Yes, I have `(in the slow path)` later in this sentence.

File: runtime/vm/ValueTypeHelpers.hpp (hunk 2 above)
Comment (hangshao0) [reply runtime/vm/ValueTypeHelpers.hpp:462]: Removed that comment.

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Review by gacholio — APPROVED** [review]

**Comment by tajila** [comment]
@hangshao0 there were some failures in the build

**Comment by hangshao0** [comment]
I will look at the failures.

**Comment by hangshao0** [comment]
Failed at:
```
4XESTACKTRACE                at java/lang/String.format(String.java:4894)
4XESTACKTRACE                at com/ibm/j9ddr/PointerHelper.beginAnnotatedMethod(BytecodeGenerator.java:420)
4XESTACKTRACE                at com/ibm/j9ddr/PointerHelper.doStructurePointerMethod(BytecodeGenerator.java:1631)
4XESTACKTRACE                at com/ibm/j9ddr/PointerHelper.doAccessorMethods(BytecodeGenerator.java:451)
4XESTACKTRACE                at com/ibm/j9ddr/PointerHelper.generate(BytecodeGenerator.java:1661)
4XESTACKTRACE                at com/ibm/j9ddr/PointerHelper.getClassBytes(BytecodeGenerator.java:321)
4XESTACKTRACE                at com/ibm/j9ddr/BytecodeGenerator.getPointerClassBytes(BytecodeGenerator.java:108)
4XESTACKTRACE                at com/ibm/j9ddr/StructureReader.getPointerClassBytes(StructureReader.java:1132)
...
```

Which is a known issue: https://github.com/eclipse-openj9/openj9/issues/13932

**Comment by hangshao0** [comment]
The failures in https://openj9-jenkins.osuosl.org/job/Pipeline_Build_Test_JDKnext_x86-64_linux_vt_standard/23/ are:

[1]
`j9vm.249    *   ** ASSERTION FAILED ** at /home/jenkins/workspace/Build_JDKnext_x86-64_linux_vt_standard_Personal/openj9/runtime/vm/BytecodeInterpreter.hpp:4030: ((0 ))`

which is 

```
inlUnsafeIsFlattenedArray(REGISTER_ARGS_LIST)
{
	updateVMStruct(REGISTER_ARGS);
	Assert_VM_unreachable();                  <-------------------- hit this line.
	return EXECUTE_BYTECODE;
}
```
I guess this is related to the JCL update that includes new code calling this new API, whose implementation has not been merged yet.

[2] 
Jep334Tests_0 failure, which is testing `describeConstable()/descriptorString()/arrayType()/componentType()`

There is an IllegalAccessException
 ```
java.lang.IllegalAccessException: access violation: class java.util.Objects$1, from class org.openj9.test.java_lang.Test_Class (unnamed module @b34edd1)
	at java.base/java.lang.invoke.MethodHandles$Lookup.makeAccessException(MethodHandles.java:2856)
	at java.base/java.lang.invoke.MethodHandles$Lookup.accessClass(MethodHandles.java:2934)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:2793)
	at java.base/java.lang.constant.ClassDescImpl.resolveConstantDesc(ClassDescImpl.java:79)
	at java.base/java.lang.constant.ClassDescImpl.resolveConstantDesc(ClassDescImpl.java:40)
	at org.openj9.test.java_lang.Test_Class.describeConstableTestGeneral(Test_Class.java:121)
	at org.openj9.test.java_lang.Test_Class.testClassDescribeConstable(Test_Class.java:108)
```
Which does not seem to be caused by this change.

Other failures might related to JCL update as well: 
```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at org.openj9.test.java_lang.Test_Class.testClassDescriptorString(Test_Class.java:83)
```
Which failed the assertion that `descriptorString()` on Object class is `Ljava/lang/Object;` https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java12andUp/src/org/openj9/test/java_lang/Test_Class.java#L83

**Comment by tajila** [comment]
Okay, thanks for confirming @hangshao0

**Comment by hangshao0** [comment]
https://github.com/eclipse-openj9/openj9/issues/13957 created for the `Jep334Tests_0` failure.
