### PR TITLE
Remove unnecessary idiom recognition assertions

### LINKED ISSUE #17819: Assertion failure at openj9/runtime/compiler/optimizer/IdiomRecognition.cpp:6692: false
The [assertion](https://github.com/eclipse-openj9/openj9/blob/ac121a2d3c357c432edfb9dc0b1ae52f30f6516b/runtime/compiler/optimizer/IdiomRecognition.cpp#L6692) at

`/home/jenkins/workspace/Build_JDK11_ppc64le_linux_Personal/openj9/runtime/compiler/optimizer/IdiomRecognition.cpp:6692: false`

fails during `sanity.functional` test case `JCL_Test_2` on `ppc64le_linux` for Java 11

Link to the [Jenkins job](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal/786/).

Stack trace:
```
org.openj9.test.java.lang.
Exception in thread "no-op thread" org.openj9.test.java.lang.Test_ThreadGroup$1UncaughtException
	at org.openj9.test.java.lang.Test_ThreadGroup$13.uncaughtException(Test_ThreadGroup.java:972) from jdk.internal.loader.ClassLoaders$AppClassLoader@9a9ece8e(file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
	at java.base/java.lang.Thread.uncaughtException(Thread.java:1363) from jrt:/java.base
org.openj9.test.java.lang.Test_Throwable$TestException: test
Assertion failed at /home/jenkins/workspace/Build_JDK11_ppc64le_linux_Personal/openj9/runtime/compiler/optimizer/IdiomRecognition.cpp:6692: false
VMState: 0x000544ff
	not implemented yet
compiling java/lang/AbstractStringBuilder.append([C)Ljava/lang/AbstractStringBuilder; at level: hot
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xbf2920) [0x7fb213b32920]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xc0641c) [0x7fb213b4641c]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3058) [0x7fb2136f3058]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c4) [0x7fb2136f33c4]
#4: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3cdb3c) [0x7fb21330db3c]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d6bd0) [0x7fb213316bd0]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x4354ac) [0x7fb2133754ac]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d3de0) [0x7fb213313de0]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d5a1c) [0x7fb213315a1c]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa003c8) [0x7fb2139403c8]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa01214) [0x7fb213941214]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa02384) [0x7fb213942384]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x735dac) [0x7fb213675dac]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x73ed70) [0x7fb21367ed70]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17f3c8) [0x7fb2130bf3c8]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x180844) [0x7fb2130c0844]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17d514) [0x7fb2130bd514]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17dd00) [0x7fb2130bdd00]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17bfbc) [0x7fb2130bbfbc]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17c878) [0x7fb2130bc878]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17c93c) [0x7fb2130bc93c]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#23: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17cf54) [0x7fb2130bcf54]
#24: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9thr29.so(+0x113e8) [0x7fb2193013e8]
#25: /lib/powerpc64le-linux-gnu/libpthread.so.0(+0x8838) [0x7fb219eb8838]
#26: /lib/powerpc64le-linux-gnu/libc.so.6(clone+0x74) [0x7fb219d4b884]

JIT: crashed while compiling java/lang/AbstractStringBuilder.append([C)Ljava/lang/AbstractStringBuilder; (recoverable 0)
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xbf2920) [0x7fb213b32920]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xc0641c) [0x7fb213b4641c]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x1627f8) [0x7fb2130a27f8]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3d6a0) [0x7fb21936d6a0]
#4: function __kernel_sigtramp_rt64+0 [0]
#5: /lib/powerpc64le-linux-gnu/libpthread.so.0(raise+0xd8) [0x7fb219eca6a8]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3210) [0x7fb2136f3210]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c8) [0x7fb2136f33c8]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3cdb3c) [0x7fb21330db3c]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d6bd0) [0x7fb213316bd0]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x4354ac) [0x7fb2133754ac]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d3de0) [0x7fb213313de0]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d5a1c) [0x7fb213315a1c]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa003c8) [0x7fb2139403c8]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa01214) [0x7fb213941214]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa02384) [0x7fb213942384]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x735dac) [0x7fb213675dac]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x73ed70) [0x7fb21367ed70]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17f3c8) [0x7fb2130bf3c8]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x180844) [0x7fb2130c0844]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17d514) [0x7fb2130bd514]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17dd00) [0x7fb2130bdd00]
#23: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17bfbc) [0x7fb2130bbfbc]
#24: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17c878) [0x7fb2130bc878]
#25: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17c93c) [0x7fb2130bc93c]
#26: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#27: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x17cf54) [0x7fb2130bcf54]
#28: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9thr29.so(+0x113e8) [0x7fb2193013e8]
#29: /lib/powerpc64le-linux-gnu/libpthread.so.0(+0x8838) [0x7fb219eb8838]
Unhandled exception
Type=Unhandled trap vmState=0x000544ff
J9Generic_Signal_Number=00000108 Signal_Number=00000005 Error_Value=00000000 Signal_Code=fffffffa
Handler1=00007FB219444A10 Handler2=00007FB21936D440
R0=00000000000000AE R1=00007FB1F2FF18A0 R2=00007FB219EF7F00 R3=0000000000000000
R4=00007FB1F2FF18C8 R5=0000000000000000 R6=0000000000000008 R7=00007FB219ECA680
R8=800000000280F033 R9=0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=00007FB1F30068F0 R14=0000000000000000 R15=FFFFFFFFFFFFFFF8
R16=00007FB1C0834860 R17=00007FB2180E9570 R18=00007FB1C0906040 R19=00007FB1C0902000
R20=FFFFFFFFFFFFFFFF R21=00007FB2180E9570 R22=00007FB1C0906040 R23=00007FB213D0A6C0
R24=0000000000000100 R25=0000000000000100 R26=00007FB2180E9430 R27=00007FB1C08375B0
R28=00007FB213D0C2D8 R29=00007FB1F2FF18C8 R30=0000000000000005 R31=0000000000000000
NIP=00007FB219ECA6A8 MSR=800000000280F033 ORIG_GPR3=0000000000000002 CTR=0000000000000000
LINK=00007FB219ECA618 XER=0000000000000000 CCR=0000000024024478 SOFTE=0000000000000001
TRAP=0000000000000C00 DAR=00007FB213B328E8 dsisr=0000000040000000 RESULT=0000000000000000
FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR1 ffffffffffffffff (f: 4294967296.000000, d: -nan)
FPR2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR3 3fefffffff800000 (f: 4286578688.000000, d: 1.000000e+00)
FPR4 3ff008040614b195 (f: 102019480.000000, d: 1.001957e+00)
FPR5 3fe62e47012a370a (f: 19543818.000000, d: 6.931491e-01)
FPR6 3fd54d514f7ca407 (f: 1333568512.000000, d: 3.328441e-01)
FPR7 3ed0101b5df7b634 (f: 1576515072.000000, d: 3.829698e-06)
FPR8 00007fb1f2ffabe8 (f: 4076841984.000000, d: 6.936793e-310)
FPR9 bfe0000000000001 (f: 1.000000, d: -5.000000e-01)
FPR10 00007fb1c0832ff0 (f: 3229822976.000000, d: 6.936752e-310)
FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR13 00007fb218d39530 (f: 416519488.000000, d: 6.936825e-310)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/lib/powerpc64le-linux-gnu/libpthread.so.0
Module_base_address=00007FB219EB0000 Symbol=raise
Symbol_address=00007FB219ECA5D0

Method_being_compiled=java/lang/AbstractStringBuilder.append([C)Ljava/lang/AbstractStringBuilder;
Target=2_90_20230718_1597 (Linux 5.4.0-153-generic)
CPU=ppc64le (4 logical CPUs) (0x1fcc00000 RAM)
----------- Stack Backtrace -----------
raise+0xd8 (0x00007FB219ECA6A8 [libpthread.so.0+0x1a6a8])
_ZN2TR4trapEv+0x70 (0x00007FB2136F3210 [libj9jit29.so+0x7b3210])
_ZN2TR9assertionEPKciS1_S1_z+0x98 (0x00007FB2136F33C8 [libj9jit29.so+0x7b33c8])
_ZN18TR_CISCTransformer16analyzeBoolTableEPP12TR_BitVectorPPN2TR7TreeTopEP11TR_CISCNodeS1_S8_S8_ii+0x100c (0x00007FB21330DB3C [libj9jit29.so+0x3cdb3c])
_ZN18TR_CISCTransformer20analyzeCharBoolTableEP11TR_CISCNodePhS1_PPN2TR7TreeTopE+0x210 (0x00007FB213316BD0 [libj9jit29.so+0x3d6bd0])
_Z25CISCTransform2CopyingTRTxP18TR_CISCTransformer+0x78c (0x00007FB2133754AC [libj9jit29.so+0x4354ac])
_ZN18TR_CISCTransformer27computeTopologicalEmbeddingEP12TR_CISCGraphS1_+0xa30 (0x00007FB213313DE0 [libj9jit29.so+0x3d3de0])
_ZN18TR_CISCTransformer7performEv+0xe5c (0x00007FB213315A1C [libj9jit29.so+0x3d5a1c])
_ZN3OMR9Optimizer19performOptimizationEPK20OptimizationStrategyiii+0xa78 (0x00007FB2139403C8 [libj9jit29.so+0xa003c8])
_ZN3OMR9Optimizer19performOptimizationEPK20OptimizationStrategyiii+0x18c4 (0x00007FB213941214 [libj9jit29.so+0xa01214])
_ZN3OMR9Optimizer8optimizeEv+0x2c4 (0x00007FB213942384 [libj9jit29.so+0xa02384])
_ZN3OMR11Compilation20performOptimizationsEv+0x3c (0x00007FB213675DAC [libj9jit29.so+0x735dac])
_ZN3OMR11Compilation7compileEv+0x620 (0x00007FB21367ED70 [libj9jit29.so+0x73ed70])
_ZN2TR28CompilationInfoPerThreadBase7compileEP10J9VMThreadPNS_11CompilationEP17TR_ResolvedMethodR11TR_J9VMBaseP19TR_OptimizationPlanRKNS_16SegmentAllocatorE+0x548 (0x00007FB2130BF3C8 [libj9jit29.so+0x17f3c8])
_ZN2TR28CompilationInfoPerThreadBase14wrappedCompileEP13J9PortLibraryPv+0x384 (0x00007FB2130C0844 [libj9jit29.so+0x180844])
omrsig_protect+0x358 (0x00007FB21936E848 [libj9prt29.so+0x3e848])
_ZN2TR28CompilationInfoPerThreadBase7compileEP10J9VMThreadP21TR_MethodToBeCompiledRN2J917J9SegmentProviderE+0x324 (0x00007FB2130BD514 [libj9jit29.so+0x17d514])
_ZN2TR24CompilationInfoPerThread12processEntryER21TR_MethodToBeCompiledRN2J917J9SegmentProviderE+0x280 (0x00007FB2130BDD00 [libj9jit29.so+0x17dd00])
_ZN2TR24CompilationInfoPerThread14processEntriesEv+0x3ac (0x00007FB2130BBFBC [libj9jit29.so+0x17bfbc])
_ZN2TR24CompilationInfoPerThread3runEv+0xf8 (0x00007FB2130BC878 [libj9jit29.so+0x17c878])
_Z30protectedCompilationThreadProcP13J9PortLibraryPN2TR24CompilationInfoPerThreadE+0x9c (0x00007FB2130BC93C [libj9jit29.so+0x17c93c])
omrsig_protect+0x358 (0x00007FB21936E848 [libj9prt29.so+0x3e848])
_Z21compilationThreadProcPv+0x234 (0x00007FB2130BCF54 [libj9jit29.so+0x17cf54])
thread_wrapper+0x1a8 (0x00007FB2193013E8 [libj9thr29.so+0x113e8])
start_thread+0xe8 (0x00007FB219EB8838 [libpthread.so.0+0x8838])
clone+0x74 (0x00007FB219D4B884 [libc.so.6+0x14b884])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2023/07/18 13:00:41 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/core.20230718.130041.2921696.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/core.20230718.130041.2921696.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/javacore.20230718.130041.2921696.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/javacore.20230718.130041.2921696.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/Snap.20230718.130041.2921696.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/Snap.20230718.130041.2921696.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/aqa-tests/TKG/output_16897069832009/JCL_Test_2/jitdump.20230718.130041.2921696.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'JIT Compilation Thread-001' thread 0x000000000009A200
JVMDUMP049I JIT dump notified all waiting threads of the current method to be compiled
JVMDUMP054I JIT dump is tracing the IL of the method on the crashed compilation thread
Assertion failed at /home/jenkins/workspace/Build_JDK11_ppc64le_linux_Personal/openj9/runtime/compiler/infra/J9MonitorTable.cpp:255: false
VMState: 0x000544ff
	comp thread 1 does not have classUnloadMonitor
compiling java/lang/AbstractStringBuilder.append([C)Ljava/lang/AbstractStringBuilder; at level: hot
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xbf2920) [0x7fb213b32920]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xc0641c) [0x7fb213b4641c]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3058) [0x7fb2136f3058]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c4) [0x7fb2136f33c4]
#4: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x363114) [0x7fb2132a3114]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x2b1978) [0x7fb2131f1978]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x2b1c48) [0x7fb2131f1c48]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x184260) [0x7fb2130c4260]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x284f2c) [0x7fb2131c4f2c]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3239a0) [0x7fb2132639a0]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x1b2cac) [0x7fb2130f2cac]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x1b26b8) [0x7fb2130f26b8]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xc3e8) [0x7fb218d8c3e8]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0x4ea0) [0x7fb218d84ea0]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xb090) [0x7fb218d8b090]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xb290) [0x7fb218d8b290]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0x2e79c) [0x7fb218dae79c]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x447c4) [0x7fb2194447c4]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x44bc4) [0x7fb219444bc4]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3d6a0) [0x7fb21936d6a0]
#23: function __kernel_sigtramp_rt64+0 [0]
#24: /lib/powerpc64le-linux-gnu/libpthread.so.0(raise+0xd8) [0x7fb219eca6a8]
#25: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3210) [0x7fb2136f3210]
#26: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c8) [0x7fb2136f33c8]
#27: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3cdb3c) [0x7fb21330db3c]
#28: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d6bd0) [0x7fb213316bd0]
#29: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x4354ac) [0x7fb2133754ac]

JVMDUMP052I JIT dump recursive crash occurred on diagnostic thread
JVMDUMP048I JIT dump method being compiled is an ordinary method
Assertion failed at /home/jenkins/workspace/Build_JDK11_ppc64le_linux_Personal/openj9/runtime/compiler/infra/J9MonitorTable.cpp:255: false
VMState: 0x000544ff
	comp thread 1 does not have classUnloadMonitor
compiling java/lang/AbstractStringBuilder.append([C)Ljava/lang/AbstractStringBuilder; at level: hot
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xbf2920) [0x7fb213b32920]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xc0641c) [0x7fb213b4641c]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3058) [0x7fb2136f3058]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c4) [0x7fb2136f33c4]
#4: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x363114) [0x7fb2132a3114]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x2b1978) [0x7fb2131f1978]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x27e8e8) [0x7fb2131be8e8]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x1b27d4) [0x7fb2130f27d4]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xc3e8) [0x7fb218d8c3e8]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0x4ea0) [0x7fb218d84ea0]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xb090) [0x7fb218d8b090]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0xb290) [0x7fb218d8b290]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9dmp29.so(+0x2e79c) [0x7fb218dae79c]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x447c4) [0x7fb2194447c4]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3e848) [0x7fb21936e848]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9vm29.so(+0x44bc4) [0x7fb219444bc4]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9prt29.so(+0x3d6a0) [0x7fb21936d6a0]
#18: function __kernel_sigtramp_rt64+0 [0]
#19: /lib/powerpc64le-linux-gnu/libpthread.so.0(raise+0xd8) [0x7fb219eca6a8]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b3210) [0x7fb2136f3210]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x7b33c8) [0x7fb2136f33c8]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3cdb3c) [0x7fb21330db3c]
#23: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d6bd0) [0x7fb213316bd0]
#24: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x4354ac) [0x7fb2133754ac]
#25: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d3de0) [0x7fb213313de0]
#26: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0x3d5a1c) [0x7fb213315a1c]
#27: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa003c8) [0x7fb2139403c8]
#28: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa01214) [0x7fb213941214]
#29: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Personal_testList_1/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so(+0xa02384) [0x7fb213942384]

JVMDUMP013I Processed dump event "gpf", detail "".
-----------------------------------
JCL_Test_2_FAILED
```

### PR DESCRIPTION
**Pull request by jdmpapin**
There are uses of `TR_ASSERT()` in idiom recognition that check for cases that are not necessarily impossible and that are handled conservatively in builds where `TR_ASSERT()` is not checked. Assertions are not a good way to detect and report these cases, since assertion failure is not likely to be due to a bug.

This commit removes a number of these assertions. Now the conservative logic will apply in all builds. When it does, a static debug counter will be incremented, and (when tracing idiom recognition) a message will be printed to the log.

Anyone who wants to look for transformations that have been prevented due to incomplete support for a particular case can use the new static debug counters.

Additionally, use `dumpOptDetails()` to trace when a transformer fails. In that case it's misleading to leave the log showing only the message from `performTransformation()`.

Fixes #17819

### CODE REVIEW

File: runtime/compiler/optimizer/IdiomRecognition.cpp [hunk 1]
```diff
@@ -6688,10 +6688,33 @@ TR_CISCTransformer::analyzeBoolTable(TR_BitVector **bv, TR::TreeTop **retSameExi
                      takenBV &= tmpBV;
                      ntakenBV -= tmpBV;
                      break;
+
                   default:
-                     TR_ASSERT(false, "not implemented yet");
+                     {
                      // not implemented yet
+                     const char *opName =
+                        TR::ILOpCode((TR::ILOpCodes)n->getOpcode()).getName();
```
Comment (hzongaro) [inline runtime/compiler/optimizer/IdiomRecognition.cpp:6696]: A very minor comment, but is there any reason why this couldn't be written this way?

```
n->getIlOpCode().getName();
```

**Review by hzongaro — COMMENTED** [review]
I think your change looks good - just one minor question/comment.

I notice there are at least four other places in Idiom Recognition that have a `TR_ASSERT` that says "not implemented yet".  As the goal in the short-term is to get PROD_WITH_ASSUMES working for `sanity.functional` test runs, fixing just this one is fine for now, but may I ask you to open a follow up issue to track cleaning up the remaining four - assuming that they also describe situations that can be safely ignored?

File: runtime/compiler/optimizer/IdiomRecognition.cpp (hunk 1 above)
Comment (jdmpapin) [reply runtime/compiler/optimizer/IdiomRecognition.cpp]: I ended up not using this because I factored the logic into a function and I wanted to pass the numeric opcode

**Comment by jdmpapin** [comment]
Updated. Along with some assertions in the transformations, I caught `analyzeByteBoolTable()` and `analyzeCharBoolTable()`. What were the other two places you had in mind?

**Comment by hzongaro** [comment]
> What were the other two places you had in mind?

I think I miscounted - the third was in `analyzeBoolTable`, which was the one you originally changed.  The fourth is in [TR_CISCTransformer::modifyBlockByVersioningCheck](https://github.com/eclipse-openj9/openj9/blob/6ef55f5540c3ef358cccd39b7d37416f93c64780/runtime/compiler/optimizer/IdiomRecognition.cpp#L6074), and so far as I can tell, that method is never actually used.  Looking at it more closely, I think it represents a real assertion, rather than simply flagging something that was unimplemented.

Thanks for catching the additional changes in the transformations!  I'll review your changes.

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins test sanity all jdk11,jdk17

**Comment by hzongaro** [comment]
Jenkins test sanity jdk17 aarch64_linux

**Comment by hzongaro** [comment]
Jenkins test sanity aarch64_linux jdk17

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11

**Comment by hzongaro** [comment]
Jenkins test sanity aarch64_linux jdk17

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11
Jenkins test sanity aarch64_linux jdk17

**Comment by hzongaro** [comment]
Jenkins test sanity zlinux jdk11

**Comment by hzongaro** [comment]
Jenkins test sanity aarch64_linux jdk17
