### PR TITLE
Fix buffer overflow in javadump trace formatting for large objects

### LINKED ISSUE #22880: jdk_nio_1 java/nio/charset/CharsetDecoder/XcodeOverflow.java OOM, stack smashing detected, timed out
**Failure link**
---
From internal [Test_openjdk25_j9_extended.openjdk_s390x_linux_testList_2](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk25_j9_extended.openjdk_s390x_linux_testList_2/49/) (sles15s390x-svl-rt3-1)

```**Java Version**
java version "25.0.1-beta" 2025-10-21
IBM Semeru Runtime Certified Edition 25.0.1+8-202511011600 (build 25.0.1-beta+8-202511011600)
Eclipse OpenJ9 VM 25.0.1+8-202511011600 (build 25.0.1-beta+8-202511011600-master-32e41c6fa4, JRE 25 Linux s390x-64-Bit Compressed References 20251101_73 (JIT enabled, AOT enabled)
OpenJ9   - 32e41c6fa4
OMR      - 55e1efdf4
JCL      - 9caebab0a based on jdk-25.0.1+8)
```

[Rerun in Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?SDK_RESOURCE=customized&amp;TARGET=jdk_nio_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk25_j9_extended.openjdk_s390x_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=s390x_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk25%2Fjdk25-linux-s390x-openj9-IBM%2F73%2Fibm-semeru-certified-jdk_s390x_linux_JDK25U_2025-11-01-16-01.tar.gz+https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fsys-rt-generic-local%2Fhyc-runtimes-jenkins.swg-devops.com%2Fbuild-scripts%2Fjobs%2Fjdk25%2Fjdk25-linux-s390x-openj9-IBM%2F73%2Fibm-semeru-certified-testimage_s390x_linux_JDK25U_2025-11-01-16-01.tar.gz&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=Jenkins+4096+key&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=na.artifactory.swg-devops&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=83181e25-eea4-4f55-8b3e-e79615733226&amp;JDK_VERSION=25&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=git%40github.com%3Aibmruntimes%2Fopenj9-openjdk-jdk25&amp;JCK_GIT_BRANCH=main&amp;RELEASE_TAG=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=openj9&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=sys-rt-generic-local%2Chyc-runtimes-team-restricted-oracle-sdk-generic-local&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=61&amp;DOCKERIMAGE_TAG=&amp;TEST_TIME=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=%23rt-jenkins&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=7c1c2c28-650f-49e0-afd1-ca6b60479546&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=https%3A%2F%2Ftrssrtp1.fyre.ibm.com%2F&amp;RERUN_FAILURE=false&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None) - Change TARGET to run only the failed test targets

**Optional info**
---
Failure output (captured from console output)
---
```
[2025-11-01T20:50:23.547Z] Running test jdk_nio_1 ...
[2025-11-01T20:50:23.547Z] ===============================================
[2025-11-01T20:50:23.547Z] jdk_nio_1 Start Time: Sat Nov  1 13:50:23 2025 Epoch Time (ms): 1762030223276
[2025-11-01T20:50:23.547Z] variation: Mode650
[2025-11-01T20:50:23.547Z] JVM_OPTIONS:  -XX:-UseCompressedOops -Xverbosegclog 

[2025-11-01T21:30:20.270Z] TEST: java/nio/charset/CharsetDecoder/XcodeOverflow.java

[2025-11-01T21:30:20.272Z] STDERR:
[2025-11-01T21:30:20.272Z] JVMDUMP055I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError", exception "Java heap space" at 2025/11/01 14:01:50 - please wait.

[2025-11-01T21:30:20.272Z] *** stack smashing detected ***: terminated

[2025-11-01T21:30:20.273Z] TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk25_j9_extended.openjdk_s390x_linux_testList_2/jdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1705006ms).
```

[50x internal Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/56000/) - failed 20/50 across all children

### PR DESCRIPTION
**Pull request by AditiS11**
Increase _MaximumFormattedTracePointLength from 512 to 2048 bytes 
to prevent overflow when formatting trace messages containing large object.
Fixes: https://github.com/eclipse-openj9/openj9/issues/22880

### CODE REVIEW

**Comment by AditiS11** [comment]
50x Grinder

1. s390x-Linux (All 50 iterations passed) --> https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/59692/console
2. linux-aarch64 (All 50 iterations passed) --> https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/59684/console
3. mac x86-64 (All 50 iterations passed) -->https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/59693/console

File: runtime/rasdump/javadump.cpp
Comment (keithc-ca) [inline runtime/rasdump/javadump.cpp]: Please correct the types so they're consistent (compare lines 398 and 409); each of the constants declared on lines 397-402 should have type `U_32`.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

**Comment by keithc-ca** [comment]
At first I was going to suggest there's no fixed bound on the length of a formatted tracepoint, particularly if `-Xtrace:maxstringlenth` is used with a large value, or a method has a large number of string parameters. However, the maximum acceptable value for `maxstringlength` is 128, and `method_trace.c` uses a 1024 byte buffer for parameters. If either of those change, this may need to be revisited.

File: runtime/rasdump/javadump.cpp
Comment (keithc-ca) [reply runtime/rasdump/javadump.cpp]: I was asking that you change lines 397-402 and lines 408-413 so they all use `U_32`.
```c
	static const U_32 _MaximumExceptionNameLength;
	static const U_32 _MaximumFormattedTracePointLength;
	static const U_32 _MaximumCommandLineLength;
	static const U_32 _MaximumTimeStampLength;
	static const U_32 _MaximumGPValueLength;
	static const U_32 _MaximumJavaStackDepth;
```

```c
const U_32 JavaCoreDumpWriter::_MaximumExceptionNameLength(128);
const U_32 JavaCoreDumpWriter::_MaximumFormattedTracePointLength(2048);
const U_32 JavaCoreDumpWriter::_MaximumCommandLineLength(512);
const U_32 JavaCoreDumpWriter::_MaximumTimeStampLength(30);
const U_32 JavaCoreDumpWriter::_MaximumGPValueLength(512);
const U_32 JavaCoreDumpWriter::_MaximumJavaStackDepth(100000);
```

**Review by keithc-ca — CHANGES_REQUESTED** [review]
Please also fix the commit message: Lines in the body should be no more than 72 characters long. See https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#commit-guidelines.

File: runtime/rasdump/javadump.cpp [hunk 1]
```diff
@@ -394,23 +394,23 @@ private :
 	int64_t           _DumpStart;
 
 	/* Static declared data */
-	static const unsigned int _MaximumExceptionNameLength;
+	static const U_32  _MaximumExceptionNameLength;
```
Comment (keithc-ca) [inline runtime/rasdump/javadump.cpp]: Just one space after `U_32`, please.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: runtime/rasdump/javadump.cpp (hunk 1 above)
Comment (pshipton) [reply runtime/rasdump/javadump.cpp]: I've removed the space.

**Comment by keithc-ca** [comment]
Jenkins compile amac jdk21

**Review by keithc-ca — APPROVED** [review]
