### PR TITLE
Make BoolArrayStoreTransformer iterate CFG for DLT compiles

### LINKED ISSUE #15369: Compilation Fails even from noOpt Level
Java -version output
--------------------
```
openjdk version "11.0.16-internal" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16-internal+0-adhoc..openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-4ca209b54, JRE 11 Linux amd64-64-Bit Compressed References 20220615_000000 (JIT enabled, AOT enabled)
OpenJ9   - 4ca209b54
OMR      - 26b89f9f9
JCL      - 231dcc9eeb based on jdk-11.0.16+6)


openjdk version "1.8.0_342-internal"
OpenJDK Runtime Environment (build 1.8.0_342-internal-_2022_06_10_15_18-b00)
Eclipse OpenJ9 VM (build master-3d06b2f9c, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20220610_000000 (JIT enabled, AOT enabled)
OpenJ9   - 3d06b2f9c
OMR      - cf8ddbd1a
JCL      - 2bb179375a based on jdk8u342-b05)
```

Summary of problem
------------------

Looks like the test fails from `noOpt` level, so it should be different from #15306 and #15347. This affects both JDK11 and JDK8.

``` java
class Test {
  int N = 256;

  void mainTest(String[] strArr1) {
    int i26, i28, i32;
    byte[] byArr = new byte[N];
    for (i26 = 12; i26 < 222; ++i26) {
      for (i28 = 24; i28 > 1; i28 -= 3) for (i32 = 1; i32 < 4; i32 += 2) byArr[i28] -= i32;
      for (int ax$14 = 3005; ax$14 < 6948; ax$14 += 1) {
        boolean[] ax$11 = new boolean[576];
      }
    }
    long ccc = checkSum(byArr);
    System.out.println(ccc);
  }

  public static void main(String[] strArr) {
    Test _instance = new Test();
    _instance.mainTest(strArr);
  }

  public static long checkSum(byte[] a) {
    long sum = 0;
    for (int j = 0; j < a.length; j++) {
      sum += (byte) (a[j] / (j + 1) + a[j] % (j + 1));
    }
    return sum;
  }
}
```

Results of OpenJ9:

```
$ ./OpenJ9/jdk11/java Test
0
```

Results of OpenJ9-Xint (HotSpot/ART also give the same result): 

```
$ ./OpenJ9/jdk11/java -Xint Test
-114
```

Diagnosis
---------

If you exclude `Test.mainTest()` from compilation, then it gives the same result as HotSpot/ART/OpenJ9-Xint

```
$ ./OpenJ9/jdk11/bin/java '-Xjit:exclude={Test.mainTest(*)*}' Test        
-114
```

But if you compile `Test.mainTest()` even from `noOpt` level, it gives `0` again

```
$ ./OpenJ9/jdk11/bin/java '-Xjit:{Test.mainTest(*)*}(optlevel=noOpt)' Test
0
```

So I reckon this to be different from 15306 (scorching) and 15347 (hot). (So is JDK8.)

### PR DESCRIPTION
**Pull request by BradleyWood**
On DLT compiles where type information is not available we must not truncate byte stores to 1-bit.

Fixes #15369

Signed-off-by: BradleyWood <bradley.wood@ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Comment by 0xdaryl** [comment]
AArch64 CI failure seems to be a variant of #13577.

**Comment by BradleyWood** [comment]
x64 mac failure caused by warning:

```
12:03:37  /Users/jenkins/workspace/Build_JDK17_x86-64_mac_Personal/openj9/runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp:155:40: error: '&&' within '||' [-Werror,-Wlogical-op-parentheses]
12:03:37        if (_hasByteArrayAutoOrCheckCast && _hasBoolArrayAutoOrCheckCast || comp()->isDLT())
```

I'll add parenthesis...

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk17

File: runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp [hunk 1]
```diff
@@ -152,8 +152,12 @@ void TR_BoolArrayStoreTransformer::perform()
 
    if (!_bstoreiUnknownArrayTypeNodes->empty())
       {
-      if (_hasByteArrayAutoOrCheckCast && _hasBoolArrayAutoOrCheckCast) // only need to iterate CFG if both byte and boolean array exist
+      if ((_hasByteArrayAutoOrCheckCast && _hasBoolArrayAutoOrCheckCast) || comp()->isDLT())
+         {
+         // need to iterate CFG if both byte and boolean array exist or on DLT compiles
+         // On DLT compiles where type information is not available we must not truncate byte stores to 1-bit
```
Comment (jdmpapin) [inline runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp:158]: > we must not truncate byte stores to 1-bit

I think this part of the comment (and the commit message) is misleading. We have to truncate the value at every `bastore` if and only if it's storing to a `boolean[]`. We could just as well incorrectly leave a `bstorei` node unmodified (failing to truncate) when it stores to a `boolean[]` but without any `boolean[]` autos or `checkcast` detected in the trees

I think it would be better to say just that not all of the bytecode has been translated into IL, so there may have been autos and/or `checkcast` operations of both `boolean[]` and `byte[]` type, and the full analysis is needed

**Review by jdmpapin — APPROVED** [review]
Approved assuming that the comment/commit message will be clarified

A similar problem is possible when parameters are overwritten by bytecode instructions that don't get translated to trees for DLT, and this transformation can currently trust the parameter signature when it shouldn't. However, in determining that this problem exists, I've fixed it myself. This PR is already a strict improvement, so I think it should be merged as-is, and I will open a follow-up fix afterward

File: runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp (hunk 1 above)
Comment (BradleyWood) [reply runtime/compiler/optimizer/BoolArrayStoreTransformer.cpp]: [Updated the comment](https://github.com/eclipse-openj9/openj9/compare/831e3be7f7fe1974f05967d612b860a1d1437429..1abf31f922dd1c6a4a96c7471667133d09a96b99)

**Comment by jdmpapin** [comment]
@0xdaryl, are you ok with merging this now?

**Review by 0xdaryl — APPROVED** [review]
