### PR TITLE
Fix jdk/internal/misc/Unsafe.copyMemory crash without value propagation

### LINKED ISSUE #13314: Liberty app server does not start without value propagation
I was doing some performance investigation and observed that Liberty app server cannot start with `-Xjit:optLevel=noOpt`. I switched to `-Xjit:optLevel=cold`, but ran into the same issue once I added `disableLocalVP`. Further investigation revealed that the problematic method is 
`jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V>`
Value propagation changes `Unsafe.copyMemory` into arraycopy and this transformation seems to be essential for correctness:
```
[     5] O^O VALUE PROPAGATION: Changing call Unsafe.copyMemory [00007F24DB004510] to arraycopy
```
I don't know if this can be considered a bug, but losing the ability to use optLevel=noOpt, or disable VP is an inconvenience.

### PR DESCRIPTION
**Pull request by BradleyWood**
Running with optLevel=noOpt or disableLocalVP causes VM crash on startup when Unsafe.copyMemory is called. This fix ensures that the intrinsic is inlined.

Closes #13314 

Signed-off-by: BradleyWood <bradley.wood@ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
It isn't clear to me why this method MUST be inlined by the backend for correctness as opposed to allowing it to be called directly.  Calling it directly might be slower, but it should always be a functionally correct thing to do.  Without this clarity I'm worried we're just avoiding the problem by inlining it.  Can you provide more rationale for this fix please?

Also, I also observed a similar backtrace on AArch64 (I did not try the other architectures).  The heart of this PR addresses x86 only.

**Comment by BradleyWood** [comment]
The call can always go through the JNI, however I believe the original intent was to optimize copyMemory instead by inlining with the array copy intrinsic (there is even a jit option to disable this).

https://github.com/eclipse-openj9/openj9/blob/cd8db74f1d43b37e3bdbd1c72f9e120d18047634/runtime/compiler/il/J9Node.cpp#L294-L298

If the path above executes, the intrinsic is not inlined, and VP does not run, then there is no copyMemory call. By default, the native function seems to have IL that calls itself (should there be an 'unimplemented' IL opcode to catch this?) which causes the stack overflow.

I can address the other platforms.

**Comment by BradleyWood** [comment]
@0xdaryl should be ready for review.

**Comment by BradleyWood** [comment]
```
Post Optimization Trees: for jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
n1n       BBStart <block_2> (freq 10000)                                                      [0x7f77245b2220] bci=[-1,0,-] rc=0 vc=38 vn=- li=- udi=- nc=0
n10n      treetop                                                                             [0x7f77245b24f0] bci=[-1,0,-] rc=0 vc=38 vn=- li=- udi=- nc=1
n9n         call  jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V[#363  final native virtual Method] [flags 0x20500 0x0 ] ()  [0x7f77245b24a0] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=6 flg=0x20
n3n           aload  <'this' parm Ljdk/internal/misc/Unsafe;>[#351  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [0x7f77245b22c0] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0 flg=0x4
n4n           aload  <parm 1 Ljava/lang/Object;>[#352  Parm] [flags 0x40000107 0x0 ]          [0x7f77245b2310] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0
n5n           lload  <parm 2 J>[#353  Parm] [flags 0x40000104 0x0 ]                           [0x7f77245b2360] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0
n6n           aload  <parm 4 Ljava/lang/Object;>[#354  Parm] [flags 0x40000107 0x0 ]          [0x7f77245b23b0] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0
n7n           lload  <parm 5 J>[#355  Parm] [flags 0x40000104 0x0 ]                           [0x7f77245b2400] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0
n8n           lload  <parm 7 J>[#356  Parm] [flags 0x40000104 0x0 ]                           [0x7f77245b2450] bci=[-1,0,-] rc=1 vc=38 vn=- li=- udi=- nc=0
n11n      return                                                                              [0x7f77245b2540] bci=[-1,0,-] rc=0 vc=38 vn=- li=- udi=- nc=0
n2n       BBEnd </block_2>   
```

```
Post Lower Trees: for jdk/internal/misc/Unsafe.copyMemory0(Ljava/lang/Object;JLjava/lang/Object;JJ)V

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
n1n       BBStart <block_2> (freq 10000)                                                      [0x7f77245b2220] bci=[-1,0,-] rc=0 vc=41 vn=- li=2 udi=- nc=0
n14n      arraycopy  <arraycopy>[#217  helper Method] [flags 0x400 0x0 ] ()                   [0x7f77245b2630] bci=[-1,0,-] rc=0 vc=0 vn=- li=- udi=- nc=3 flg=0x20
n12n        aladd                                                                             [0x7f77245b2590] bci=[-1,0,-] rc=1 vc=0 vn=- li=- udi=- nc=2
n4n           aload  <parm 1 Ljava/lang/Object;>[#352  Parm] [flags 0xc0000107 0x0 ]          [0x7f77245b2310] bci=[-1,0,-] rc=1 vc=41 vn=- li=2 udi=- nc=0
n5n           lload  <parm 2 J>[#353  Parm] [flags 0xc0000104 0x0 ]                           [0x7f77245b2360] bci=[-1,0,-] rc=1 vc=41 vn=- li=2 udi=- nc=0
n13n        aladd                                                                             [0x7f77245b25e0] bci=[-1,0,-] rc=1 vc=0 vn=- li=- udi=- nc=2
n6n           aload  <parm 4 Ljava/lang/Object;>[#354  Parm] [flags 0xc0000107 0x0 ]          [0x7f77245b23b0] bci=[-1,0,-] rc=1 vc=41 vn=- li=2 udi=- nc=0
n7n           lload  <parm 5 J>[#355  Parm] [flags 0xc0000104 0x0 ]                           [0x7f77245b2400] bci=[-1,0,-] rc=1 vc=41 vn=- li=2 udi=- nc=0
n8n         lload  <parm 7 J>[#356  Parm] [flags 0xc0000104 0x0 ]                             [0x7f77245b2450] bci=[-1,0,-] rc=1 vc=41 vn=- li=2 udi=- nc=0
n11n      return                                                                              [0x7f77245b2540] bci=[-1,0,-] rc=0 vc=41 vn=- li=2 udi=- nc=0
n2n       BBEnd </block_2>   
```

**Comment by 0xdaryl** [comment]
Jenkins test all sanity jdk11,jdk17

**Comment by 0xdaryl** [comment]
The reason this method must be transformed by the backends if value propagation does not do it (as is the case when run with noopt) is because the code to prepare nodes for a JNI call checks whether `canTransformUnsafeCopyToArrayCopy()` and the method matches the `copyMemory0` method.  By avoiding preparing the node for JNI during ilgen, the logic assumes that some future transformation will transform this call, which is why this PR is needed.

File: runtime/compiler/codegen/J9CodeGenerator.cpp [hunk 1]
```diff
@@ -839,6 +839,52 @@ J9::CodeGenerator::lowerTreeIfNeeded(
...
       }
 
+   if (node->getOpCode().isCall() &&
+         node->getSymbol()->getMethodSymbol()->isNative() &&
+         comp()->canTransformUnsafeCopyToArrayCopy())
+      {
+      TR::RecognizedMethod rm = node->getSymbol()->castToMethodSymbol()->getRecognizedMethod();
+
+      if ((rm == TR::sun_misc_Unsafe_copyMemory || rm == TR::jdk_internal_misc_Unsafe_copyMemory0) &&
+            performTransformation(comp(), "O^O Call arraycopy instead of Unsafe.copyMemory: %s\n", comp()->cg()->getDebug()->getName(node)))
```
[the remark this answers is not in the document]
Comment (0xdaryl) [reply runtime/compiler/codegen/J9CodeGenerator.cpp:849]: All references to `comp()` in this method should be changed to `self()->comp()` to make the linter happy.

**Comment by 0xdaryl** [comment]
I'd like to target this for JDK18 (0.31).

File: runtime/compiler/codegen/J9CodeGenerator.cpp [hunk 2]
```diff
@@ -839,6 +839,52 @@ J9::CodeGenerator::lowerTreeIfNeeded(
...
+         {
+         TR::CodeGenerator *cg = comp()->cg();
```
[the remark this answers is not in the document]
Comment (BradleyWood) [reply runtime/compiler/codegen/J9CodeGenerator.cpp]: Done

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11

File: runtime/compiler/codegen/J9CodeGenerator.cpp [hunk 3]
```diff
@@ -839,6 +839,51 @@ J9::CodeGenerator::lowerTreeIfNeeded(
...
+            src = TR::Node::create(TR::aladd, 2, src, srcOffset);
+            dest = TR::Node::create(TR::aladd, 2, dest, destOffset);
+            }
+
+         TR::Node *arraycopyNode = TR::Node::createArraycopy(src, dest, len);
+         TR::TreeTop *arrayCopyTT = TR::TreeTop::create(self()->comp(), arraycopyNode, tt->getNextTreeTop(), tt->getPrevTreeTop());
+
+         tt->getPrevTreeTop()->setNextTreeTop(arrayCopyTT);
+         tt->getNextTreeTop()->setPrevTreeTop(arrayCopyTT);
+         tt->getNode()->recursivelyDecReferenceCount();
```
Comment (0xdaryl) [inline runtime/compiler/codegen/J9CodeGenerator.cpp:876]: I don't think a recursive dec reference count is what you want here.  Creating a new arraycopy node with children will add the children and increment their reference counts.  I think all you want is to decrement the reference count on each child because you are simply moving the children from one tree to another before unlinking the original tree.

Another option to look into is whether the original node could be "recreated" (via `TR::Node::recreate`).  This might be cleaner, and you wouldn't have to worry about unlinking it.

Comment (BradleyWood) [reply runtime/compiler/codegen/J9CodeGenerator.cpp:876]: > I think all you want is to decrement the reference count on each child because you are simply moving the children from one tree to another before unlinking the original tree.

Won't `recursivelyDecReferenceCount()` this decrease the reference count of the original node, and its children?

> Another option to look into is whether the original node could be "recreated" (via TR::Node::recreate)

We can't use TR::Node::recreate because the children differ from the original node, which it does not support.

Comment (0xdaryl) [reply runtime/compiler/codegen/J9CodeGenerator.cpp:876]: Unless I'm mistaken, `recursivelyDecReferenceCount()` won't just do the children, but continue to descend.  You should only have to touch the ref counts on the immediate children.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11

**Review by 0xdaryl — APPROVED** [review]
