### PR TITLE
Fall back to out-of-line call to StringUTF16.toBytes

### LINKED ISSUE #19309: OpenJDK CompactString/MaxSizeUTF16String testMaxCharArray() expects OOM but gets NegativeArraySizeException with JIT
jdk23 testing on amac. This also occurs with jdk-21.0.2+13 or jdk-17.0.10+7 on xLinux. It does not occur with jdk-17.0.9+9 so likely there is a change between 0.41 and 0.43 causing this.

```
17:09:02  openjdk version "23-internal" 2024-09-17
17:09:02  OpenJDK Runtime Environment (build 23-internal-adhoc.****.BuildJDKnextaarch64macPersonal)
17:09:02  Eclipse OpenJ9 VM (build master-b2db2045aa4, JRE 23 Mac OS X aarch64-64-Bit 20240411_113 (JIT enabled, AOT enabled)
17:09:02  OpenJ9   - b2db2045aa4
17:09:02  OMR      - 0e07ad19c1f
17:09:02  JCL      - 7ac6a9b5b39 based on jdk-23+17)
```

From a grinder on 
java/lang/String/CompactString/MaxSizeUTF16String.java
```
16:22:49  STARTED    MaxSizeUTF16String::testMaxCharArray 'testMaxCharArray()'
16:22:49  Checking max UTF16 string len: 1073741824
16:22:49  java.lang.NegativeArraySizeException: -2147483648
16:22:49  	at java.base/java.lang.String.<init>(String.java:5655)
16:22:49  	at java.base/java.lang.String.<init>(String.java:489)
16:22:49  	at MaxSizeUTF16String.testMaxCharArray(MaxSizeUTF16String.java:110)
```

This can be duplicated with the following, when running with `-Xjit:count=0`. When running without or with -Xint, the expected OOM error occurs (shown below).
```
public class MaxChar {

private final static int MAX_UTF16_STRING_LENGTH = Integer.MAX_VALUE / 2;

    private static char[] generateCharData(int size) {
        char[] nonAscii = "\u0100".toCharArray();
        char[] arr = new char[size];
        System.arraycopy(nonAscii, 0, arr, 0, nonAscii.length); // non-latin1 at start
        return arr;
    }

public static void main(String[] args) throws Throwable {
        final char[] large_char_array = generateCharData(MAX_UTF16_STRING_LENGTH + 1);
        new String(large_char_array, 0, MAX_UTF16_STRING_LENGTH + 1);
}
}
```
```
Exception in thread "main" java.lang.OutOfMemoryError: UTF16 String size is 1073741824, should be less than 1073741823
        at java.base/java.lang.StringUTF16.newBytesLength(StringUTF16.java:60)
        at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
        at java.base/java.lang.StringUTF16.toBytes(StringUTF16.java:169)
        at java.base/java.lang.StringUTF16.compress(StringUTF16.java:218)
        at java.base/java.lang.String.<init>(String.java:5646)
        at java.base/java.lang.String.<init>(String.java:489)
        at MaxChar.main(MaxChar.java:14)
```

### PR DESCRIPTION
**Pull request by hzongaro**
The implementation of `StringUTF16.toBytes` will throw a `NegativeArraySizeException` if the specified array length is negative or an `OutOfMemoryError` if the length is 2^30 or greater.  The IL for the inline implementation that the JIT compiler generates for that recognized method could throw a `NegativeArraySizeException` in situations where the actual implementation would throw an `OutOfMemoryError`.

This change calls the actual implementation if the array length is outside the range [0,0x3fffffff] to ensure that the behaviour is always as expected in exceptional situations.

Fixes #19309

### CODE REVIEW

**Comment by hzongaro** [comment]
@knn-k, may I ask you to review this change?

File: runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp [hunk 1]
```diff
@@ -275,27 +275,110 @@ void J9::RecognizedCallTransformer::process_java_lang_StringUTF16_toBytes(TR::Tr
...
+   // |     iload offTemp                      |          |
+   // |     ==>newarray                        |          |
+   // |     iconst 0                           |          |
+   // |     iload lenTemp                      |          |
+   // | goto joinBlock   ----------------------------+    |
+   // +----------------------------------------+     |    |
+   //                                                |    |
+   //                      +------------------------------+
+   //                      |                         |
+   // fallBackPathBlock    V (freq 0) (cold)         |
```
Comment (knn-k) [inline runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp:340]: Minor nitpick: "fallBack" or "fallback"?  See also line 315, and variable names at lines 403-404 and 420.

**Comment by knn-k** [comment]
I looked through the commit.  It looked OK to me, but I am not familiar with manipulation of IL trees.  I would like someone else to review.

File: runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp (hunk 1 above)
Comment (hzongaro) [reply runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp]: Thanks!  I've fixed up usage of "fallback" versus "fall back" in commit f3d338d270e56ad6adf35e79232fb53af208d08a.

Comment (hzongaro) [reply runtime/compiler/optimizer/J9RecognizedCallTransformer.cpp]: Once changes have been approved, I will squash the commit that corrects the typos.

**Comment by hzongaro** [comment]
@0xdaryl, may I ask you to review this change as well?  Once changes have been approved, I will squash the commit that corrects the typos.

**Comment by hzongaro** [comment]
@0xdaryl, may I ask you to review this change?

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk21

**Comment by 0xdaryl** [comment]
The Z JitServer failure has been seen before, and I don't think has anything to do with this PR.

No nodes are available for the Windows build.

**Review by 0xdaryl — APPROVED** [review]
