### PR TITLE
Don't return dark matter objects in DTFJ's JavaHeap.getObjects

### LINKED ISSUE #10537: DTJF/jdmpview unexpected core dump object class corruption
Java -version output
--------------------

```
$ jdmpview -core core.20200825.105225.2472.0002.dmp
[...]
	*0 : PID: 2472 : JRE 11 Windows 10 amd64-64 (build 11.0.8+10)
```

Summary of problem
------------------

Core dump taken with exclusive access using `com.ibm.jvm.Dump.triggerDump("system:request=exclusive+serial+prepwalk")` and loaded with MAT shows unexpected core dump object class corruption (from JavaHeap.getObjects); for example, with object `0x603953fa0`, jdmpview shows the same:

```
> x/j 0x603953fa0
	 heap #1 - name: Generational@18a41cc9c50

	  	  <error getting class name while traversing objects: <corrupt data encountered>> @ 0x603953fa0
	   declared fields:
Problem running command: 
com.ibm.j9ddr.view.dtfj.image.J9DDRCorruptData incompatible with com.ibm.dtfj.java.JavaField
```

Reproduced with a standalone program:

```
Reference good object: Instance of java/util/HashMap @ 0x603951fb8
Reference good object class: java/util/HashMap

Suspect object: com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaObject@3953fa6
Suspect object class: JavaClass 0x437b00 (exception reading class name)
```

Standalone program:

```
import java.io.File;
import java.util.Iterator;

import com.ibm.dtfj.image.CorruptDataException;
import com.ibm.dtfj.image.Image;
import com.ibm.dtfj.image.ImageAddressSpace;
import com.ibm.dtfj.image.ImageFactory;
import com.ibm.dtfj.image.ImageProcess;
import com.ibm.dtfj.java.JavaHeap;
import com.ibm.dtfj.java.JavaObject;
import com.ibm.dtfj.java.JavaRuntime;

public class DTFJPlay
{
    public static void main(String[] args) throws Throwable
    {
        Image image = null;
        if (args.length > 0)
        {
            Class<?> factoryClass = Class.forName("com.ibm.dtfj.image.j9.ImageFactory");
            ImageFactory factory = (ImageFactory) factoryClass.newInstance();
            image = factory.getImage(new File(args[0]));
            processImage(image);
        }
        else
        {
            System.err.println("No filename specified");
        }
    }

    private static void processImage(Image image) throws CorruptDataException
    {
        Iterator<?> itAS = image.getAddressSpaces();
        while (itAS.hasNext())
        {
            ImageAddressSpace imageAS = (ImageAddressSpace) itAS.next();
            Iterator<?> pAS = imageAS.getProcesses();
            while (pAS.hasNext())
            {
                ImageProcess imageP = (ImageProcess) pAS.next();
                Iterator<?> rAS = imageP.getRuntimes();
                while (rAS.hasNext())
                {
                    JavaRuntime runtime = (JavaRuntime) rAS.next();
                    Iterator<?> hAS = runtime.getHeaps();
                    while (hAS.hasNext())
                    {
                        JavaHeap heap = (JavaHeap) hAS.next();
                        Iterator<?> oAS = heap.getObjects();
                        while (oAS.hasNext())
                        {
                            JavaObject object = (JavaObject) oAS.next();
                            long objectAddress = object.getID().getAddress();
                            if (objectAddress == 0x603953fa0L)
                            {
                                System.out.println("Suspect object: " + object);
                                System.out.println("Suspect object class: " + object.getJavaClass());
                                return;
                            }
                            else if (objectAddress == 0x603951fb8L)
                            {
                                System.out.println("Reference good object: " + object);
                                System.out.println("Reference good object class: " + object.getJavaClass());
                                System.out.println();
                            }
                        }
                    }
                }
            }
        }
    }
}
```

The following (`requestMask = 0x000000000000000D (13)`) confirms that the core dump was taken with exclusive access (`J9RAS_DUMP_DO_EXCLUSIVE_VM_ACCESS`):

```
> !findcallsite dmpagent.c:1739
 !j9x 0x0000018A41C4E5C0,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4E680,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4E740,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4E8C0,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4EB00,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4EBC0,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4EEC0,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A41C4F040,0x0000000000000078 dmpagent.c:1739
 !j9x 0x0000018A549804C0,0x0000000000000078 dmpagent.c:1739
Call site count = 9
> !J9RASdumpAgent 0x0000018A549804C0
J9RASdumpAgent at 0x18a549804c0 {
  Fields for J9RASdumpAgent:
	0x0: class J9RASdumpAgent* nextPtr = !j9rasdumpagent 0x0000000000000000
	0x8: void* shutdownFn = !j9x 0x00007FFF283E5A20
	0x10: U64 eventMask = 0x00000000004A2000 (4857856)
	0x18: U8* detailFilter = !j9x 0x0000000000000000
	0x20: U64 startOnCount = 0x0000000000000001 (1)
	0x28: U64 stopOnCount = 0x0000000000000000 (0)
	0x30: U64 count = 0x0000000000000000 (0)
	0x38: U8* labelTemplate = !j9x 0x0000018A41C4EE00
	0x40: void* dumpFn = !j9x 0x00007FFF283E5E70
	0x48: U8* dumpOptions = !j9x 0x0000000000000000
	0x50: void* userData = !j9x 0x0000000000000000
	0x58: U64 priority = 0x00000000000003E7 (999)
	0x60: U64 requestMask = 0x000000000000000D (13)
	0x68: U64 prepState = 0x0000000000000315 (789)
	0x70: U8* subFilter = !j9x 0x0000000000000000
}
```

Diagnostic files
----------------

IBM Box core dump link: https://ibm.box.com/s/cmm1x274s1krfyrw4wp7laqy6svtgt9p

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #10537

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

### CODE REVIEW

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java [hunk 1]
```diff
@@ -57,6 +58,21 @@ public void doDeadObject(J9ObjectPointer object) {
 	}
 
 	public void doLiveObject(J9ObjectPointer ptr) {
+		try {
+			if (J9ObjectHelper.clazz(ptr).classObject().getAddress() == -1) {
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java:62]: This will not work 32-bit dumps where the all-ones pointer value would be `0xFFFFFFFFL`.
Also, this is the wrong place for this test: it belongs in `GCObjectModel_V1.isDeadObject(J9ObjectPointer)`.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java (hunk 1 above)
Comment (kgibm) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java:62]: > This will not work for 32-bit dumps

Makes sense. Do I check `J9BuildFlags.env_data64`?

> it belongs in GCObjectModel_V1.isDeadObject(J9ObjectPointer).

That's actually where I first put the patch but I encountered some very strange behavior where marking these objects as dead caused a drastic change in the number of total live objects from 1,427,358 to 113,626, whereas placing the check in `HeapObjectIterator` knocked down only the expected amount (to 1,427,353). Might there be some logic along the lines of: if we find a dead object in this section, then assume the rest of the section is dead? Anyway, I'll take a look...

Comment (keithc-ca) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java:62]: > Do I check `J9BuildFlags.env_data64`

At least indirectly, yes. I suggest adding:
```
    private static final J9ObjectPointer J9_INVALID_OBJECT = J9ObjectPointer.cast(~0L);
```
and changing the test to `J9_INVALID_OBJECT.eq(J9ObjectHelper.clazz(object).classObject())`.

Comment (kgibm) [reply debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/java/j9/HeapObjectIterator.java:62]: I think I figured out the issue: The heap iterator checks for a dead object and advances the search pointer by `ObjectModel.getSizeInBytesDeadObject` so I think I just need to add the dark matter check in `getSizeInBytesDeadObject` to instead return `ObjectModel.getConsumedSizeInBytesWithHeader`.

Thanks Dmitri, I think I'll change to `J9AccClassDying` as it's more logical.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel_V1.java [hunk 2]
```diff
@@ -170,19 +173,36 @@ public UDATA getSizeInBytesWithHeader(J9ObjectPointer object) throws CorruptData
...
 
-@Override
+	@Override
 	public boolean isDeadObject(J9ObjectPointer object) throws CorruptDataException 
 	{
-		return J9ObjectHelper.flags(object).allBitsIn(J9_GC_OBJ_HEAP_HOLE);
+		return J9ObjectHelper.flags(object).allBitsIn(J9_GC_OBJ_HEAP_HOLE) || isDarkMatter(object);
+	}
+
+	private boolean isDarkMatter(J9ObjectPointer object) throws CorruptDataException {
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel_V1.java:191]: This method can be `static`.

**Review by keithc-ca — APPROVED** [review]

**Comment by dmitripivkine** [comment]
So the naming is inherited from `jextract` `gccheck` came from time there was no concept of leaving unloaded class instance in the heap. The possibilities were "object" or "hole" ("alive" or "dead") - an alternative to well formed object (assumed "alive") was hole only. Today real "dark matter" still be well formed object so it goes to category of object handling (and "alive" as opposite of "dead" is not applicable any more). But naming still reflect this ancient concept

**Comment by kgibm** [comment]
Ok, so you think `isDeadObject` should be left as before, but `isDarkMatter` API should be exposed in `ObjectModel` and the heap walking logic can use it in addition to `isDeadObject`?

**Comment by kgibm** [comment]
Ok, I think I understand. I'll try to patch it...

**Comment by kgibm** [comment]
@dmitripivkine New commit pushed, please check again when you have a chance

**Review by dmitripivkine — APPROVED** [review]
Thank you very much for code improvement!

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk17

**Comment by dmitripivkine** [comment]
@keithc-ca This code has been changed significantly. Would you like to review it again?

**Comment by kgibm** [comment]
I think I found one issue in `HeapWalker` here:

```java
			case STATE_FINISHED :
				long address = object.getAddress();
-				if(!ObjectModel.isDeadObject(object)) {
+				if(!isDeadObject(object)) {
					address += ObjectModel.getSizeInBytesWithHeader(object).longValue();
				}
				log.fine(String.format(" end=0x%08x object count = %d\n",
						address,
						objectCount
				));
				totalObjectCount += objectCount;
				log.fine("Total object count = " + totalObjectCount);
				events.doSectionEnd(address);
				break;
```

The `address` is used as the ending address of the section which is reported in the log statement and sent to the listener with `events.doSectionEnd(address)`. The old logic would add the size of a non-hole object, but the new logic would incorrectly avoid adding the size of a non-hole, dark matter object. It seems to me both are wrong, and it should be something like the following. @dmitripivkine What do you think?

```java
				if(!ObjectModel.isHoleObject(object)) {
					address += ObjectModel.getSizeInBytesWithHeader(object).longValue();
				} else {
					address += ObjectModel.getSizeInBytesHoleObject(object).longValue();
				}
```

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel_V1.java [hunk 3]
```diff
@@ -170,21 +170,38 @@ public UDATA getSizeInBytesWithHeader(J9ObjectPointer object) throws CorruptData
...
+			if (J9ObjectHelper.clazz(object).classDepthAndFlags().anyBitsIn(J9AccClassDying)) {
+				// If an object's class's classDepthAndFlags includes J9AccClassDying,
+				// then the class has been unloaded and this object is left as dark matter
+				// for potential future clean up, so we can treat it as dead.
+				// See https://github.com/eclipse-openj9/openj9/issues/10537
+				return true;
+			}
+		} catch (CorruptDataException e) {
+			// If there was something wrong checking the object's class, then keep
+			// the old behavior in case further diagnostics can be done by the user.
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCObjectModel_V1.java:200]: This comment could be improved: since this is a new method, there is no 'old behavior'.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/walkers/HeapWalker.java [hunk 4]
```diff
@@ -133,12 +133,16 @@ public void walk() {
...
+	private static boolean isDeadObject(J9ObjectPointer object) throws CorruptDataException {
+		return ObjectModel.isHoleObject(object) || ObjectModel.isDarkMatterObject(object);
+	}
 	
 	private void doState(J9ObjectPointer object) throws CorruptDataException {
 		switch(state) {
 			case STATE_INIT : 
 				log.fine("Scanning Region @ 0x" + Long.toHexString(region.getHeapRegionDescriptorPointer().getAddress()));
-				if(!ObjectModel.isDeadObject(object)) {
+				if(!isDeadObject(object)) {
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/walkers/HeapWalker.java:145]: Formatting: space before `(` in each location where `isDeadObject()` is used.

File: debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java [hunk 5]
```diff
@@ -180,7 +180,7 @@ public int checkObjectHeap(J9ObjectPointer object, GCHeapRegionDescriptor region
 		J9ClassPointer clazz = null;
 		
 		try {
-			if(ObjectModel.isDeadObject(object)) {
+			if(ObjectModel.isHoleObject(object)) {
```
Comment (keithc-ca) [inline debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/gccheck/CheckEngine.java:183]: Formatting: space before `(` - here and on line 1111.

**Review by keithc-ca — CHANGES_REQUESTED** [review]

**Comment by dmitripivkine** [comment]
> I think I found one issue in `HeapWalker` here:
> 
> ```java
> 			case STATE_FINISHED :
> 				long address = object.getAddress();
> -				if(!ObjectModel.isDeadObject(object)) {
> +				if(!isDeadObject(object)) {
> 					address += ObjectModel.getSizeInBytesWithHeader(object).longValue();
> 				}
> 				log.fine(String.format(" end=0x%08x object count = %d\n",
> 						address,
> 						objectCount
> 				));
> 				totalObjectCount += objectCount;
> 				log.fine("Total object count = " + totalObjectCount);
> 				events.doSectionEnd(address);
> 				break;
> ```
> 
> The `address` is used as the ending address of the section which is reported in the log statement and sent to the listener with `events.doSectionEnd(address)`. The old logic would add the size of a non-hole object, but the new logic would incorrectly avoid adding the size of a non-hole, dark matter object. It seems to me both are wrong, and it should be something like the following. @dmitripivkine What do you think?
> 
> ```java
> 				if(!ObjectModel.isHoleObject(object)) {
> 					address += ObjectModel.getSizeInBytesWithHeader(object).longValue();
> 				} else {
> 					address += ObjectModel.getSizeInBytesHoleObject(object).longValue();
> 				}
> ```

Your suggestion sounds correct, however needs to be tested.
So I am looking across all states in this switch - old behaviour was dark matter object has followed "live" object path. "Dead" path use to be for holes only. With your change dark matter object is not going "live" path (and `new DTFJJavaObject()` is not going to be created - I guess this is your intention) but follow "dead" path which functionally does nothing. I think it is ok and we just need to keep current pointer in the right place. And it is exactly you are proposing to do.
Also I am wondering how more side effects this change of behaviour might cause. Ok, this is just tooling code (not run-time JVM) so it less critical if we overlooked something - it might be fixed later on

**Comment by kgibm** [comment]
> Also I am wondering how more side effects this change of behaviour might cause

Searching the code for implementors of `HeapWalkerEvents`, it looks like it's just `HeapObjectIterator` and `HeapWalker$DummyHeapWalkerEvents`, both of which do nothing in `doSectionEnd`, so it seems to be safe to change; perhaps even unnecessary, although it seems like it's worth fixing while I'm here.

**Comment by kgibm** [comment]
I think I made all the requested changes. Also squashed and pushed. Please re-review.

**Comment by kgibm** [comment]
Found some more code to clean up, and now I'm done and it's ready for re-review.

**Comment by dmitripivkine** [comment]
Would you please double check that `!gccheck objectheap` command works for cores generated for gc policies `gencon`, `balanced` and `metronome`? I don't think we have enough DDR testing coverage in the build.

**Comment by kgibm** [comment]
> Would you please double check that `!gccheck objectheap` command works for cores generated for gc policies `gencon`, `balanced` and `metronome`?

Yes, sure, I'll create some cores and check

**Comment by kgibm** [comment]
@dmitripivkine Testing `gencon` first, I saw some output in `!gccheck objectheap` that I wasn't sure what it meant, so I first reverted all my changes, re-built, and did the same with a vanilla build and I see the same thing there. Are these `class pointer is null`, `new pointer in old object without remembered bit set`, and `class pointer not in a class segment` messages expected in a vanilla JDK build?

```
$ cd openj9
$ git restore .
[...]
$ git show --summary
commit 8c1840d808785e26daf7eac6096d5c6be17f1c3e (HEAD -> master, origin/master, origin/HEAD)
Merge: cd9f62398 109bfec9b
Author: AdamBrousseau <adam.brousseau88@gmail.com>
Date:   Tue Apr 12 14:21:42 2022 -0400

    Merge pull request #14905 from keithc-ca/criu
    
    Add support for CRIU builds of jdk17-19 on x86-64_linux
$ cd ..
$ make images
[...]
$ ./build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.0.15.jdk/Contents/Home/bin/java \
    -Xgcpolicy:gencon -Xdump:system:defaults:file=vanilla_core_gencon.%Y%m%d.%H%M%S.%pid.%seq.dmp -Xdump:system:events=vmstop,request=exclusive+preempt \
    -cp /Users/kevin/git/DTFJAnalyzer/bin/ DTFJAnalyzerObjectSizes \
    ~/git/sample.daytrader8/target/liberty/wlp/usr/servers/defaultServer/core.20220411.085846.77505.0002.dmp -object 0x70032eff8
[...]
[Wed Apr 13 13:50:42 CDT 2022] count(JavaObject) = 1427358
[...]
$ ./build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.0.15.jdk/Contents/Home/bin/jdmpview -core vanilla_core*
[...]
> !gccheck objectheap
Starting GC Check
Checking HEAP...  <gc check (1): from debugger: HEAP: IObject slot 7000b3390(7000b33a0) -> 7fee0ba38: class pointer is null>
  <gc check (2): from debugger: HEAP: IObject slot 7000b3390(7000b33a4) -> 7fee0ba38: class pointer is null>
  <gc check (3): from debugger: HEAP: IObject slot 7000b3390(7000b33a8) -> 7fee0ba38: class pointer is null>
  <gc check (4): from debugger: HEAP: IObject slot 7000b3390(7000b33ac) -> 7fee0ba38: class pointer is null>
  <gc check (5): from debugger: HEAP: IObject slot 7000b3390(7000b33b0) -> 7fee0ba38: class pointer is null>
  <gc check (6): from debugger: HEAP: IObject slot 7000b3390(7000b33b4) -> 7fee0ba38: class pointer is null>
  <gc check (7): from debugger: HEAP: IObject slot 7000b3390(7000b33b8) -> 7fee0ba38: class pointer is null>
  <gc check (8): from debugger: HEAP: IObject slot 7000b3390(7000b33bc) -> 7fee0ba38: class pointer is null>
  <gc check (9): from debugger: HEAP: IObject slot 7000b3390(7000b33c0) -> 7fee0ba38: class pointer is null>
  <gc check (10): from debugger: HEAP: IObject slot 7000b3390(7000b33c4) -> 7fee0ba38: class pointer is null>
  <gc check (11): from debugger: HEAP: IObject slot 7000b3390(7000b33c8) -> 7fee0ba38: class pointer is null>
  <gc check (12): from debugger: HEAP: IObject slot 7000b3390(7000b33cc) -> 7fee0ba38: class pointer is null>
  <gc check (13): from debugger: HEAP: IObject slot 7000b3390(7000b33d0) -> 7fee0ba38: class pointer is null>
  <gc check (14): from debugger: HEAP: IObject slot 7000b3390(7000b33d4) -> 7fee0ba38: class pointer is null>
  <gc check (15): from debugger: HEAP: IObject slot 7000b3390(7000b33d8) -> 7fee0ba38: class pointer is null>
  <gc check (16): from debugger: HEAP: IObject slot 7000b3390(7000b33dc) -> 7fee0ba38: class pointer is null>
  <gc check (17): from debugger: HEAP: Object slot 7000b3810(7000b3820) -> 7fee0ca50: class pointer not in a class segment>
  <gc check (18): from debugger: HEAP: IObject slot 7000b51c0(7000b51d0) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (19): from debugger: HEAP: IObject slot 7000b51c0(7000b51d4) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (20): from debugger: HEAP: IObject slot 7000b51c0(7000b51d8) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (21): from debugger: HEAP: IObject slot 7000b51c0(7000b51dc) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (22): from debugger: HEAP: IObject slot 7000b51c0(7000b51e0) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (23): from debugger: HEAP: IObject slot 7000b51c0(7000b51e4) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (24): from debugger: HEAP: IObject slot 7000b51c0(7000b51e8) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (25): from debugger: HEAP: IObject slot 7000b51c0(7000b51ec) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (26): from debugger: HEAP: IObject slot 7000b51c0(7000b51f0) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (27): from debugger: HEAP: IObject slot 7000b51c0(7000b51f4) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (28): from debugger: HEAP: IObject slot 7000b51c0(7000b51f8) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (29): from debugger: HEAP: IObject slot 7000b51c0(7000b51fc) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (30): from debugger: HEAP: IObject slot 7000b51c0(7000b5200) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (31): from debugger: HEAP: IObject slot 7000b51c0(7000b5204) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (32): from debugger: HEAP: IObject slot 7000b51c0(7000b5208) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (33): from debugger: HEAP: IObject slot 7000b51c0(7000b520c) -> 7fee0ba58: new pointer in old object without remembered bit set>
  <gc check (34): from debugger: HEAP: IObject slot 7001002b8(7001002e4) -> 7ffc6efc0: class pointer is null>
  <gc check (35): from debugger: HEAP: IObject slot 7001002b8(7001002e8) -> 7ffc6f458: class pointer not in a class segment>
  <gc check (36): from debugger: HEAP: IObject slot 7001002b8(7001002ec) -> 7ffc6f490: class pointer not in a class segment>
  <gc check (37): from debugger: HEAP: Object slot 7001436b0(7001436b8) -> 700144100: class pointer not in a class segment>
  <gc check (38): from debugger: HEAP: Object slot 7001436b0(7001436c0) -> 700144110: class pointer not in a class segment>
  <gc check (39): from debugger: HEAP: Object slot 7001436b0(7001436d8) -> 700145120: class pointer not in a class segment>
  <gc check (40): from debugger: HEAP: Object slot 7001436b0(7001436dc) -> 700145140: class pointer not in a class segment>
  <gc check (41): from debugger: HEAP: Object slot 700143700(700143708) -> 700145160: class pointer not in a class segment>
  <gc check (42): from debugger: HEAP: Object slot 700148570(70014857c) -> 700134220: class pointer is null>
  <gc check (43): from debugger: HEAP: Object slot 700148570(700148580) -> 7001476c0: class pointer not in a class segment>
  <gc check (44): from debugger: HEAP: Object slot 700148570(700148588) -> 700147678: class pointer not in a class segment>
  <gc check (45): from debugger: HEAP: Object slot 700148570(70014858c) -> 7001476c0: class pointer not in a class segment>
  <gc check (46): from debugger: HEAP: IObject slot 700149688(7001496e0) -> 7ffc72648: class pointer not in a class segment>
  <gc check (47): from debugger: HEAP: IObject slot 700149688(7001496ec) -> 7ffc74650: class pointer not in a class segment>
  <gc check (48): from debugger: HEAP: IObject slot 7001496f8(700149750) -> 7ffc726d8: class pointer not in a class segment>
  <gc check (49): from debugger: HEAP: IObject slot 7001496f8(70014975c) -> 7ffc75220: class pointer not in a class segment>
  <gc check (50): from debugger: HEAP: Object slot 700155270(700155274) -> 700137a68: class pointer not in a class segment>
  <gc check (51): from debugger: HEAP: Object slot 700155280(700155284) -> 700137ac8: class pointer not in a class segment>
  <gc check (52): from debugger: HEAP: Object slot 700155290(700155294) -> 700137b38: class pointer not in a class segment>
  <gc check (53): from debugger: HEAP: Object slot 7001552b0(7001552b4) -> 700137bc8: class pointer not in a class segment>
  <gc check (54): from debugger: HEAP: Object slot 7001552c0(7001552c4) -> 700137c18: class pointer not in a class segment>
  <gc check (55): from debugger: HEAP: Object slot 7001552d0(7001552d4) -> 700137c78: class pointer not in a class segment>
  <gc check (56): from debugger: HEAP: Object slot 7001552e0(7001552e4) -> 700137cb8: class pointer not in a class segment>
  <gc check (57): from debugger: HEAP: Object slot 700155300(700155304) -> 700137d68: class pointer not in a class segment>
  <gc check (58): from debugger: HEAP: Object slot 700155310(700155314) -> 700137dc8: class pointer not in a class segment>
  <gc check (59): from debugger: HEAP: Object slot 700155340(700155344) -> 700137ea8: class pointer not in a class segment>
  <gc check (60): from debugger: HEAP: Object slot 700155360(700155364) -> 700137f48: class pointer not in a class segment>
  <gc check (61): from debugger: HEAP: Object slot 7001553c0(7001553c4) -> 700138048: class pointer not in a class segment>
  <gc check (62): from debugger: HEAP: Object slot 7001553e0(7001553e4) -> 7001380e8: class pointer is null>
  <gc check (63): from debugger: HEAP: Object slot 7001553f0(7001553f4) -> 700138118: class pointer not in a class segment>
  <gc check (64): from debugger: HEAP: Object slot 700ea9648(700ea9650) -> 700f0b570: class pointer is null>
  <gc check (65): from debugger: HEAP: Object slot 700eb6ff0(700eb6ff8) -> 700ffa378: class pointer is null>
  <gc check (66): from debugger: HEAP: Object slot 700eb7038(700eb7040) -> 70100bc98: class pointer is null>
  <gc check (67): from debugger: HEAP: Object slot 700eb7080(700eb7088) -> 70100c4b8: class pointer is null>
  <gc check (68): from debugger: HEAP: Object slot 700eb70c8(700eb70d0) -> 70100ccd8: class pointer is null>
  <gc check (69): from debugger: HEAP: Object slot 700f31eb0(700f31eb8) -> 700f45958: class pointer not in a class segment>
  <gc check (70): from debugger: HEAP: Object slot 700f72040(700f72048) -> 70100d4f8: class pointer not in a class segment>
  <gc check (71): from debugger: HEAP: Object slot 701376308(701376310) -> 701381d28: class pointer is null>
  <gc check (72): from debugger: HEAP: Object slot 7013841d0(7013841d8) -> 7013b6f38: class pointer is null>
  <gc check (73): from debugger: HEAP: Object slot 701384218(701384220) -> 7013c1058: class pointer not in a class segment>
  <gc check (74): from debugger: HEAP: Object slot 701384260(701384268) -> 7013d7688: class pointer not in a class segment>
  <gc check (75): from debugger: HEAP: Object slot 7013842a8(7013842b0) -> 7014c4e90: class pointer is null>
  <gc check (76): from debugger: HEAP: Object slot 70139b000(70139b008) -> 7013c8978: class pointer is null>
  <gc check (77): from debugger: HEAP: Object slot 70139fb10(70139fb18) -> 7013c0c48: class pointer is null>
  <gc check (78): from debugger: HEAP: Object slot 7013a6a98(7013a6aa0) -> 7013f4a20: class pointer not in a class segment>
  <gc check (79): from debugger: HEAP: Object slot 7013afc48(7013afc50) -> 701483c50: class pointer is null>
  <gc check (80): from debugger: HEAP: Object slot 7013b6b90(7013b6b98) -> 7015ae710: class pointer not in a class segment>
  <gc check (81): from debugger: HEAP: Object slot 7013b6c20(7013b6c28) -> 7015ccc40: class pointer not in a class segment>
  <gc check (82): from debugger: HEAP: Object slot 7013d72f0(7013d72f8) -> 701484060: class pointer is null>
  <gc check (83): from debugger: HEAP: Object slot 7013d7348(7013d7350) -> 7014a4570: class pointer is null>
  <gc check (84): from debugger: HEAP: Object slot 7013d73a0(7013d73a8) -> 7014a4980: class pointer not in a class segment>
  <gc check (85): from debugger: HEAP: Object slot 701400bf0(701400bf8) -> 7014e53a0: class pointer not in a class segment>
  <gc check (86): from debugger: HEAP: Object slot 701400c48(701400c50) -> 7014e57b0: class pointer not in a class segment>
  <gc check (87): from debugger: HEAP: Object slot 7014688e8(7014688f0) -> 701581cf0: class pointer not in a class segment>
  <gc check (88): from debugger: HEAP: Object slot 7014838a8(7014838b0) -> 7015ae300: class pointer not in a class segment>
  <gc check (89): from debugger: HEAP: Object slot 7014c4cf8(7014c4d00) -> 7015d4560: class pointer is null>
  <gc check (90): from debugger: HEAP: Object slot 701505b28(701505b30) -> 7015f9080: class pointer not in a class segment>
  <gc check (91): from debugger: HEAP: Object slot 70159f658(70159f660) -> 7016e47d0: class pointer is null>
  <gc check (92): from debugger: HEAP: Object slot 70159f6a0(70159f6a8) -> 701749c90: class pointer not in a class segment>
  <gc check (93): from debugger: HEAP: Object slot 70159f6e8(70159f6f0) -> 70174a4b0: class pointer not in a class segment>
  <gc check (94): from debugger: HEAP: Object slot 70159f730(70159f738) -> 70174acd0: class pointer is null>
  <gc check (95): from debugger: HEAP: Object slot 7015e0730(7015e0738) -> 70166bb30: class pointer not in a class segment>
  <gc check (96): from debugger: HEAP: Object slot 7015e0788(7015e0790) -> 70166c350: class pointer not in a class segment>
  <gc check (97): from debugger: HEAP: Object slot 7015f8d40(7015f8d48) -> 70165ee00: class pointer not in a class segment>
  <gc check (98): from debugger: HEAP: Object slot 7016079f8(701607a00) -> 7016a2d70: class pointer not in a class segment>
  <gc check (99): from debugger: HEAP: Object slot 701607a50(701607a58) -> 7016a3590: class pointer not in a class segment>
  <gc check (100): from debugger: HEAP: Object slot 701607aa8(701607ab0) -> 7016c3eb0: class pointer not in a class segment>
  <gc check (101): from debugger: HEAP: Object slot 70166b7f0(70166b7f8) -> 70171f660: class pointer is null>
  <gc check (102): from debugger: HEAP: Object slot 701761340(701761348) -> 7017d5de0: class pointer is null>
  <gc check (103): from debugger: HEAP: Object slot 7017bc1b0(7017bc1b8) -> 7019aa440: class pointer not in a class segment>
  <gc check (104): from debugger: HEAP: Object slot 7017bc1f8(7017bc200) -> 7019ca950: class pointer is null>
  <gc check (105): from debugger: HEAP: Object slot 7017bc240(7017bc248) -> 7019cad60: class pointer not in a class segment>
  <gc check (106): from debugger: HEAP: Object slot 7017bc288(7017bc290) -> 7019cb170: class pointer not in a class segment>
  <gc check (107): from debugger: HEAP: Object slot 7017fc868(7017fc870) -> 701935f00: class pointer not in a class segment>
  <gc check (108): from debugger: HEAP: Object slot 7019eb370(7019eb378) -> 701b37340: class pointer not in a class segment>
  <gc check (109): from debugger: HEAP: Object slot 701a70650(701a70658) -> 701c39bc0: class pointer not in a class segment>
  <gc check (110): from debugger: HEAP: Object slot 701b15ea0(701b15ea8) -> 701c8e2f0: class pointer not in a class segment>
  <gc check (111): from debugger: HEAP: Object slot 701c59d78(701c59d80) -> 701cf6b40: class pointer is null>
  <gc check (112): from debugger: HEAP: Object slot 705822b10(705822b1c) -> 7fee0bd50: new pointer in old object without remembered bit set>
  <gc check (113): from debugger: HEAP: Object slot 705822b10(705822b20) -> 7fee0be80: class pointer is null>
  <gc check (114): from debugger: HEAP: Object slot 705822b10(705822b24) -> 7fee0be98: class pointer is null>
  <gc check (115): from debugger: HEAP: Object slot 705822d30(705822d3c) -> 7fee0bf18: new pointer in old object without remembered bit set>
  <gc check (116): from debugger: HEAP: Object slot 705822d30(705822d40) -> 7fee0c120: class pointer is null>
  <gc check (117): from debugger: HEAP: Object slot 705822d30(705822d44) -> 7fee0c138: new pointer in old object without remembered bit set>
  <gc check (118): from debugger: HEAP: Object slot 705824070(70582407c) -> 7fee0ce58: class pointer not in a class segment>
  <gc check (119): from debugger: HEAP: Object slot 705824070(705824080) -> 7fee0cf60: class pointer is null>
  <gc check (120): from debugger: HEAP: Object slot 705824070(705824084) -> 7fee0cf78: new pointer in old object without remembered bit set>
  <gc check (121): from debugger: HEAP: IObject slot 70582bfb0(70582bfc0) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (122): from debugger: HEAP: IObject slot 70582bfb0(70582bfc4) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (123): from debugger: HEAP: IObject slot 70582bfb0(70582bfc8) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (124): from debugger: HEAP: IObject slot 70582bfb0(70582bfcc) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (125): from debugger: HEAP: IObject slot 70582bfb0(70582bfd0) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (126): from debugger: HEAP: IObject slot 70582bfb0(70582bfd4) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (127): from debugger: HEAP: IObject slot 70582bfb0(70582bfd8) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (128): from debugger: HEAP: IObject slot 70582bfb0(70582bfdc) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (129): from debugger: HEAP: IObject slot 70582bfb0(70582bfe0) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (130): from debugger: HEAP: IObject slot 70582bfb0(70582bfe4) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (131): from debugger: HEAP: IObject slot 70582bfb0(70582bfe8) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (132): from debugger: HEAP: IObject slot 70582bfb0(70582bfec) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (133): from debugger: HEAP: IObject slot 70582bfb0(70582bff0) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (134): from debugger: HEAP: IObject slot 70582bfb0(70582bff4) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (135): from debugger: HEAP: IObject slot 70582bfb0(70582bff8) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (136): from debugger: HEAP: IObject slot 70582bfb0(70582bffc) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (137): from debugger: HEAP: IObject slot 70582bfb0(70582c000) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (138): from debugger: HEAP: IObject slot 70582bfb0(70582c004) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (139): from debugger: HEAP: IObject slot 70582bfb0(70582c008) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (140): from debugger: HEAP: IObject slot 70582bfb0(70582c00c) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (141): from debugger: HEAP: IObject slot 70582bfb0(70582c010) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (142): from debugger: HEAP: IObject slot 70582bfb0(70582c014) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (143): from debugger: HEAP: IObject slot 70582bfb0(70582c018) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (144): from debugger: HEAP: IObject slot 70582bfb0(70582c01c) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (145): from debugger: HEAP: IObject slot 70582bfb0(70582c020) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (146): from debugger: HEAP: IObject slot 70582bfb0(70582c024) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (147): from debugger: HEAP: IObject slot 70582bfb0(70582c028) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (148): from debugger: HEAP: IObject slot 70582bfb0(70582c02c) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (149): from debugger: HEAP: IObject slot 70582bfb0(70582c030) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (150): from debugger: HEAP: IObject slot 70582bfb0(70582c034) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (151): from debugger: HEAP: IObject slot 70582bfb0(70582c038) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (152): from debugger: HEAP: IObject slot 70582bfb0(70582c03c) -> 7fee71dc8: new pointer in old object without remembered bit set>
  <gc check (153): from debugger: HEAP: Object slot 70582c888(70582c8a0) -> 7fee0bc00: class pointer is null>
done (17363 ms).
Done (17375ms)
```

Running with my changes showed similar output:

```
[...]
$ ./build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.0.15.jdk/Contents/Home/bin/java \
    -Xgcpolicy:gencon -Xdump:system:defaults:file=patched_core_gencon.%Y%m%d.%H%M%S.%pid.%seq.dmp -Xdump:system:events=vmstop,request=exclusive+preempt \
    -cp /Users/kevin/git/DTFJAnalyzer/bin/ DTFJAnalyzerObjectSizes \
    ~/git/sample.daytrader8/target/liberty/wlp/usr/servers/defaultServer/core.20220411.085846.77505.0002.dmp -object 0x70032eff8
[...]
[Wed Apr 13 13:50:42 CDT 2022] count(JavaObject) = 1427353
[...]
$ ./build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.0.15.jdk/Contents/Home/bin/jdmpview -core patched_core*
[...]
> !gccheck objectheap
Starting GC Check
Checking HEAP...  <gc check (1): from debugger: HEAP: Object slot 70012d7a8(70012d7b0) -> 70012d918: class pointer not in a class segment>
  <gc check (2): from debugger: HEAP: Object slot 70012d7a8(70012d7b8) -> 70012d928: class pointer not in a class segment>
  <gc check (3): from debugger: HEAP: Object slot 70012d7a8(70012d7d0) -> 70012e938: class pointer not in a class segment>
  <gc check (4): from debugger: HEAP: IObject slot 700157098(7001570a8) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (5): from debugger: HEAP: IObject slot 700157098(7001570ac) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (6): from debugger: HEAP: IObject slot 700157098(7001570b0) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (7): from debugger: HEAP: IObject slot 700157098(7001570b4) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (8): from debugger: HEAP: IObject slot 700157098(7001570b8) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (9): from debugger: HEAP: IObject slot 700157098(7001570bc) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (10): from debugger: HEAP: IObject slot 700157098(7001570c0) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (11): from debugger: HEAP: IObject slot 700157098(7001570c4) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (12): from debugger: HEAP: IObject slot 700157098(7001570c8) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (13): from debugger: HEAP: IObject slot 700157098(7001570cc) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (14): from debugger: HEAP: IObject slot 700157098(7001570d0) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (15): from debugger: HEAP: IObject slot 700157098(7001570d4) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (16): from debugger: HEAP: IObject slot 700157098(7001570d8) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (17): from debugger: HEAP: IObject slot 700157098(7001570dc) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (18): from debugger: HEAP: IObject slot 700157098(7001570e0) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (19): from debugger: HEAP: IObject slot 700157098(7001570e4) -> 7ff494b50: new pointer in old object without remembered bit set>
  <gc check (20): from debugger: HEAP: IObject slot 70016d7d8(70016d7e8) -> 7ff494b70: class pointer not in a class segment>
  <gc check (21): from debugger: HEAP: IObject slot 70016d7d8(70016d7ec) -> 7ff494b70: class pointer not in a class segment>
  <gc check (22): from debugger: HEAP: IObject slot 70016d7d8(70016d7f0) -> 7ff494b70: class pointer not in a class segment>
  <gc check (23): from debugger: HEAP: IObject slot 70016d7d8(70016d7f4) -> 7ff494b70: class pointer not in a class segment>
  <gc check (24): from debugger: HEAP: IObject slot 70016d7d8(70016d7f8) -> 7ff494b70: class pointer not in a class segment>
  <gc check (25): from debugger: HEAP: IObject slot 70016d7d8(70016d7fc) -> 7ff494b70: class pointer not in a class segment>
  <gc check (26): from debugger: HEAP: IObject slot 70016d7d8(70016d800) -> 7ff494b70: class pointer not in a class segment>
  <gc check (27): from debugger: HEAP: IObject slot 70016d7d8(70016d804) -> 7ff494b70: class pointer not in a class segment>
  <gc check (28): from debugger: HEAP: IObject slot 70016d7d8(70016d808) -> 7ff494b70: class pointer not in a class segment>
  <gc check (29): from debugger: HEAP: IObject slot 70016d7d8(70016d80c) -> 7ff494b70: class pointer not in a class segment>
  <gc check (30): from debugger: HEAP: IObject slot 70016d7d8(70016d810) -> 7ff494b70: class pointer not in a class segment>
  <gc check (31): from debugger: HEAP: IObject slot 70016d7d8(70016d814) -> 7ff494b70: class pointer not in a class segment>
  <gc check (32): from debugger: HEAP: IObject slot 70016d7d8(70016d818) -> 7ff494b70: class pointer not in a class segment>
  <gc check (33): from debugger: HEAP: IObject slot 70016d7d8(70016d81c) -> 7ff494b70: class pointer not in a class segment>
  <gc check (34): from debugger: HEAP: IObject slot 70016d7d8(70016d820) -> 7ff494b70: class pointer not in a class segment>
  <gc check (35): from debugger: HEAP: IObject slot 70016d7d8(70016d824) -> 7ff494b70: class pointer not in a class segment>
  <gc check (36): from debugger: HEAP: Object slot 70018d698(70018d69c) -> 70018fc08: class pointer not in a class segment>
  <gc check (37): from debugger: HEAP: Object slot 70018d6d0(70018d6d4) -> 70018fce8: class pointer not in a class segment>
  <gc check (38): from debugger: HEAP: Object slot 70018d740(70018d744) -> 70018fe68: class pointer not in a class segment>
  <gc check (39): from debugger: HEAP: Object slot 70018d758(70018d75c) -> 70018fe78: class pointer not in a class segment>
  <gc check (40): from debugger: HEAP: Object slot 70018d788(70018d78c) -> 70018ff88: class pointer not in a class segment>
  <gc check (41): from debugger: HEAP: Object slot 70018d798(70018d79c) -> 70018ffd8: class pointer not in a class segment>
  <gc check (42): from debugger: HEAP: Object slot 70018d7b8(70018d7bc) -> 700190088: class pointer not in a class segment>
  <gc check (43): from debugger: HEAP: Object slot 70018d7c8(70018d7cc) -> 7001900c8: class pointer not in a class segment>
  <gc check (44): from debugger: HEAP: Object slot 70018d7d8(70018d7dc) -> 700190118: class pointer not in a class segment>
  <gc check (45): from debugger: HEAP: Object slot 70018d7f8(70018d7fc) -> 7001901a8: class pointer is null>
  <gc check (46): from debugger: HEAP: Object slot 70018d808(70018d80c) -> 700190238: class pointer not in a class segment>
  <gc check (47): from debugger: HEAP: Object slot 70018d848(70018d84c) -> 7001903c8: class pointer not in a class segment>
  <gc check (48): from debugger: HEAP: Object slot 7010ea7f8(7010ea800) -> 701113d30: class pointer is null>
  <gc check (49): from debugger: HEAP: Object slot 7010ea840(7010ea848) -> 701114140: class pointer is null>
  <gc check (50): from debugger: HEAP: Object slot 7010ea888(7010ea890) -> 701114550: class pointer is null>
  <gc check (51): from debugger: HEAP: Object slot 7010ea8d0(7010ea8d8) -> 701114d70: class pointer is null>
  <gc check (52): from debugger: HEAP: Object slot 7010fb560(7010fb568) -> 701114960: class pointer is null>
  <gc check (53): from debugger: HEAP: Object slot 70112d8a8(70112d8b0) -> 7011956a0: class pointer is null>
  <gc check (54): from debugger: HEAP: Object slot 701238150(701238158) -> 70131f390: class pointer is null>
  <gc check (55): from debugger: HEAP: Object slot 701238198(7012381a0) -> 70131fbb0: class pointer is null>
  <gc check (56): from debugger: HEAP: Object slot 7013056b0(7013056b8) -> 7014f5d90: class pointer not in a class segment>
  <gc check (57): from debugger: HEAP: Object slot 701783c60(701783c68) -> 7018a65c8: class pointer not in a class segment>
  <gc check (58): from debugger: HEAP: Object slot 701889c10(701889c18) -> 70192f128: class pointer is null>
  <gc check (59): from debugger: HEAP: Object slot 705da5528(705da5540) -> 7ff4949d8: class pointer is null>
  <gc check (60): from debugger: HEAP: IObject slot 705da5e38(705da5e48) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (61): from debugger: HEAP: IObject slot 705da5e38(705da5e4c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (62): from debugger: HEAP: IObject slot 705da5e38(705da5e50) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (63): from debugger: HEAP: IObject slot 705da5e38(705da5e54) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (64): from debugger: HEAP: IObject slot 705da5e38(705da5e58) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (65): from debugger: HEAP: IObject slot 705da5e38(705da5e5c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (66): from debugger: HEAP: IObject slot 705da5e38(705da5e60) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (67): from debugger: HEAP: IObject slot 705da5e38(705da5e64) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (68): from debugger: HEAP: IObject slot 705da5e38(705da5e68) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (69): from debugger: HEAP: IObject slot 705da5e38(705da5e6c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (70): from debugger: HEAP: IObject slot 705da5e38(705da5e70) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (71): from debugger: HEAP: IObject slot 705da5e38(705da5e74) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (72): from debugger: HEAP: IObject slot 705da5e38(705da5e78) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (73): from debugger: HEAP: IObject slot 705da5e38(705da5e7c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (74): from debugger: HEAP: IObject slot 705da5e38(705da5e80) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (75): from debugger: HEAP: IObject slot 705da5e38(705da5e84) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (76): from debugger: HEAP: IObject slot 705da5e38(705da5e88) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (77): from debugger: HEAP: IObject slot 705da5e38(705da5e8c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (78): from debugger: HEAP: IObject slot 705da5e38(705da5e90) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (79): from debugger: HEAP: IObject slot 705da5e38(705da5e94) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (80): from debugger: HEAP: IObject slot 705da5e38(705da5e98) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (81): from debugger: HEAP: IObject slot 705da5e38(705da5e9c) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (82): from debugger: HEAP: IObject slot 705da5e38(705da5ea0) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (83): from debugger: HEAP: IObject slot 705da5e38(705da5ea4) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (84): from debugger: HEAP: IObject slot 705da5e38(705da5ea8) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (85): from debugger: HEAP: IObject slot 705da5e38(705da5eac) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (86): from debugger: HEAP: IObject slot 705da5e38(705da5eb0) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (87): from debugger: HEAP: IObject slot 705da5e38(705da5eb4) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (88): from debugger: HEAP: IObject slot 705da5e38(705da5eb8) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (89): from debugger: HEAP: IObject slot 705da5e38(705da5ebc) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (90): from debugger: HEAP: IObject slot 705da5e38(705da5ec0) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (91): from debugger: HEAP: IObject slot 705da5e38(705da5ec4) -> 7ff4b1ef8: new pointer in old object without remembered bit set>
  <gc check (92): from debugger: HEAP: Object slot 705f5c2b8(705f5c2c4) -> 7ff494c68: new pointer in old object without remembered bit set>
  <gc check (93): from debugger: HEAP: Object slot 705f5c2b8(705f5c2c8) -> 7ff494d98: class pointer is null>
  <gc check (94): from debugger: HEAP: Object slot 705f5c2b8(705f5c2cc) -> 7ff494db0: class pointer is null>
  <gc check (95): from debugger: HEAP: Object slot 705f5c4d8(705f5c4e4) -> 7ff494e30: new pointer in old object without remembered bit set>
  <gc check (96): from debugger: HEAP: Object slot 705f5c4d8(705f5c4e8) -> 7ff495038: class pointer is null>
  <gc check (97): from debugger: HEAP: Object slot 705f5c4d8(705f5c4ec) -> 7ff495050: class pointer not in a class segment>
  <gc check (98): from debugger: HEAP: Object slot 705f5d818(705f5d824) -> 7ff495db0: class pointer is null>
  <gc check (99): from debugger: HEAP: Object slot 705f5d818(705f5d828) -> 7ff495eb8: class pointer is null>
  <gc check (100): from debugger: HEAP: Object slot 705f5d818(705f5d82c) -> 7ff495ed0: class pointer not in a class segment>
done (18446 ms).
Done (18459ms)
```

**Comment by dmitripivkine** [comment]
Yes, these messages are expected (well, unavoidable really). The triggering of these messages caused by discovering of dark matter in the heap. You are fixing case where dark matter can be recognized if correspondent RAM class is unloaded, but it is only tip of the iceberg. There are many other dead objects instances of loaded classes in the heap. And if object is not alive (dead) GC is not updating it any more. So pointers in dead objects become stall and trigger these false messages. It is unavoidable in the current DDR model where we have no reliable way to recognize dark matter.

An ultimate solution for DDR might be traversing graph alive objects from the roots similarly GC does run time and creating valid mark map by DDR itself. We investigated this way in the past but did not conclude with solution.

**Comment by kgibm** [comment]
> Yes, these messages are expected (well, unavoidable really)

Ok, makes sense.

I ran the same test with `balanced` and the results were cleaner:

```
> !gccheck objectheap
Starting GC Check
Checking HEAP...done (23201 ms).
Done (23212ms)
```

I'm on macOS, so I can't test `metronome`. I'll also be out the rest of this week but I'll try to find a Linux box next week to test `metronome`.

**Comment by dmitripivkine** [comment]
> I ran the same test with balanced and the results were cleaner

Yes, `Balanced` maintains two Mark Maps ("current" and "new") so we have better information in hands.

**Comment by kgibm** [comment]
> There are many other dead objects instances of loaded classes in the heap

Out of curiosity, what are these other cases? Is it something to add checks for in `isDarkMatterObject`?

**Comment by dmitripivkine** [comment]
> > There are many other dead objects instances of loaded classes in the heap
> 
> Out of curiosity, what are these other cases? Is it something to add checks for in `isDarkMatterObject` or is the only option creating a mark map?

In general current DDR can not recognize "alive" and "dead" objects in the heap. In order to do this DDR should have notion of current reachability to the object. And it can be done by traversing current object graph. Without this "alive" and "dead" objects looks identical.

**Comment by kgibm** [comment]
> And it can be done by traversing current object graph. Without this "alive" and "dead" objects looks identical.

I'm guessing this means that there's no way the GC could be enhanced to add a flag like `DARK_MATTER` to dark matter object bitflags since an object is not consciously decided to be dark matter but is instead determined to be dark matter when the GC marks live refs from roots.

**Comment by dmitripivkine** [comment]
> > And it can be done by traversing current object graph. Without this "alive" and "dead" objects looks identical.
> 
> I'm guessing this means that there's no way the GC could be enhanced to add a flag like `DARK_MATTER` to dark matter object bitflags since an object is not consciously decided to be dark matter but is instead determined to be dark matter when the GC marks live refs from roots.

Correct. GC can not waste resources to do something with dead objects. Building internal DDR Mark Map however it doable, it just mimic STW GC Mark logic. I experimented with this many years ago and main problem was required time. And current DDR can not benefit from multithreaded processing due memory reading from core DTFJ supports single treading only.

**Comment by kgibm** [comment]
@dmitripivkine Built on Linux and tested metronome and the result was similar to `gencon` in that both the vanilla and patched builds had similar output in `!gccheck objectheap` including the messages `hole next is not a hole`, `class pointer is null`, and `class pointer not in a class segment`. Is it okay to move forward with the patch?

Here is the vanilla build without the patch (as confirmed by the DTFJ program finding 1427358 objects):

<details>
<summary>Non-patched build output</summary>

```
[Mon Apr 18 11:52:57 CDT 2022] count(JavaObject) = 1427358
[...]
> !gccheck objectheap
Starting GC Check
Checking HEAP...  <gc check (1): from debugger: HEAP: Object83c90f30: hole next is not a hole>
  <gc check (1): Hole 83c90f30 header: 83C90E71 00000000 00000030 00000000>
  <gc check (2): from debugger: HEAP: Object83c94020: hole next is not a hole>
  <gc check (2): Hole 83c94020 header: 83C93F91 00000000 00000030 00000000>
  <gc check (3): from debugger: HEAP: Object83c94230: hole next is not a hole>
  <gc check (3): Hole 83c94230 header: 83C94081 00000000 00000030 00000000>
  <gc check (4): from debugger: HEAP: Object83c94890: hole next is not a hole>
  <gc check (4): Hole 83c94890 header: 83C946B1 00000000 00000030 00000000>
  <gc check (5): from debugger: HEAP: Object83c95b50: hole next is not a hole>
  <gc check (5): Hole 83c95b50 header: 83C95AC1 00000000 00000030 00000000>
  <gc check (6): from debugger: HEAP: Object83c965a0: hole next is not a hole>
  <gc check (6): Hole 83c965a0 header: 83C964B1 00000000 00000030 00000000>
  <gc check (7): from debugger: HEAP: Object83c96e40: hole next is not a hole>
  <gc check (7): Hole 83c96e40 header: 83C96D81 00000000 00000030 00000000>
  <gc check (8): from debugger: HEAP: Object83c96f30: hole next is not a hole>
  <gc check (8): Hole 83c96f30 header: 83C96EA1 00000000 00000030 00000000>
  <gc check (9): from debugger: HEAP: Object83c9a9e0: hole next is not a hole>
  <gc check (9): Hole 83c9a9e0 header: 83C9A891 00000000 00000030 00000000>
  <gc check (10): from debugger: HEAP: Object83c9b3d0: hole next is not a hole>
  <gc check (10): Hole 83c9b3d0 header: 83C9B1F1 00000000 00000030 00000000>
  <gc check (11): from debugger: HEAP: Object83c9c1e0: hole next is not a hole>
  <gc check (11): Hole 83c9c1e0 header: 83C9C061 00000000 00000030 00000000>
  <gc check (12): from debugger: HEAP: Object83c9cc90: hole next is not a hole>
  <gc check (12): Hole 83c9cc90 header: 83C9CBA1 00000000 00000030 00000000>
  <gc check (13): from debugger: HEAP: Object8fa0d020: hole next is not a hole>
  <gc check (13): Hole 8fa0d020 header: 8FA0CFC1 00000000 00000020 00000000>
  <gc check (14): from debugger: HEAP: Object8fa0d2a0: hole next is not a hole>
  <gc check (14): Hole 8fa0d2a0 header: 8FA0D1A1 00000000 00000020 00000000>
  <gc check (15): from debugger: HEAP: Object8fa0d4a0: hole next is not a hole>
  <gc check (15): Hole 8fa0d4a0 header: 8FA0D401 00000000 00000020 00000000>
  <gc check (16): from debugger: HEAP: Object8fa0d6a0: hole next is not a hole>
  <gc check (16): Hole 8fa0d6a0 header: 8FA0D641 00000000 00000020 00000000>
  <gc check (17): from debugger: HEAP: Object8fa0e5a0: hole next is not a hole>
  <gc check (17): Hole 8fa0e5a0 header: 8FA0E401 00000000 00000020 00000000>
  <gc check (18): from debugger: HEAP: Object8fa0e6e0: hole next is not a hole>
  <gc check (18): Hole 8fa0e6e0 header: 8FA0E601 00000000 00000020 00000000>
  <gc check (19): from debugger: HEAP: Object8fa0e820: hole next is not a hole>
  <gc check (19): Hole 8fa0e820 header: 8FA0E7A1 00000000 00000020 00000000>
  <gc check (20): from debugger: HEAP: Object9011feb0: hole next is not a hole>
  <gc check (20): Hole 9011feb0 header: 9011FE11 00000000 00000028 00000000>
  <gc check (21): from debugger: HEAP: Object901c5c40: hole next is not a hole>
  <gc check (21): Hole 901c5c40 header: 901C5B21 00000000 00000030 00000000>
  <gc check (22): from debugger: HEAP: Object901c5e80: hole next is not a hole>
  <gc check (22): Hole 901c5e80 header: 901C5DF1 00000000 00000030 00000000>
  <gc check (23): from debugger: HEAP: Object901c61b0: hole next is not a hole>
  <gc check (23): Hole 901c61b0 header: 901C6031 00000000 00000030 00000000>
  <gc check (24): from debugger: HEAP: Object901c6c30: hole next is not a hole>
  <gc check (24): Hole 901c6c30 header: 901C6BA1 00000000 00000030 00000000>
  <gc check (25): from debugger: HEAP: Object901c7920: hole next is not a hole>
  <gc check (25): Hole 901c7920 header: 901C76E1 00000000 00000030 00000000>
  <gc check (26): from debugger: HEAP: Object901c7bf0: hole next is not a hole>
  <gc check (26): Hole 901c7bf0 header: 901C7A71 00000000 00000030 00000000>
  <gc check (27): from debugger: HEAP: Object901c7e00: hole next is not a hole>
  <gc check (27): Hole 901c7e00 header: 901C7C51 00000000 00000030 00000000>
  <gc check (28): from debugger: HEAP: Object901c8010: hole next is not a hole>
  <gc check (28): Hole 901c8010 header: 901C7F81 00000000 00000030 00000000>
  <gc check (29): from debugger: HEAP: Object901c8b50: hole next is not a hole>
  <gc check (29): Hole 901c8b50 header: 901C8A61 00000000 00000030 00000000>
  <gc check (30): from debugger: HEAP: Object901c8d90: hole next is not a hole>
  <gc check (30): Hole 901c8d90 header: 901C8CA1 00000000 00000030 00000000>
  <gc check (31): from debugger: HEAP: Object901c9b10: hole next is not a hole>
  <gc check (31): Hole 901c9b10 header: 901C95D1 00000000 00000030 00000000>
  <gc check (32): from debugger: HEAP: Object901c9e70: hole next is not a hole>
  <gc check (32): Hole 901c9e70 header: 901C9B71 00000000 00000030 00000000>
  <gc check (33): from debugger: HEAP: Object901ca230: hole next is not a hole>
  <gc check (33): Hole 901ca230 header: 901CA0E1 00000000 00000030 00000000>
  <gc check (34): from debugger: HEAP: Object901ca4d0: hole next is not a hole>
  <gc check (34): Hole 901ca4d0 header: 901CA291 00000000 00000030 00000000>
  <gc check (35): from debugger: HEAP: Object901cb0a0: hole next is not a hole>
  <gc check (35): Hole 901cb0a0 header: 901CAEF1 00000000 00000030 00000000>
  <gc check (36): from debugger: HEAP: Object901cb280: hole next is not a hole>
  <gc check (36): Hole 901cb280 header: 901CB101 00000000 00000030 00000000>
  <gc check (37): from debugger: HEAP: Object901cc4e0: hole next is not a hole>
  <gc check (37): Hole 901cc4e0 header: 901CC421 00000000 00000030 00000000>
  <gc check (38): from debugger: HEAP: Object901cc870: hole next is not a hole>
  <gc check (38): Hole 901cc870 header: 901CC721 00000000 00000030 00000000>
  <gc check (39): from debugger: HEAP: Object901ccc30: hole next is not a hole>
  <gc check (39): Hole 901ccc30 header: 901CC8D1 00000000 00000030 00000000>
  <gc check (40): from debugger: HEAP: Object901cd230: hole next is not a hole>
  <gc check (40): Hole 901cd230 header: 901CCF91 00000000 00000030 00000000>
  <gc check (41): from debugger: HEAP: Object901cd4a0: hole next is not a hole>
  <gc check (41): Hole 901cd4a0 header: 901CD3E1 00000000 00000030 00000000>
  <gc check (42): from debugger: HEAP: Object901cd680: hole next is not a hole>
  <gc check (42): Hole 901cd680 header: 901CD501 00000000 00000030 00000000>
  <gc check (43): from debugger: HEAP: Object901ce0d0: hole next is not a hole>
  <gc check (43): Hole 901ce0d0 header: 901CDF51 00000000 00000030 00000000>
  <gc check (44): from debugger: HEAP: Object901cea30: hole next is not a hole>
  <gc check (44): Hole 901cea30 header: 901CE701 00000000 00000030 00000000>
  <gc check (45): from debugger: HEAP: Object901ced00: hole next is not a hole>
  <gc check (45): Hole 901ced00 header: 901CEB81 00000000 00000030 00000000>
  <gc check (46): from debugger: HEAP: Object901cee20: hole next is not a hole>
  <gc check (46): Hole 901cee20 header: 901CED61 00000000 00000030 00000000>
  <gc check (47): from debugger: HEAP: Object901cefa0: hole next is not a hole>
  <gc check (47): Hole 901cefa0 header: 901CEEE1 00000000 00000030 00000000>
  <gc check (48): from debugger: HEAP: Object901cf180: hole next is not a hole>
  <gc check (48): Hole 901cf180 header: 901CF001 00000000 00000030 00000000>
  <gc check (49): from debugger: HEAP: Object901cf750: hole next is not a hole>
  <gc check (49): Hole 901cf750 header: 901CF691 00000000 00000030 00000000>
  <gc check (50): from debugger: HEAP: Object901cffc0: hole next is not a hole>
  <gc check (50): Hole 901cffc0 header: 901CFCC1 00000000 00000030 00000000>
  <gc check (51): from debugger: HEAP: Object slot 901f81d8(901f81e4) -> 9c5c0000: class pointer is null>
  <gc check (52): from debugger: HEAP: Object slot 9024d390(9024d398) -> 9592b800: class pointer not in a class segment>
  <gc check (53): from debugger: HEAP: Object slot 90284808(90284810) -> abea5ce0: class pointer not in a class segment>
  <gc check (54): from debugger: HEAP: Object90451ce0: hole next is not a hole>
  <gc check (54): Hole 90451ce0 header: 90451AC1 00000000 00000020 00000000>
  <gc check (55): from debugger: HEAP: Object90451e60: hole next is not a hole>
  <gc check (55): Hole 90451e60 header: 90451DC1 00000000 00000020 00000000>
  <gc check (56): from debugger: HEAP: Object90455940: hole next is not a hole>
  <gc check (56): Hole 90455940 header: 904555A1 00000000 00000020 00000000>
  <gc check (57): from debugger: HEAP: Object904581c0: hole next is not a hole>
  <gc check (57): Hole 904581c0 header: 90458121 00000000 00000020 00000000>
  <gc check (58): from debugger: HEAP: Object90458360: hole next is not a hole>
  <gc check (58): Hole 90458360 header: 90458281 00000000 00000020 00000000>
  <gc check (59): from debugger: HEAP: Object904588c0: hole next is not a hole>
  <gc check (59): Hole 904588c0 header: 90458521 00000000 00000020 00000000>
  <gc check (60): from debugger: HEAP: Object90458bc0: hole next is not a hole>
  <gc check (60): Hole 90458bc0 header: 90458B61 00000000 00000020 00000000>
  <gc check (61): from debugger: HEAP: Object9045e0e0: hole next is not a hole>
  <gc check (61): Hole 9045e0e0 header: 9045D961 00000000 00000020 00000000>
  <gc check (62): from debugger: HEAP: Object90512bc0: hole next is not a hole>
  <gc check (62): Hole 90512bc0 header: 90511B01 00000000 00000020 00000000>
  <gc check (63): from debugger: HEAP: Object90514bc0: hole next is not a hole>
  <gc check (63): Hole 90514bc0 header: 90513E41 00000000 00000020 00000000>
  <gc check (64): from debugger: HEAP: Object90515460: hole next is not a hole>
  <gc check (64): Hole 90515460 header: 905153C1 00000000 00000020 00000000>
  <gc check (65): from debugger: HEAP: Object90516360: hole next is not a hole>
  <gc check (65): Hole 90516360 header: 90515541 00000000 00000020 00000000>
  <gc check (66): from debugger: HEAP: Object90517280: hole next is not a hole>
  <gc check (66): Hole 90517280 header: 90516A21 00000000 00000020 00000000>
  <gc check (67): from debugger: HEAP: Object905187a0: hole next is not a hole>
  <gc check (67): Hole 905187a0 header: 90517EE1 00000000 00000020 00000000>
  <gc check (68): from debugger: HEAP: Object90519400: hole next is not a hole>
  <gc check (68): Hole 90519400 header: 90518CA1 00000000 00000020 00000000>
  <gc check (69): from debugger: HEAP: Object9051b100: hole next is not a hole>
  <gc check (69): Hole 9051b100 header: 9051AD01 00000000 00000020 00000000>
  <gc check (70): from debugger: HEAP: Object9051bc40: hole next is not a hole>
  <gc check (70): Hole 9051bc40 header: 9051B921 00000000 00000020 00000000>
  <gc check (71): from debugger: HEAP: Object9051c180: hole next is not a hole>
  <gc check (71): Hole 9051c180 header: 9051BD21 00000000 00000020 00000000>
  <gc check (72): from debugger: HEAP: Object9051c900: hole next is not a hole>
  <gc check (72): Hole 9051c900 header: 9051C461 00000000 00000020 00000000>
  <gc check (73): from debugger: HEAP: Object9051ca20: hole next is not a hole>
  <gc check (73): Hole 9051ca20 header: 9051C981 00000000 00000020 00000000>
  <gc check (74): from debugger: HEAP: Object905c03c0: hole next is not a hole>
  <gc check (74): Hole 905c03c0 header: 905C0321 00000000 00000028 00000000>
  <gc check (75): from debugger: HEAP: Object905c0b68: hole next is not a hole>
  <gc check (75): Hole 905c0b68 header: 905C0AC9 00000000 00000028 00000000>
  <gc check (76): from debugger: HEAP: Object905c0c58: hole next is not a hole>
  <gc check (76): Hole 905c0c58 header: 905C0BB9 00000000 00000028 00000000>
  <gc check (77): from debugger: HEAP: Object905c1158: hole next is not a hole>
  <gc check (77): Hole 905c1158 header: 905C10B9 00000000 00000028 00000000>
  <gc check (78): from debugger: HEAP: Object905c12e8: hole next is not a hole>
  <gc check (78): Hole 905c12e8 header: 905C1271 00000000 00000028 00000000>
  <gc check (79): from debugger: HEAP: Object905c14c8: hole next is not a hole>
  <gc check (79): Hole 905c14c8 header: 905C1429 00000000 00000028 00000000>
  <gc check (80): from debugger: HEAP: Object905c1770: hole next is not a hole>
  <gc check (80): Hole 905c1770 header: 905C16D1 00000000 00000028 00000000>
  <gc check (81): from debugger: HEAP: Object905c18b0: hole next is not a hole>
  <gc check (81): Hole 905c18b0 header: 905C17C1 00000000 00000028 00000000>
  <gc check (82): from debugger: HEAP: Object905c1978: hole next is not a hole>
  <gc check (82): Hole 905c1978 header: 905C1901 00000000 00000028 00000000>
  <gc check (83): from debugger: HEAP: Object905c1c98: hole next is not a hole>
  <gc check (83): Hole 905c1c98 header: 905C1C21 00000000 00000028 00000000>
  <gc check (84): from debugger: HEAP: Object905c1ef0: hole next is not a hole>
  <gc check (84): Hole 905c1ef0 header: 905C1E51 00000000 00000028 00000000>
  <gc check (85): from debugger: HEAP: Object905c2238: hole next is not a hole>
  <gc check (85): Hole 905c2238 header: 905C2149 00000000 00000028 00000000>
  <gc check (86): from debugger: HEAP: Object905c23f0: hole next is not a hole>
  <gc check (86): Hole 905c23f0 header: 905C2301 00000000 00000028 00000000>
  <gc check (87): from debugger: HEAP: Object905c26e8: hole next is not a hole>
  <gc check (87): Hole 905c26e8 header: 905C2649 00000000 00000028 00000000>
  <gc check (88): from debugger: HEAP: Object905c2828: hole next is not a hole>
  <gc check (88): Hole 905c2828 header: 905C2761 00000000 00000028 00000000>
  <gc check (89): from debugger: HEAP: Object905c2918: hole next is not a hole>
  <gc check (89): Hole 905c2918 header: 905C2879 00000000 00000028 00000000>
  <gc check (90): from debugger: HEAP: Object905c2ad0: hole next is not a hole>
  <gc check (90): Hole 905c2ad0 header: 905C2A31 00000000 00000028 00000000>
  <gc check (91): from debugger: HEAP: Object905c2d50: hole next is not a hole>
  <gc check (91): Hole 905c2d50 header: 905C2CD9 00000000 00000028 00000000>
  <gc check (92): from debugger: HEAP: Object905c2e18: hole next is not a hole>
  <gc check (92): Hole 905c2e18 header: 905C2DA1 00000000 00000028 00000000>
  <gc check (93): from debugger: HEAP: Object905c3368: hole next is not a hole>
  <gc check (93): Hole 905c3368 header: 905C32C9 00000000 00000028 00000000>
  <gc check (94): from debugger: HEAP: Object905c3638: hole next is not a hole>
  <gc check (94): Hole 905c3638 header: 905C3599 00000000 00000028 00000000>
  <gc check (95): from debugger: HEAP: Object905c3728: hole next is not a hole>
  <gc check (95): Hole 905c3728 header: 905C3689 00000000 00000028 00000000>
  <gc check (96): from debugger: HEAP: Object905c38e0: hole next is not a hole>
  <gc check (96): Hole 905c38e0 header: 905C3841 00000000 00000028 00000000>
  <gc check (97): from debugger: HEAP: Object905c3a70: hole next is not a hole>
  <gc check (97): Hole 905c3a70 header: 905C39D1 00000000 00000028 00000000>
  <gc check (98): from debugger: HEAP: Object905c3c50: hole next is not a hole>
  <gc check (98): Hole 905c3c50 header: 905C3BB1 00000000 00000028 00000000>
  <gc check (99): from debugger: HEAP: Object905c3f20: hole next is not a hole>
  <gc check (99): Hole 905c3f20 header: 905C3E81 00000000 00000028 00000000>
  <gc check (100): from debugger: HEAP: Object905c41c8: hole next is not a hole>
  <gc check (100): Hole 905c41c8 header: 905C4129 00000000 00000028 00000000>
  <gc check (101): from debugger: HEAP: Object905c4420: hole next is not a hole>
  <gc check (101): Hole 905c4420 header: 905C4381 00000000 00000028 00000000>
  <gc check (102): from debugger: HEAP: Object905c4768: hole next is not a hole>
  <gc check (102): Hole 905c4768 header: 905C46C9 00000000 00000028 00000000>
  <gc check (103): from debugger: HEAP: Object905c4c18: hole next is not a hole>
  <gc check (103): Hole 905c4c18 header: 905C4B79 00000000 00000028 00000000>
  <gc check (104): from debugger: HEAP: Object905c4f88: hole next is not a hole>
  <gc check (104): Hole 905c4f88 header: 905C4EE9 00000000 00000028 00000000>
  <gc check (105): from debugger: HEAP: Object905c5118: hole next is not a hole>
  <gc check (105): Hole 905c5118 header: 905C5079 00000000 00000028 00000000>
  <gc check (106): from debugger: HEAP: Object905c5780: hole next is not a hole>
  <gc check (106): Hole 905c5780 header: 905C56B9 00000000 00000028 00000000>
  <gc check (107): from debugger: HEAP: Object905c5870: hole next is not a hole>
  <gc check (107): Hole 905c5870 header: 905C57D1 00000000 00000028 00000000>
  <gc check (108): from debugger: HEAP: Object905c5a50: hole next is not a hole>
  <gc check (108): Hole 905c5a50 header: 905C5961 00000000 00000028 00000000>
  <gc check (109): from debugger: HEAP: Object905c5bb8: hole next is not a hole>
  <gc check (109): Hole 905c5bb8 header: 905C5AF1 00000000 00000028 00000000>
  <gc check (110): from debugger: HEAP: Object905c60e0: hole next is not a hole>
  <gc check (110): Hole 905c60e0 header: 905C5D99 00000000 00000028 00000000>
  <gc check (111): from debugger: HEAP: Object905c61f8: hole next is not a hole>
  <gc check (111): Hole 905c61f8 header: 905C6181 00000000 00000028 00000000>
  <gc check (112): from debugger: HEAP: Object905c6950: hole next is not a hole>
  <gc check (112): Hole 905c6950 header: 905C68B1 00000000 00000028 00000000>
  <gc check (113): from debugger: HEAP: Object905c6b58: hole next is not a hole>
  <gc check (113): Hole 905c6b58 header: 905C6AB9 00000000 00000028 00000000>
  <gc check (114): from debugger: HEAP: Object905c6d38: hole next is not a hole>
  <gc check (114): Hole 905c6d38 header: 905C6C99 00000000 00000028 00000000>
  <gc check (115): from debugger: HEAP: Object905c6e78: hole next is not a hole>
  <gc check (115): Hole 905c6e78 header: 905C6E01 00000000 00000028 00000000>
  <gc check (116): from debugger: HEAP: Object905c7120: hole next is not a hole>
  <gc check (116): Hole 905c7120 header: 905C7081 00000000 00000028 00000000>
  <gc check (117): from debugger: HEAP: Object905c7490: hole next is not a hole>
  <gc check (117): Hole 905c7490 header: 905C73F1 00000000 00000028 00000000>
  <gc check (118): from debugger: HEAP: Object90b92a40: hole next is not a hole>
  <gc check (118): Hole 90b92a40 header: 90B91621 00000000 00000020 00000000>
  <gc check (119): from debugger: HEAP: Object90b98f60: hole next is not a hole>
  <gc check (119): Hole 90b98f60 header: 90B983E1 00000000 00000020 00000000>
  <gc check (120): from debugger: HEAP: Object90da0c60: hole next is not a hole>
  <gc check (120): Hole 90da0c60 header: 90DA0BE1 00000000 00000020 00000000>
  <gc check (121): from debugger: HEAP: Object90da3060: hole next is not a hole>
  <gc check (121): Hole 90da3060 header: 90DA2261 00000000 00000020 00000000>
  <gc check (122): from debugger: HEAP: Object90da5360: hole next is not a hole>
  <gc check (122): Hole 90da5360 header: 90DA3741 00000000 00000020 00000000>
  <gc check (123): from debugger: HEAP: Object90da7200: hole next is not a hole>
  <gc check (123): Hole 90da7200 header: 90DA7021 00000000 00000020 00000000>
  <gc check (124): from debugger: HEAP: Object90da7d40: hole next is not a hole>
  <gc check (124): Hole 90da7d40 header: 90DA7AE1 00000000 00000020 00000000>
  <gc check (125): from debugger: HEAP: Object90da8f00: hole next is not a hole>
  <gc check (125): Hole 90da8f00 header: 90DA8DC1 00000000 00000020 00000000>
  <gc check (126): from debugger: HEAP: Object slot 915333c0(915333c4) -> 90674600: class pointer not in a class segment>
  <gc check (127): from debugger: HEAP: Object slot 94680000(94680004) -> 84379e78: class pointer not in a class segment>
  <gc check (128): from debugger: HEAP: Objecta2c514a0: hole next is not a hole>
  <gc check (128): Hole a2c514a0 header: A2C51401 00000000 00000020 00000000>
  <gc check (129): from debugger: HEAP: Objecta2c52160: hole next is not a hole>
  <gc check (129): Hole a2c52160 header: A2C51A81 00000000 00000020 00000000>
  <gc check (130): from debugger: HEAP: Objecta2c528a0: hole next is not a hole>
  <gc check (130): Hole a2c528a0 header: A2C52821 00000000 00000020 00000000>
  <gc check (131): from debugger: HEAP: Objecta2c53aa0: hole next is not a hole>
  <gc check (131): Hole a2c53aa0 header: A2C539A1 00000000 00000020 00000000>
  <gc check (132): from debugger: HEAP: Objecta2c53fc0: hole next is not a hole>
  <gc check (132): Hole a2c53fc0 header: A2C53CE1 00000000 00000020 00000000>
  <gc check (133): from debugger: HEAP: Objecta2c549e0: hole next is not a hole>
  <gc check (133): Hole a2c549e0 header: A2C54761 00000000 00000020 00000000>
  <gc check (134): from debugger: HEAP: Objecta2c554a0: hole next is not a hole>
  <gc check (134): Hole a2c554a0 header: A2C55421 00000000 00000020 00000000>
  <gc check (135): from debugger: HEAP: Objecta2c56be0: hole next is not a hole>
  <gc check (135): Hole a2c56be0 header: A2C566A1 00000000 00000020 00000000>
  <gc check (136): from debugger: HEAP: Objecta2c57c00: hole next is not a hole>
  <gc check (136): Hole a2c57c00 header: A2C57A81 00000000 00000020 00000000>
  <gc check (137): from debugger: HEAP: Objecta2c58660: hole next is not a hole>
  <gc check (137): Hole a2c58660 header: A2C58521 00000000 00000020 00000000>
  <gc check (138): from debugger: HEAP: Objecta2c5a0a0: hole next is not a hole>
  <gc check (138): Hole a2c5a0a0 header: A2C5A041 00000000 00000020 00000000>
  <gc check (139): from debugger: HEAP: Objecta2c5a260: hole next is not a hole>
  <gc check (139): Hole a2c5a260 header: A2C5A201 00000000 00000020 00000000>
  <gc check (140): from debugger: HEAP: Objecta2c5a540: hole next is not a hole>
  <gc check (140): Hole a2c5a540 header: A2C5A4C1 00000000 00000020 00000000>
  <gc check (141): from debugger: HEAP: Objecta2c5ab40: hole next is not a hole>
  <gc check (141): Hole a2c5ab40 header: A2C5A821 00000000 00000020 00000000>
  <gc check (142): from debugger: HEAP: Objecta2c5b4a0: hole next is not a hole>
  <gc check (142): Hole a2c5b4a0 header: A2C5B421 00000000 00000020 00000000>
  <gc check (143): from debugger: HEAP: Objecta2c5bd60: hole next is not a hole>
  <gc check (143): Hole a2c5bd60 header: A2C5BC81 00000000 00000020 00000000>
  <gc check (144): from debugger: HEAP: Objecta2c5c180: hole next is not a hole>
  <gc check (144): Hole a2c5c180 header: A2C5C061 00000000 00000020 00000000>
  <gc check (145): from debugger: HEAP: Objecta2c5caa0: hole next is not a hole>
  <gc check (145): Hole a2c5caa0 header: A2C5C8E1 00000000 00000020 00000000>
  <gc check (146): from debugger: HEAP: Objecta2c5cfc0: hole next is not a hole>
  <gc check (146): Hole a2c5cfc0 header: A2C5CF61 00000000 00000020 00000000>
  <gc check (147): from debugger: HEAP: Objecta2c5d4c0: hole next is not a hole>
  <gc check (147): Hole a2c5d4c0 header: A2C5D441 00000000 00000020 00000000>
  <gc check (148): from debugger: HEAP: Objecta2c5dd80: hole next is not a hole>
  <gc check (148): Hole a2c5dd80 header: A2C5DC81 00000000 00000020 00000000>
  <gc check (149): from debugger: HEAP: Objecta2c5e440: hole next is not a hole>
  <gc check (149): Hole a2c5e440 header: A2C5E2C1 00000000 00000020 00000000>
  <gc check (150): from debugger: HEAP: Objecta2c5e600: hole next is not a hole>
  <gc check (150): Hole a2c5e600 header: A2C5E521 00000000 00000020 00000000>
  <gc check (151): from debugger: HEAP: Objecta2c5e6a0: hole next is not a hole>
  <gc check (151): Hole a2c5e6a0 header: A2C5E641 00000000 00000020 00000000>
  <gc check (152): from debugger: HEAP: Objecta2c5e8c0: hole next is not a hole>
  <gc check (152): Hole a2c5e8c0 header: A2C5E761 00000000 00000020 00000000>
  <gc check (153): from debugger: HEAP: Objecta2c5f900: hole next is not a hole>
  <gc check (153): Hole a2c5f900 header: A2C5F8A1 00000000 00000020 00000000>
  <gc check (154): from debugger: HEAP: Objecta2fe0670: hole next is not a hole>
  <gc check (154): Hole a2fe0670 header: A2FE05D1 00000000 00000010 00000000>
  <gc check (155): from debugger: HEAP: Objecta2fe0790: hole next is not a hole>
  <gc check (155): Hole a2fe0790 header: A2FE0691 00000000 00000010 00000000>
  <gc check (156): from debugger: HEAP: Objecta2fe0830: hole next is not a hole>
  <gc check (156): Hole a2fe0830 header: A2FE07B1 00000000 00000010 00000000>
  <gc check (157): from debugger: HEAP: Objecta848ff80: hole next is not a hole>
  <gc check (157): Hole a848ff80 header: A848FD61 00000000 00000020 00000000>
  <gc check (158): from debugger: HEAP: Objectae1f58e0: hole next is not a hole>
  <gc check (158): Hole ae1f58e0 header: AE1F1DA1 00000000 00000020 00000000>
  <gc check (159): from debugger: HEAP: Objectb5888e20: hole next is not a hole>
  <gc check (159): Hole b5888e20 header: B5888941 00000000 00000020 00000000>
  <gc check (160): from debugger: HEAP: Objectb588cec0: hole next is not a hole>
  <gc check (160): Hole b588cec0 header: B588C7C1 00000000 00000020 00000000>
done (110984 ms).
Done (110990ms)
```

</details>

Here is the patched build:

<details>
<summary>Patched build output</summary>

```
[Mon Apr 18 11:49:32 CDT 2022] count(JavaObject) = 1427353
[...]
> !gccheck objectheap
Starting GC Check
Checking HEAP...  <gc check (1): from debugger: HEAP: Object slot 83ca0210(83ca0224) -> 845bb1d0: class pointer not in a class segment>
  <gc check (2): from debugger: HEAP: Object slot 83cad9f0(83cad9fc) -> 83e33260: class pointer not in a class segment>
  <gc check (3): from debugger: HEAP: Object83cb0540: hole next is not a hole>
  <gc check (3): Hole 83cb0540 header: 83CB0421 00000000 00000020 00000000>
  <gc check (4): from debugger: HEAP: Object83cb0b60: hole next is not a hole>
  <gc check (4): Hole 83cb0b60 header: 83CB0B01 00000000 00000020 00000000>
  <gc check (5): from debugger: HEAP: Object83cb0fe0: hole next is not a hole>
  <gc check (5): Hole 83cb0fe0 header: 83CB0F61 00000000 00000020 00000000>
  <gc check (6): from debugger: HEAP: Object83cb1800: hole next is not a hole>
  <gc check (6): Hole 83cb1800 header: 83CB16A1 00000000 00000020 00000000>
  <gc check (7): from debugger: HEAP: Object83cb23a0: hole next is not a hole>
  <gc check (7): Hole 83cb23a0 header: 83CB21C1 00000000 00000020 00000000>
  <gc check (8): from debugger: HEAP: Object83cb2440: hole next is not a hole>
  <gc check (8): Hole 83cb2440 header: 83CB23E1 00000000 00000020 00000000>
  <gc check (9): from debugger: HEAP: Object83cb27a0: hole next is not a hole>
  <gc check (9): Hole 83cb27a0 header: 83CB2701 00000000 00000020 00000000>
  <gc check (10): from debugger: HEAP: Object83cb2940: hole next is not a hole>
  <gc check (10): Hole 83cb2940 header: 83CB2841 00000000 00000020 00000000>
  <gc check (11): from debugger: HEAP: Object83cb2ce0: hole next is not a hole>
  <gc check (11): Hole 83cb2ce0 header: 83CB2C81 00000000 00000020 00000000>
  <gc check (12): from debugger: HEAP: Object83cb2e40: hole next is not a hole>
  <gc check (12): Hole 83cb2e40 header: 83CB2D21 00000000 00000020 00000000>
  <gc check (13): from debugger: HEAP: Object83cb3760: hole next is not a hole>
  <gc check (13): Hole 83cb3760 header: 83CB2FE1 00000000 00000020 00000000>
  <gc check (14): from debugger: HEAP: Object83cb47e0: hole next is not a hole>
  <gc check (14): Hole 83cb47e0 header: 83CB4421 00000000 00000020 00000000>
  <gc check (15): from debugger: HEAP: Object83cb5be0: hole next is not a hole>
  <gc check (15): Hole 83cb5be0 header: 83CB59C1 00000000 00000020 00000000>
  <gc check (16): from debugger: HEAP: Object83cb65e0: hole next is not a hole>
  <gc check (16): Hole 83cb65e0 header: 83CB6261 00000000 00000020 00000000>
  <gc check (17): from debugger: HEAP: Object83cb6900: hole next is not a hole>
  <gc check (17): Hole 83cb6900 header: 83CB6821 00000000 00000020 00000000>
  <gc check (18): from debugger: HEAP: Object83cb6c20: hole next is not a hole>
  <gc check (18): Hole 83cb6c20 header: 83CB6AE1 00000000 00000020 00000000>
  <gc check (19): from debugger: HEAP: Object83cbb120: hole next is not a hole>
  <gc check (19): Hole 83cbb120 header: 83CBB041 00000000 00000020 00000000>
  <gc check (20): from debugger: HEAP: Object83cbb260: hole next is not a hole>
  <gc check (20): Hole 83cbb260 header: 83CBB201 00000000 00000020 00000000>
  <gc check (21): from debugger: HEAP: Object83cbf7e0: hole next is not a hole>
  <gc check (21): Hole 83cbf7e0 header: 83CBF3A1 00000000 00000020 00000000>
  <gc check (22): from debugger: HEAP: Object83cbfc00: hole next is not a hole>
  <gc check (22): Hole 83cbfc00 header: 83CBF961 00000000 00000020 00000000>
  <gc check (23): from debugger: HEAP: Object83d1f4f8: hole next is not a hole>
  <gc check (23): Hole 83d1f4f8 header: 83D1F301 00000000 00000048 00000000>
  <gc check (24): from debugger: HEAP: Object843e5758: hole next is not a hole>
  <gc check (24): Hole 843e5758 header: 843E5419 00000000 00000068 00000000>
  <gc check (25): from debugger: HEAP: Object slot 845b9420(845b942c) -> c49e7c38: class pointer not in a class segment>
  <gc check (26): from debugger: HEAP: Object slot 845b94c0(845b94cc) -> c49e7c38: class pointer not in a class segment>
  <gc check (27): from debugger: HEAP: Object slot 8b68fa30(8b68fa34) -> 900ffbd0: class pointer is null>
  <gc check (28): from debugger: HEAP: Object slot 8ff48ed0(8ff48ed8) -> 9b2c8b80: class pointer not in a class segment>
  <gc check (29): from debugger: HEAP: Object slot 8ff4c670(8ff4c678) -> b56994a0: class pointer not in a class segment>
  <gc check (30): from debugger: HEAP: Object slot 8ff905c8(8ff905d4) -> 9bd966a8: class pointer not in a class segment>
  <gc check (31): from debugger: HEAP: Object slot 8ff906b8(8ff906c4) -> 9bd966a8: class pointer not in a class segment>
  <gc check (32): from debugger: HEAP: Object slot 8ff948a8(8ff948b0) -> 885e8140: class pointer not in a class segment>
  <gc check (33): from debugger: HEAP: Object slot 8ff95f50(8ff95f58) -> b4369690: class pointer not in a class segment>
  <gc check (34): from debugger: HEAP: Object slot 8ff98db8(8ff98dc0) -> 9d91e350: class pointer not in a class segment>
  <gc check (35): from debugger: HEAP: Object slot 8ff9b810(8ff9b81c) -> b1c69a80: class pointer not in a class segment>
  <gc check (36): from debugger: HEAP: Object slot 8ff9b838(8ff9b844) -> b1c69a80: class pointer not in a class segment>
  <gc check (37): from debugger: HEAP: Object slot 8ff9ea88(8ff9ea90) -> 9c358440: corrupt data exception>
  <gc check (38): from debugger: HEAP: Object slot 90062e18(90062e24) -> 9209dde0: class pointer not in a class segment>
  <gc check (39): from debugger: HEAP: Object slot 90062fa8(90062fb4) -> 9209dcc0: class pointer not in a class segment>
  <gc check (40): from debugger: HEAP: Object900afe60: hole next is not a hole>
  <gc check (40): Hole 900afe60 header: 900AFD71 00000000 00000028 00000000>
  <gc check (41): from debugger: HEAP: Object900afeb0: hole next is not a hole>
  <gc check (41): Hole 900afeb0 header: 900AFD71 00000000 00000078 00000000>
  <gc check (42): from debugger: HEAP: Object slot 901aeea8(901aeed0) -> 97b59f60: class pointer not in a class segment>
  <gc check (43): from debugger: HEAP: Object slot 901aef88(901aef98) -> 97b59f60: class pointer not in a class segment>
  <gc check (44): from debugger: HEAP: Object90210880: hole next is not a hole>
  <gc check (44): Hole 90210880 header: 90210281 00000000 00000020 00000000>
  <gc check (45): from debugger: HEAP: Object90211760: hole next is not a hole>
  <gc check (45): Hole 90211760 header: 902110C1 00000000 00000020 00000000>
  <gc check (46): from debugger: HEAP: Object90212360: hole next is not a hole>
  <gc check (46): Hole 90212360 header: 90211A21 00000000 00000020 00000000>
  <gc check (47): from debugger: HEAP: Object90213300: hole next is not a hole>
  <gc check (47): Hole 90213300 header: 90212D21 00000000 00000020 00000000>
  <gc check (48): from debugger: HEAP: Object902134e0: hole next is not a hole>
  <gc check (48): Hole 902134e0 header: 90213421 00000000 00000020 00000000>
  <gc check (49): from debugger: HEAP: Object902136c0: hole next is not a hole>
  <gc check (49): Hole 902136c0 header: 90213581 00000000 00000020 00000000>
  <gc check (50): from debugger: HEAP: Object902141a0: hole next is not a hole>
  <gc check (50): Hole 902141a0 header: 902140C1 00000000 00000020 00000000>
  <gc check (51): from debugger: HEAP: Object90214ac0: hole next is not a hole>
  <gc check (51): Hole 90214ac0 header: 90214A21 00000000 00000020 00000000>
  <gc check (52): from debugger: HEAP: Object90215280: hole next is not a hole>
  <gc check (52): Hole 90215280 header: 90215221 00000000 00000020 00000000>
  <gc check (53): from debugger: HEAP: Object902153a0: hole next is not a hole>
  <gc check (53): Hole 902153a0 header: 90215341 00000000 00000020 00000000>
  <gc check (54): from debugger: HEAP: Object90215f40: hole next is not a hole>
  <gc check (54): Hole 90215f40 header: 90215EC1 00000000 00000020 00000000>
  <gc check (55): from debugger: HEAP: Object90216440: hole next is not a hole>
  <gc check (55): Hole 90216440 header: 902162A1 00000000 00000020 00000000>
  <gc check (56): from debugger: HEAP: Object90216de0: hole next is not a hole>
  <gc check (56): Hole 90216de0 header: 90216C01 00000000 00000020 00000000>
  <gc check (57): from debugger: HEAP: Object90217aa0: hole next is not a hole>
  <gc check (57): Hole 90217aa0 header: 90217961 00000000 00000020 00000000>
  <gc check (58): from debugger: HEAP: Object90217fa0: hole next is not a hole>
  <gc check (58): Hole 90217fa0 header: 90217F41 00000000 00000020 00000000>
  <gc check (59): from debugger: HEAP: Object9021a280: hole next is not a hole>
  <gc check (59): Hole 9021a280 header: 9021A141 00000000 00000020 00000000>
  <gc check (60): from debugger: HEAP: Object9021a920: hole next is not a hole>
  <gc check (60): Hole 9021a920 header: 9021A801 00000000 00000020 00000000>
  <gc check (61): from debugger: HEAP: Object9021b0e0: hole next is not a hole>
  <gc check (61): Hole 9021b0e0 header: 9021AF41 00000000 00000020 00000000>
  <gc check (62): from debugger: HEAP: Object9021b360: hole next is not a hole>
  <gc check (62): Hole 9021b360 header: 9021B1C1 00000000 00000020 00000000>
  <gc check (63): from debugger: HEAP: Object9021b980: hole next is not a hole>
  <gc check (63): Hole 9021b980 header: 9021B901 00000000 00000020 00000000>
  <gc check (64): from debugger: HEAP: Object9021c200: hole next is not a hole>
  <gc check (64): Hole 9021c200 header: 9021C0A1 00000000 00000020 00000000>
  <gc check (65): from debugger: HEAP: Object9021cbe0: hole next is not a hole>
  <gc check (65): Hole 9021cbe0 header: 9021CAC1 00000000 00000020 00000000>
  <gc check (66): from debugger: HEAP: Object9021ce40: hole next is not a hole>
  <gc check (66): Hole 9021ce40 header: 9021CCC1 00000000 00000020 00000000>
  <gc check (67): from debugger: HEAP: Object9021d320: hole next is not a hole>
  <gc check (67): Hole 9021d320 header: 9021D2C1 00000000 00000020 00000000>
  <gc check (68): from debugger: HEAP: Object9021dcc0: hole next is not a hole>
  <gc check (68): Hole 9021dcc0 header: 9021D961 00000000 00000020 00000000>
  <gc check (69): from debugger: HEAP: Object9021eaa0: hole next is not a hole>
  <gc check (69): Hole 9021eaa0 header: 9021E481 00000000 00000020 00000000>
  <gc check (70): from debugger: HEAP: Object9021f320: hole next is not a hole>
  <gc check (70): Hole 9021f320 header: 9021F201 00000000 00000020 00000000>
  <gc check (71): from debugger: HEAP: Object9021fb40: hole next is not a hole>
  <gc check (71): Hole 9021fb40 header: 9021F5C1 00000000 00000020 00000000>
  <gc check (72): from debugger: HEAP: Object902d05c8: hole next is not a hole>
  <gc check (72): Hole 902d05c8 header: 902D0529 00000000 00000028 00000000>
  <gc check (73): from debugger: HEAP: Object902d0910: hole next is not a hole>
  <gc check (73): Hole 902d0910 header: 902D0871 00000000 00000028 00000000>
  <gc check (74): from debugger: HEAP: Object902d0d20: hole next is not a hole>
  <gc check (74): Hole 902d0d20 header: 902D0C81 00000000 00000028 00000000>
  <gc check (75): from debugger: HEAP: Object902d0e60: hole next is not a hole>
  <gc check (75): Hole 902d0e60 header: 902D0DC1 00000000 00000028 00000000>
  <gc check (76): from debugger: HEAP: Object902d10e0: hole next is not a hole>
  <gc check (76): Hole 902d10e0 header: 902D1041 00000000 00000028 00000000>
  <gc check (77): from debugger: HEAP: Object902d11f8: hole next is not a hole>
  <gc check (77): Hole 902d11f8 header: 902D1159 00000000 00000028 00000000>
  <gc check (78): from debugger: HEAP: Object902d1310: hole next is not a hole>
  <gc check (78): Hole 902d1310 header: 902D1271 00000000 00000028 00000000>
  <gc check (79): from debugger: HEAP: Object902d14c8: hole next is not a hole>
  <gc check (79): Hole 902d14c8 header: 902D1429 00000000 00000028 00000000>
  <gc check (80): from debugger: HEAP: Object902d1608: hole next is not a hole>
  <gc check (80): Hole 902d1608 header: 902D1591 00000000 00000028 00000000>
  <gc check (81): from debugger: HEAP: Object902d17c0: hole next is not a hole>
  <gc check (81): Hole 902d17c0 header: 902D16F9 00000000 00000028 00000000>
  <gc check (82): from debugger: HEAP: Object902d1b58: hole next is not a hole>
  <gc check (82): Hole 902d1b58 header: 902D1A91 00000000 00000028 00000000>
  <gc check (83): from debugger: HEAP: Object902d2800: hole next is not a hole>
  <gc check (83): Hole 902d2800 header: 902D2761 00000000 00000028 00000000>
  <gc check (84): from debugger: HEAP: Object902d2ad0: hole next is not a hole>
  <gc check (84): Hole 902d2ad0 header: 902D2A31 00000000 00000028 00000000>
  <gc check (85): from debugger: HEAP: Object902d2c38: hole next is not a hole>
  <gc check (85): Hole 902d2c38 header: 902D2B71 00000000 00000028 00000000>
  <gc check (86): from debugger: HEAP: Object902d2dc8: hole next is not a hole>
  <gc check (86): Hole 902d2dc8 header: 902D2D29 00000000 00000028 00000000>
  <gc check (87): from debugger: HEAP: Object902d2f58: hole next is not a hole>
  <gc check (87): Hole 902d2f58 header: 902D2EB9 00000000 00000028 00000000>
  <gc check (88): from debugger: HEAP: Object902d3430: hole next is not a hole>
  <gc check (88): Hole 902d3430 header: 902D3369 00000000 00000028 00000000>
  <gc check (89): from debugger: HEAP: Object902d35e8: hole next is not a hole>
  <gc check (89): Hole 902d35e8 header: 902D3549 00000000 00000028 00000000>
  <gc check (90): from debugger: HEAP: Object902d3c50: hole next is not a hole>
  <gc check (90): Hole 902d3c50 header: 902D3BD9 00000000 00000028 00000000>
  <gc check (91): from debugger: HEAP: Object902d3d90: hole next is not a hole>
  <gc check (91): Hole 902d3d90 header: 902D3CF1 00000000 00000028 00000000>
  <gc check (92): from debugger: HEAP: Object902d3f20: hole next is not a hole>
  <gc check (92): Hole 902d3f20 header: 902D3E81 00000000 00000028 00000000>
  <gc check (93): from debugger: HEAP: Object902d40b0: hole next is not a hole>
  <gc check (93): Hole 902d40b0 header: 902D4011 00000000 00000028 00000000>
  <gc check (94): from debugger: HEAP: Object902d50f0: hole next is not a hole>
  <gc check (94): Hole 902d50f0 header: 902D5051 00000000 00000028 00000000>
  <gc check (95): from debugger: HEAP: Object902d51e0: hole next is not a hole>
  <gc check (95): Hole 902d51e0 header: 902D5141 00000000 00000028 00000000>
  <gc check (96): from debugger: HEAP: Object902d5398: hole next is not a hole>
  <gc check (96): Hole 902d5398 header: 902D52F9 00000000 00000028 00000000>
  <gc check (97): from debugger: HEAP: Object902d5488: hole next is not a hole>
  <gc check (97): Hole 902d5488 header: 902D53E9 00000000 00000028 00000000>
  <gc check (98): from debugger: HEAP: Object902d59d8: hole next is not a hole>
  <gc check (98): Hole 902d59d8 header: 902D5939 00000000 00000028 00000000>
  <gc check (99): from debugger: HEAP: Object902d5ca8: hole next is not a hole>
  <gc check (99): Hole 902d5ca8 header: 902D5BE1 00000000 00000028 00000000>
  <gc check (100): from debugger: HEAP: Object902d60e0: hole next is not a hole>
  <gc check (100): Hole 902d60e0 header: 902D6041 00000000 00000028 00000000>
  <gc check (101): from debugger: HEAP: Object902d6310: hole next is not a hole>
  <gc check (101): Hole 902d6310 header: 902D6271 00000000 00000028 00000000>
  <gc check (102): from debugger: HEAP: Object902d6400: hole next is not a hole>
  <gc check (102): Hole 902d6400 header: 902D6361 00000000 00000028 00000000>
  <gc check (103): from debugger: HEAP: Object902d6810: hole next is not a hole>
  <gc check (103): Hole 902d6810 header: 902D6771 00000000 00000028 00000000>
  <gc check (104): from debugger: HEAP: Object902d6bd0: hole next is not a hole>
  <gc check (104): Hole 902d6bd0 header: 902D6B59 00000000 00000028 00000000>
  <gc check (105): from debugger: HEAP: Object902d6ce8: hole next is not a hole>
  <gc check (105): Hole 902d6ce8 header: 902D6C21 00000000 00000028 00000000>
  <gc check (106): from debugger: HEAP: Object902d6e78: hole next is not a hole>
  <gc check (106): Hole 902d6e78 header: 902D6DD9 00000000 00000028 00000000>
  <gc check (107): from debugger: HEAP: Object902d7080: hole next is not a hole>
  <gc check (107): Hole 902d7080 header: 902D6FB9 00000000 00000028 00000000>
  <gc check (108): from debugger: HEAP: Object902d71c0: hole next is not a hole>
  <gc check (108): Hole 902d71c0 header: 902D7149 00000000 00000028 00000000>
  <gc check (109): from debugger: HEAP: Object902d72b0: hole next is not a hole>
  <gc check (109): Hole 902d72b0 header: 902D7211 00000000 00000028 00000000>
  <gc check (110): from debugger: HEAP: Object902d7558: hole next is not a hole>
  <gc check (110): Hole 902d7558 header: 902D74B9 00000000 00000028 00000000>
  <gc check (111): from debugger: HEAP: Object902d84a8: hole next is not a hole>
  <gc check (111): Hole 902d84a8 header: 902D8409 00000000 00000028 00000000>
  <gc check (112): from debugger: HEAP: Object902d8890: hole next is not a hole>
  <gc check (112): Hole 902d8890 header: 902D87F1 00000000 00000028 00000000>
  <gc check (113): from debugger: HEAP: Object902d8a70: hole next is not a hole>
  <gc check (113): Hole 902d8a70 header: 902D89A9 00000000 00000028 00000000>
  <gc check (114): from debugger: HEAP: Object902d8cf0: hole next is not a hole>
  <gc check (114): Hole 902d8cf0 header: 902D8C51 00000000 00000028 00000000>
  <gc check (115): from debugger: HEAP: Object902d8f20: hole next is not a hole>
  <gc check (115): Hole 902d8f20 header: 902D8E81 00000000 00000028 00000000>
  <gc check (116): from debugger: HEAP: Object902d9358: hole next is not a hole>
  <gc check (116): Hole 902d9358 header: 902D92B9 00000000 00000028 00000000>
  <gc check (117): from debugger: HEAP: Object902da758: hole next is not a hole>
  <gc check (117): Hole 902da758 header: 902DA6E1 00000000 00000028 00000000>
  <gc check (118): from debugger: HEAP: Object902db3d8: hole next is not a hole>
  <gc check (118): Hole 902db3d8 header: 902DB339 00000000 00000028 00000000>
  <gc check (119): from debugger: HEAP: Object902db518: hole next is not a hole>
  <gc check (119): Hole 902db518 header: 902DB4A1 00000000 00000028 00000000>
  <gc check (120): from debugger: HEAP: Object902db6d0: hole next is not a hole>
  <gc check (120): Hole 902db6d0 header: 902DB659 00000000 00000028 00000000>
  <gc check (121): from debugger: HEAP: Object902db8b0: hole next is not a hole>
  <gc check (121): Hole 902db8b0 header: 902DB811 00000000 00000028 00000000>
  <gc check (122): from debugger: HEAP: Object slot 90326270(90326278) -> 841e4620: class pointer not in a class segment>
  <gc check (123): from debugger: HEAP: Object slot 9032c418(9032c420) -> a7160060: class pointer is null>
  <gc check (124): from debugger: HEAP: Object90511b60: hole next is not a hole>
  <gc check (124): Hole 90511b60 header: 90511AA1 00000000 00000020 00000000>
  <gc check (125): from debugger: HEAP: Object90515820: hole next is not a hole>
  <gc check (125): Hole 90515820 header: 90514B21 00000000 00000020 00000000>
  <gc check (126): from debugger: HEAP: Object90515a80: hole next is not a hole>
  <gc check (126): Hole 90515a80 header: 90515861 00000000 00000020 00000000>
  <gc check (127): from debugger: HEAP: Object905189e0: hole next is not a hole>
  <gc check (127): Hole 905189e0 header: 905187C1 00000000 00000020 00000000>
  <gc check (128): from debugger: HEAP: Object9051d200: hole next is not a hole>
  <gc check (128): Hole 9051d200 header: 9051CFE1 00000000 00000020 00000000>
  <gc check (129): from debugger: HEAP: Object905915e0: hole next is not a hole>
  <gc check (129): Hole 905915e0 header: 905910E1 00000000 00000020 00000000>
  <gc check (130): from debugger: HEAP: Object90594ea0: hole next is not a hole>
  <gc check (130): Hole 90594ea0 header: 90592541 00000000 00000020 00000000>
  <gc check (131): from debugger: HEAP: Object905965a0: hole next is not a hole>
  <gc check (131): Hole 905965a0 header: 90595EE1 00000000 00000020 00000000>
  <gc check (132): from debugger: HEAP: Object905984a0: hole next is not a hole>
  <gc check (132): Hole 905984a0 header: 90598201 00000000 00000020 00000000>
  <gc check (133): from debugger: HEAP: Object90599120: hole next is not a hole>
  <gc check (133): Hole 90599120 header: 905990C1 00000000 00000020 00000000>
  <gc check (134): from debugger: HEAP: Object9059a440: hole next is not a hole>
  <gc check (134): Hole 9059a440 header: 90599E81 00000000 00000020 00000000>
  <gc check (135): from debugger: HEAP: Object9059ab60: hole next is not a hole>
  <gc check (135): Hole 9059ab60 header: 9059A661 00000000 00000020 00000000>
  <gc check (136): from debugger: HEAP: Object9059be40: hole next is not a hole>
  <gc check (136): Hole 9059be40 header: 9059BD41 00000000 00000020 00000000>
  <gc check (137): from debugger: HEAP: Object90631c80: hole next is not a hole>
  <gc check (137): Hole 90631c80 header: 90631521 00000000 00000020 00000000>
  <gc check (138): from debugger: HEAP: Object906325a0: hole next is not a hole>
  <gc check (138): Hole 906325a0 header: 906324E1 00000000 00000020 00000000>
  <gc check (139): from debugger: HEAP: Object90633820: hole next is not a hole>
  <gc check (139): Hole 90633820 header: 906328C1 00000000 00000020 00000000>
  <gc check (140): from debugger: HEAP: Object90638780: hole next is not a hole>
  <gc check (140): Hole 90638780 header: 90637241 00000000 00000020 00000000>
  <gc check (141): from debugger: HEAP: Object90638ca0: hole next is not a hole>
  <gc check (141): Hole 90638ca0 header: 90638AC1 00000000 00000020 00000000>
  <gc check (142): from debugger: HEAP: Object906399a0: hole next is not a hole>
  <gc check (142): Hole 906399a0 header: 90639801 00000000 00000020 00000000>
  <gc check (143): from debugger: HEAP: Object9063da40: hole next is not a hole>
  <gc check (143): Hole 9063da40 header: 9063CAA1 00000000 00000020 00000000>
  <gc check (144): from debugger: HEAP: Object9063f040: hole next is not a hole>
  <gc check (144): Hole 9063f040 header: 9063DD01 00000000 00000020 00000000>
  <gc check (145): from debugger: HEAP: Object906419f0: hole next is not a hole>
  <gc check (145): Hole 906419f0 header: 90641901 00000000 00000028 00000000>
  <gc check (146): from debugger: HEAP: Object90641a40: hole next is not a hole>
  <gc check (146): Hole 90641a40 header: 90641901 00000000 00000078 00000000>
  <gc check (147): from debugger: HEAP: Object90642800: hole next is not a hole>
  <gc check (147): Hole 90642800 header: 90642711 00000000 00000078 00000000>
  <gc check (148): from debugger: HEAP: Object906431d8: hole next is not a hole>
  <gc check (148): Hole 906431d8 header: 906430E9 00000000 00000028 00000000>
  <gc check (149): from debugger: HEAP: Object90643228: hole next is not a hole>
  <gc check (149): Hole 90643228 header: 906430E9 00000000 00000078 00000000>
  <gc check (150): from debugger: HEAP: Object90645550: hole next is not a hole>
  <gc check (150): Hole 90645550 header: 90645461 00000000 00000028 00000000>
  <gc check (151): from debugger: HEAP: Object906455a0: hole next is not a hole>
  <gc check (151): Hole 906455a0 header: 90645461 00000000 00000050 00000000>
  <gc check (152): from debugger: HEAP: Object90648458: hole next is not a hole>
  <gc check (152): Hole 90648458 header: 90648369 00000000 00000028 00000000>
  <gc check (153): from debugger: HEAP: Object906484d0: hole next is not a hole>
  <gc check (153): Hole 906484d0 header: 90648369 00000000 00000078 00000000>
  <gc check (154): from debugger: HEAP: Object90648728: hole next is not a hole>
  <gc check (154): Hole 90648728 header: 90648639 00000000 00000028 00000000>
  <gc check (155): from debugger: HEAP: Object90648818: hole next is not a hole>
  <gc check (155): Hole 90648818 header: 90648639 00000000 00000078 00000000>
  <gc check (156): from debugger: HEAP: Object906493d0: hole next is not a hole>
  <gc check (156): Hole 906493d0 header: 906492E1 00000000 00000078 00000000>
  <gc check (157): from debugger: HEAP: Object9064dd18: hole next is not a hole>
  <gc check (157): Hole 9064dd18 header: 9064DC29 00000000 00000028 00000000>
  <gc check (158): from debugger: HEAP: Object9064ddb8: hole next is not a hole>
  <gc check (158): Hole 9064ddb8 header: 9064DC29 00000000 00000078 00000000>
  <gc check (159): from debugger: HEAP: Object9064ffc8: hole next is not a hole>
  <gc check (159): Hole 9064ffc8 header: 9064FED9 00000000 00000028 00000000>
  <gc check (160): from debugger: HEAP: Object90676b80: hole next is not a hole>
  <gc check (160): Hole 90676b80 header: 90676A91 00000000 00000028 00000000>
  <gc check (161): from debugger: HEAP: Object90676bd0: hole next is not a hole>
  <gc check (161): Hole 90676bd0 header: 90676A91 00000000 00000050 00000000>
  <gc check (162): from debugger: HEAP: Object90679e20: hole next is not a hole>
  <gc check (162): Hole 90679e20 header: 90679D31 00000000 00000028 00000000>
  <gc check (163): from debugger: HEAP: Object90679fd8: hole next is not a hole>
  <gc check (163): Hole 90679fd8 header: 90679D31 00000000 00000078 00000000>
  <gc check (164): from debugger: HEAP: Object9067a410: hole next is not a hole>
  <gc check (164): Hole 9067a410 header: 9067A321 00000000 00000028 00000000>
  <gc check (165): from debugger: HEAP: Object9067a550: hole next is not a hole>
  <gc check (165): Hole 9067a550 header: 9067A461 00000000 00000028 00000000>
  <gc check (166): from debugger: HEAP: Object9067a5a0: hole next is not a hole>
  <gc check (166): Hole 9067a5a0 header: 9067A461 00000000 00000078 00000000>
  <gc check (167): from debugger: HEAP: Object9067c710: hole next is not a hole>
  <gc check (167): Hole 9067c710 header: 9067C621 00000000 00000028 00000000>
  <gc check (168): from debugger: HEAP: Object9067c828: hole next is not a hole>
  <gc check (168): Hole 9067c828 header: 9067C761 00000000 00000078 00000000>
  <gc check (169): from debugger: HEAP: Object9067cc88: hole next is not a hole>
  <gc check (169): Hole 9067cc88 header: 9067CB99 00000000 00000028 00000000>
  <gc check (170): from debugger: HEAP: Object9067cda0: hole next is not a hole>
  <gc check (170): Hole 9067cda0 header: 9067CB99 00000000 00000078 00000000>
  <gc check (171): from debugger: HEAP: Object9067d4d0: hole next is not a hole>
  <gc check (171): Hole 9067d4d0 header: 9067D391 00000000 00000028 00000000>
  <gc check (172): from debugger: HEAP: Object9067d520: hole next is not a hole>
  <gc check (172): Hole 9067d520 header: 9067D391 00000000 00000078 00000000>
  <gc check (173): from debugger: HEAP: Object9067fbb8: hole next is not a hole>
  <gc check (173): Hole 9067fbb8 header: 9067FAC9 00000000 00000078 00000000>
  <gc check (174): from debugger: HEAP: Object906efc58: hole next is not a hole>
  <gc check (174): Hole 906efc58 header: 906EFB41 00000000 00000078 00000000>
  <gc check (175): from debugger: HEAP: Object906efed8: hole next is not a hole>
  <gc check (175): Hole 906efed8 header: 906EFCF9 00000000 00000078 00000000>
  <gc check (176): from debugger: HEAP: Object slot 908df9d0(908df9d4) -> 90067c38: class pointer not in a class segment>
  <gc check (177): from debugger: HEAP: Object908f05c0: hole next is not a hole>
  <gc check (177): Hole 908f05c0 header: 908F0361 00000000 00000020 00000000>
  <gc check (178): from debugger: HEAP: Object908f06a0: hole next is not a hole>
  <gc check (178): Hole 908f06a0 header: 908F0601 00000000 00000020 00000000>
  <gc check (179): from debugger: HEAP: Object908f08e0: hole next is not a hole>
  <gc check (179): Hole 908f08e0 header: 908F0861 00000000 00000020 00000000>
  <gc check (180): from debugger: HEAP: Object908f0c80: hole next is not a hole>
  <gc check (180): Hole 908f0c80 header: 908F0B81 00000000 00000020 00000000>
  <gc check (181): from debugger: HEAP: Object908f0ec0: hole next is not a hole>
  <gc check (181): Hole 908f0ec0 header: 908F0E61 00000000 00000020 00000000>
  <gc check (182): from debugger: HEAP: Object908f1780: hole next is not a hole>
  <gc check (182): Hole 908f1780 header: 908F1361 00000000 00000020 00000000>
  <gc check (183): from debugger: HEAP: Object908f1b60: hole next is not a hole>
  <gc check (183): Hole 908f1b60 header: 908F1901 00000000 00000020 00000000>
  <gc check (184): from debugger: HEAP: Object908f1d80: hole next is not a hole>
  <gc check (184): Hole 908f1d80 header: 908F1D21 00000000 00000020 00000000>
  <gc check (185): from debugger: HEAP: Object908f3560: hole next is not a hole>
  <gc check (185): Hole 908f3560 header: 908F3241 00000000 00000020 00000000>
  <gc check (186): from debugger: HEAP: Object908f4780: hole next is not a hole>
  <gc check (186): Hole 908f4780 header: 908F4721 00000000 00000020 00000000>
  <gc check (187): from debugger: HEAP: Object908f4aa0: hole next is not a hole>
  <gc check (187): Hole 908f4aa0 header: 908F49E1 00000000 00000020 00000000>
  <gc check (188): from debugger: HEAP: Object908f5060: hole next is not a hole>
  <gc check (188): Hole 908f5060 header: 908F4FE1 00000000 00000020 00000000>
  <gc check (189): from debugger: HEAP: Object908f5520: hole next is not a hole>
  <gc check (189): Hole 908f5520 header: 908F5101 00000000 00000020 00000000>
  <gc check (190): from debugger: HEAP: Object908f6120: hole next is not a hole>
  <gc check (190): Hole 908f6120 header: 908F5D41 00000000 00000020 00000000>
  <gc check (191): from debugger: HEAP: Object908f6620: hole next is not a hole>
  <gc check (191): Hole 908f6620 header: 908F62A1 00000000 00000020 00000000>
  <gc check (192): from debugger: HEAP: Object908f6ea0: hole next is not a hole>
  <gc check (192): Hole 908f6ea0 header: 908F6E01 00000000 00000020 00000000>
  <gc check (193): from debugger: HEAP: Object908f77c0: hole next is not a hole>
  <gc check (193): Hole 908f77c0 header: 908F7121 00000000 00000020 00000000>
  <gc check (194): from debugger: HEAP: Object908f83c0: hole next is not a hole>
  <gc check (194): Hole 908f83c0 header: 908F8321 00000000 00000020 00000000>
  <gc check (195): from debugger: HEAP: Object908fa180: hole next is not a hole>
  <gc check (195): Hole 908fa180 header: 908FA121 00000000 00000020 00000000>
  <gc check (196): from debugger: HEAP: Object908fa4c0: hole next is not a hole>
  <gc check (196): Hole 908fa4c0 header: 908FA401 00000000 00000020 00000000>
  <gc check (197): from debugger: HEAP: Object908fc6a0: hole next is not a hole>
  <gc check (197): Hole 908fc6a0 header: 908FC481 00000000 00000020 00000000>
  <gc check (198): from debugger: HEAP: Object908fe000: hole next is not a hole>
  <gc check (198): Hole 908fe000 header: 908FDDC1 00000000 00000020 00000000>
  <gc check (199): from debugger: HEAP: Object908fe0a0: hole next is not a hole>
  <gc check (199): Hole 908fe0a0 header: 908FE041 00000000 00000020 00000000>
  <gc check (200): from debugger: HEAP: Object908fe680: hole next is not a hole>
  <gc check (200): Hole 908fe680 header: 908FE121 00000000 00000020 00000000>
  <gc check (201): from debugger: HEAP: Object908feea0: hole next is not a hole>
  <gc check (201): Hole 908feea0 header: 908FED61 00000000 00000020 00000000>
  <gc check (202): from debugger: HEAP: Object908ffa00: hole next is not a hole>
  <gc check (202): Hole 908ffa00 header: 908FF961 00000000 00000020 00000000>
  <gc check (203): from debugger: HEAP: Object9098b7a0: hole next is not a hole>
  <gc check (203): Hole 9098b7a0 header: 9098B601 00000000 00000020 00000000>
  <gc check (204): from debugger: HEAP: Object9098e240: hole next is not a hole>
  <gc check (204): Hole 9098e240 header: 9098DBE1 00000000 00000020 00000000>
  <gc check (205): from debugger: HEAP: Object9098f1e0: hole next is not a hole>
  <gc check (205): Hole 9098f1e0 header: 9098F161 00000000 00000020 00000000>
  <gc check (206): from debugger: HEAP: Object9098f4a0: hole next is not a hole>
  <gc check (206): Hole 9098f4a0 header: 9098F3A1 00000000 00000020 00000000>
  <gc check (207): from debugger: HEAP: Object9098f680: hole next is not a hole>
  <gc check (207): Hole 9098f680 header: 9098F561 00000000 00000020 00000000>
  <gc check (208): from debugger: HEAP: Object slot 90ab3980(90ab3984) -> 900ffbd0: class pointer is null>
  <gc check (209): from debugger: HEAP: Object91174900: hole next is not a hole>
  <gc check (209): Hole 91174900 header: 91174681 00000000 00000020 00000000>
  <gc check (210): from debugger: HEAP: Object911778a0: hole next is not a hole>
  <gc check (210): Hole 911778a0 header: 91177581 00000000 00000020 00000000>
  <gc check (211): from debugger: HEAP: Object91177ea0: hole next is not a hole>
  <gc check (211): Hole 91177ea0 header: 91177E21 00000000 00000020 00000000>
  <gc check (212): from debugger: HEAP: Object91178f00: hole next is not a hole>
  <gc check (212): Hole 91178f00 header: 91178001 00000000 00000020 00000000>
  <gc check (213): from debugger: HEAP: Object91179020: hole next is not a hole>
  <gc check (213): Hole 91179020 header: 91178F81 00000000 00000020 00000000>
  <gc check (214): from debugger: HEAP: Object9117af60: hole next is not a hole>
  <gc check (214): Hole 9117af60 header: 9117A6E1 00000000 00000020 00000000>
  <gc check (215): from debugger: HEAP: Object9117b6e0: hole next is not a hole>
  <gc check (215): Hole 9117b6e0 header: 9117B281 00000000 00000020 00000000>
  <gc check (216): from debugger: HEAP: Object9117c680: hole next is not a hole>
  <gc check (216): Hole 9117c680 header: 9117C221 00000000 00000020 00000000>
  <gc check (217): from debugger: HEAP: Object9117eb60: hole next is not a hole>
  <gc check (217): Hole 9117eb60 header: 9117EA61 00000000 00000020 00000000>
  <gc check (218): from debugger: HEAP: IObject slot 9209d980(9209d990) -> b48bd980: class pointer not in a class segment>
  <gc check (219): from debugger: HEAP: Object920cff68: hole next is not a hole>
  <gc check (219): Hole 920cff68 header: 920CFBA1 00000000 00000058 00000000>
  <gc check (220): from debugger: HEAP: Object9248ffe0: hole next is not a hole>
  <gc check (220): Hole 9248ffe0 header: 9248FD01 00000000 00000020 00000000>
  <gc check (221): from debugger: HEAP: Object931874c0: hole next is not a hole>
  <gc check (221): Hole 931874c0 header: 931873A1 00000000 00000020 00000000>
  <gc check (222): from debugger: HEAP: Object93187820: hole next is not a hole>
  <gc check (222): Hole 93187820 header: 93187761 00000000 00000020 00000000>
  <gc check (223): from debugger: HEAP: Object931879a0: hole next is not a hole>
  <gc check (223): Hole 931879a0 header: 93187941 00000000 00000020 00000000>
  <gc check (224): from debugger: HEAP: Object93187d00: hole next is not a hole>
  <gc check (224): Hole 93187d00 header: 93187C41 00000000 00000020 00000000>
  <gc check (225): from debugger: HEAP: Object93187e40: hole next is not a hole>
  <gc check (225): Hole 93187e40 header: 93187DA1 00000000 00000020 00000000>
  <gc check (226): from debugger: HEAP: Object93187f40: hole next is not a hole>
  <gc check (226): Hole 93187f40 header: 93187EE1 00000000 00000020 00000000>
  <gc check (227): from debugger: HEAP: Object940e8880: hole next is not a hole>
  <gc check (227): Hole 940e8880 header: 940E8421 00000000 00000040 00000000>
  <gc check (228): from debugger: HEAP: Object slot 968a64d8(968a64e8) -> b6e051e0: class pointer not in a class segment>
  <gc check (229): from debugger: HEAP: Object slot b9b18500(b9b18504) -> 83e836a8: class pointer not in a class segment>
done (27590 ms).
Done (27596ms)
```
</details>

**Comment by kgibm** [comment]
Thanks Dmitri! @keithc-ca Do you still plan to re-review?

**Comment by dmitripivkine** [comment]
@keithc-ca Do you have any concerns related to this item?

**Comment by dmitripivkine** [comment]
Jenkins test sanity pLinux jdk17
