### PR TITLE
Issue #14822: Fix variable set but not used compile errors

### LINKED ISSUE #14822: Variable set but not used compile errors on macOS 12.2.1 and XCode 13.3
Received the following errors when following the [JDK 11 compilation steps on macOS](https://github.com/eclipse-openj9/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#macOS):

```
/Users/kevin/git/openj9-openjdk-jdk11/openj9/runtime/shared_common/OSCachesysv.cpp:1539:8: error: variable 'flags' set but not used [-Werror,-Wunused-but-set-variable]
/Users/kevin/git/openj9-openjdk-jdk11/openj9/runtime/vm/jnicsup.cpp:2548:7: error: variable 'check' set but not used [-Werror,-Wunused-but-set-variable]
/Users/kevin/git/openj9-openjdk-jdk11/openj9/runtime/gc_trace_vlhgc/TgcInterRegionReferences.cpp:114:12: error: variable 'thisObjectIn' set but not used [-Werror,-Wunused-but-set-variable]
/Users/kevin/git/openj9-openjdk-jdk11/openj9/runtime/gc_trace_vlhgc/TgcInterRegionReferences.cpp:115:12: error: variable 'thisObjectOut' set but not used [-Werror,-Wunused-but-set-variable]
[...]
```

macOS and XCode versions:

```
$ system_profiler SPSoftwareDataType SPDeveloperToolsDataType
Software:

    System Software Overview:

      System Version: macOS 12.2.1 (21D62)
      Kernel Version: Darwin 21.3.0
      Boot Volume: MainDisk
      Boot Mode: Normal
      Computer Name: Kevin's MacBook Pro
      User Name: Kevin Grigorenko (kevin)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 16 days 2:27

Developer:

    Developer Tools:

      Version: 13.3 (13E113)
      Location: /Applications/Xcode.app
      Applications:
          Xcode: 13.3 (20102)
          Instruments: 13.3 (64552.70)
```

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #14822

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

### CODE REVIEW

File: runtime/vm/jnicsup.cpp [hunk 1]
```diff
@@ -2545,7 +2545,6 @@ defineClass(JNIEnv *env, const char *name, jobject loader, const jbyte *buf, jsi
 		J9TranslationBufferSet *dynamicLoadBuffers;
 		UDATA classNameLength;
 		U_8 * className;
-		U_8 check;
 		U_8 c;
 		U_8 * checkPtr;
```
Comment (keithc-ca) [inline runtime/vm/jnicsup.cpp:2549]: `check` must stay because it should be used on 2578 which should have been
```
		if (0 != (check & 0x80)) {
```
While you're here, please add initialization for these local variables:
```
		J9ClassLoader * classLoader = NULL;
		J9TranslationBufferSet *dynamicLoadBuffers = NULL;
		UDATA classNameLength = 0;
		U_8 * className = NULL;
		U_8 check = 0;
		U_8 c = 0;
		U_8 * checkPtr = NULL;
```

**Review by keithc-ca — CHANGES_REQUESTED** [review]

File: runtime/gc_modron_startup/mmparse.cpp [hunk 2]
```diff
@@ -362,7 +362,9 @@ xlpSubOptionsParser(J9JavaVM *vm, IDATA xlpIndex, XlpError *xlpError, UDATA *req
 
 	/* start parsing with option */
 	parsingStates parsingState = PARSING_FIRST_OPTION;
+#if	defined(J9ZOS390)
```
[the remark this answers is not in the document]
Comment (dmitripivkine) [reply runtime/gc_modron_startup/mmparse.cpp:365]: I think you can just move variable definition down a few lines to block wrapped for J9ZOS390 already

[the remark this answers is not in the document]
Comment (kgibm) [reply runtime/gc_modron_startup/mmparse.cpp:365]: There's no C-style coding practice of declaring variables at the top of the scope?

[the remark this answers is not in the document]
Comment (kgibm) [reply runtime/gc_modron_startup/mmparse.cpp:365]: Oh, I'm sorry, I see what you mean. Disregard my last comment.

**Comment by kgibm** [comment]
@keithc-ca Please re-review when you have a chance. I also cleaned up all of the missing comments on the `#if`s, `#else`s, and `#endif`s in `runtime/shared_common/OSCachesysv.cpp` and hopefully I did it correctly.

**Review by dmitripivkine — APPROVED** [review]
GC part of the code looks good to me. Thank you for cleaning our code!

File: runtime/shared_common/OSCachesysv.cpp [hunk 3]
```diff
@@ -190,7 +190,7 @@ SH_OSCachesysv::startup(J9JavaVM* vm, const char* ctrlDirName, UDATA cacheDirPer
 
 #if defined(WIN32)
 	_semFileName = _cacheNameWithVGen;
-#else
+#else /* !defined(WIN32) */
```
Comment (keithc-ca) [inline runtime/shared_common/OSCachesysv.cpp:193]: The comment should match the expression in the `#if` directive, not its negation.
See https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md#comment-conditional-compilation-directives-if-ifdef-ifndef-else-elif-endif.

File: runtime/shared_common/OSCachesysv.cpp [hunk 4]
```diff
@@ -1355,9 +1353,9 @@ SH_OSCachesysv::printErrorMessage(LastErrorInfo *lastErrorInfo)
 			OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG_ZOS);
 #elif defined(AIXPPC)
```
Comment (keithc-ca) [inline runtime/shared_common/OSCachesysv.cpp:1354]: The comment is missing here:
```
#elif defined(AIXPPC) /* defined(J9ZOS390) */
```

File: runtime/vm/jnicsup.cpp [hunk 5]
```diff
@@ -2541,12 +2541,12 @@ defineClass(JNIEnv *env, const char *name, jobject loader, const jbyte *buf, jsi
...
-		U_8 * className;
-		U_8 check;
-		U_8 c;
+		J9ClassLoader * classLoader = NULL;
+		J9TranslationBufferSet *dynamicLoadBuffers = NULL;
+		UDATA classNameLength = 0;
+		U_8 * className = NULL;
+		U_8 check = 0;
+		U_8 c = 0;
 		U_8 * checkPtr;
```
Comment (keithc-ca) [inline runtime/vm/jnicsup.cpp:2550]: Missing initializer here:
```
		U_8 * checkPtr = NULL;
```

Comment (kgibm) [reply runtime/vm/jnicsup.cpp:2550]: Good catch

File: runtime/shared_common/OSCachesysv.cpp [hunk 6]
```diff
@@ -2686,7 +2688,7 @@ SH_OSCachesysv::getControlFilePerm(char *cacheDirName, char *filename, bool *isN
 	return rc;
 }
 
-#endif
+#endif /* !defined(WIN32) */
```
Comment (keithc-ca) [inline runtime/shared_common/OSCachesysv.cpp:2691]: At first I thought this was a stray `#endif` but it closes the `#if` on line 2274.
There are nested tests of `#if !defined(WIN32)` which are redundant and some dead code in `#else` blocks: can you clean that up too, please?

File: runtime/shared_common/OSCachesysv.cpp [hunk 7]
```diff
@@ -1353,11 +1351,11 @@ SH_OSCachesysv::printErrorMessage(LastErrorInfo *lastErrorInfo)
 		case J9PORT_ERROR_SYSV_IPC_ERRNO_E2BIG:
 #if defined(J9ZOS390)
 			OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG_ZOS);
-#elif defined(AIXPPC)
+#elif defined(AIXPPC) /* defined(J9ZOS390) */
 			OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG_AIX);
-#else
+#else /* defined(AIXPPC) */
```
[the remark this answers is not in the document]
Comment (kgibm) [reply runtime/shared_common/OSCachesysv.cpp:1356]: The coding standard says:

> #elif and #else should have comments that echo the previous condition.

So it seems the `#else` is correct in echoing the `#elif`, right?

```
#if defined(J9ZOS390)
                        OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG_ZOS);
#elif defined(AIXPPC) /* defined(J9ZOS390) */
                        OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG_AIX);
#else /* defined(AIXPPC) */
                        OSC_ERR_TRACE(J9NLS_SHRC_OSCACHE_ERROR_SHMEM_TOOBIG);
#endif /* defined(J9ZOS390) */
```

[the remark this answers is not in the document]
Comment (keithc-ca) [reply runtime/shared_common/OSCachesysv.cpp:1356]: Yes, you are right. Although there are examples of what I suggested, we should follow the documented guidelines.

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
jenkins test sanity alinux64,win jdk17
